`timescale 1ns/1ps
`default_nettype none

module tb_m134_conflict_free_16bank_dualrow_mapper;
    localparam int WORDS = 3680;
    localparam int BANKS = 16;
    localparam int WORD_W = 32;
    localparam int ROW_W = 8;

    logic clk_core;
    logic rst_core;
    logic request_valid;
    logic [11:0] logical_base_word;
    logic [BANKS*WORD_W-1:0] bank_words;
    logic request_legal;
    logic [BANKS*ROW_W-1:0] bank_row_addresses;
    logic [BANKS*WORD_W-1:0] logical_words;
    logic [BANKS-1:0] bank_use_mask;
    logic conflict_free;

    int unsigned legal_windows;
    int unsigned logical_word_checks;
    int unsigned physical_bank_checks;
    int unsigned row_crossing_windows;
    int unsigned illegal_windows;
    int unsigned base_bank_hits [0:BANKS-1];

    m134_conflict_free_16bank_dualrow_mapper dut (.*);
    m134_conflict_free_16bank_dualrow_mapper_assertions sva (.*);

    initial clk_core = 1'b0;
    always #1.5 clk_core = ~clk_core;

    function automatic logic [31:0] word_payload(input int logical_word);
        return 32'h4d000000 ^ logical_word ^ (logical_word << 12);
    endfunction

    task automatic check_legal_window(input int base_word);
        int physical_word;
        @(negedge clk_core);
        request_valid = 1'b1;
        logical_base_word = base_word[11:0];
        bank_words = '0;
        #1ps;
        if (!request_legal || !conflict_free
                || bank_use_mask != 16'hffff)
            $fatal(1, "M134 legal window rejected base=%0d", base_word);

        // Model one word returned from every physical bank at the address
        // generated by the mapper.  Address generation never depends on data.
        for (int bank = 0; bank < BANKS; bank++) begin
            physical_word = bank_row_addresses[bank*ROW_W +: ROW_W]
                            * BANKS + bank;
            if (physical_word < 0 || physical_word >= WORDS)
                $fatal(1, "M134 physical address out of range base=%0d bank=%0d word=%0d",
                       base_word, bank, physical_word);
            bank_words[bank*WORD_W +: WORD_W] =
                word_payload(physical_word);
            physical_bank_checks++;
        end
        #1ps;
        for (int word = 0; word < BANKS; word++) begin
            if (logical_words[word*WORD_W +: WORD_W]
                    !== word_payload(base_word + word))
                $fatal(1, "M134 reordered word mismatch base=%0d word=%0d",
                       base_word, word);
            logical_word_checks++;
        end
        legal_windows++;
        base_bank_hits[base_word & 15]++;
        if ((base_word & 15) != 0)
            row_crossing_windows++;
        @(posedge clk_core);
    endtask

    task automatic check_illegal_window(input int base_word);
        @(negedge clk_core);
        request_valid = 1'b1;
        logical_base_word = base_word[11:0];
        bank_words = '1;
        #1ps;
        if (request_legal || conflict_free || bank_use_mask != 0
                || bank_row_addresses != 0 || logical_words != 0)
            $fatal(1, "M134 illegal window not quarantined base=%0d",
                   base_word);
        illegal_windows++;
        @(posedge clk_core);
    endtask

    initial begin : test_sequence
        rst_core = 1'b1;
        request_valid = 1'b0;
        logical_base_word = '0;
        bank_words = '0;
        legal_windows = 0;
        logical_word_checks = 0;
        physical_bank_checks = 0;
        row_crossing_windows = 0;
        illegal_windows = 0;
        for (int bank = 0; bank < BANKS; bank++)
            base_bank_hits[bank] = 0;

        repeat (3) @(posedge clk_core);
        @(negedge clk_core);
        rst_core = 1'b0;

        // Exhaust every legal starting word, not only aligned dual rows.
        for (int base = 0; base <= WORDS-BANKS; base++)
            check_legal_window(base);

        check_illegal_window(WORDS-BANKS+1);
        check_illegal_window(WORDS-1);
        check_illegal_window((1 << 12)-1);

        @(negedge clk_core);
        request_valid = 1'b0;
        logical_base_word = 12'hfff;
        bank_words = '1;
        #1ps;
        if (request_legal || conflict_free || bank_use_mask != 0
                || bank_row_addresses != 0 || logical_words != 0)
            $fatal(1, "M134 valid-low payload affected outputs");

        for (int bank = 0; bank < BANKS; bank++)
            if (base_bank_hits[bank] == 0)
                $fatal(1, "M134 base-bank offset unhit bank=%0d", bank);
        if (legal_windows != 3665 || logical_word_checks != 58640
                || physical_bank_checks != 58640
                || row_crossing_windows != 3435 || illegal_windows != 3)
            $fatal(1, "M134 counter mismatch windows=%0d logical=%0d physical=%0d crossing=%0d illegal=%0d",
                   legal_windows, logical_word_checks, physical_bank_checks,
                   row_crossing_windows, illegal_windows);

        $display("PASS M134 conflict-free 16-bank dualrow mapper VCS legal_windows=%0d logical_words=%0d physical_bank_reads=%0d row_crossings=%0d base_offsets=16 illegal_windows=%0d words=3680 banks=16 word_bits=32 service_bits=512 reads_per_bank=1 macro=false physical_speedup=false system_speedup=false headline=false",
                 legal_windows, logical_word_checks, physical_bank_checks,
                 row_crossing_windows, illegal_windows);
        $finish;
    end

    initial begin
        #30000000;
        $fatal(1, "M134 directed VCS timeout");
    end
endmodule

`default_nettype wire
