`timescale 1ns/1ps
`default_nettype none

// Area-reference wrapper: three complete, independent 32-lane projection
// engines. Only clock/reset are shared; every transaction interface and state
// output is exposed as a packed three-engine vector.
module gatestack_three_independent32_projection_top #(
    parameter int TOKENS          = 162,
    parameter int LANES           = 32,
    parameter int MAX_TERMS       = 128,
    parameter int RESIDENT_TERMS  = 80,
    parameter int CSR_FORMAT_FADC24 = 0,
    parameter int EVENT_WAYS      = 4,
    parameter int BANKS           = 2,
    parameter int SEGMENT_TOKENS  = 18,
    parameter int GATE_W          = 9,
    parameter int WEIGHT_W        = 8,
    parameter int PRODUCT_W       = GATE_W + WEIGHT_W,
    parameter int ACC_W           = 32,
    parameter bit BIAS_STATIONARY_ENABLE = 1'b0,
    parameter int TAG_W           = 32,
    parameter int INPUT_CH_W      = 10,
    parameter int OUTPUT_TILE_W   = 8,
    parameter int ISSUE_SEQ_W     = 13,
    parameter int HEAD_COUNT_W    = 6,
    parameter int WORD_INDEX_W    = 7,
    parameter int EVENT_COUNT_W   = 13,
    parameter int COUNTER_W       = 32,
    parameter int TOKEN_ID_W      = 8,
    parameter int LANE_ID_W       = (LANES <= 1) ? 1 : $clog2(LANES),
    parameter int WAY_COUNT_W     = $clog2(EVENT_WAYS + 1),
    parameter int ROUTE_W         = 2,
    parameter int FORMAT_W        = 2,
    parameter int RES_TERM_IDX_W  = (RESIDENT_TERMS <= 1) ?
                                      1 : $clog2(RESIDENT_TERMS),
    parameter int IPD_TERM_IDX_W  = (MAX_TERMS <= 1) ? 1 : $clog2(MAX_TERMS)
) (
    input  logic                                      clk_core,
    input  logic                                      rst_core,
    input  logic [2:0]                                tile_start_valid,
    output logic [2:0]                                tile_start_ready,
    input  logic [(3*TAG_W)-1:0]                      tile_start_tag,
    input  logic [(3*OUTPUT_TILE_W)-1:0]              tile_start_output_tile,
    input  logic [(3*HEAD_COUNT_W)-1:0]               tile_start_head_count,
    input  logic [2:0]                                head_start_valid,
    output logic [2:0]                                head_start_ready,
    input  logic [(3*TAG_W)-1:0]                      head_start_tag,
    input  logic [(3*TAG_W)-1:0]                      head_start_payload_tag,
    input  logic [(3*HEAD_COUNT_W)-1:0]               head_start_index,
    input  logic [(3*ROUTE_W)-1:0]                    head_start_route_select,
    input  logic [(3*FORMAT_W)-1:0]                   head_start_csr_format,
    input  logic [(3*INPUT_CH_W)-1:0]                 head_start_input_channel_base,
    input  logic [2:0]                                head_start_last,
    input  logic [(3*8)-1:0]                          resident_term_count,
    input  logic [(3*EVENT_COUNT_W)-1:0]              resident_event_count,

    input  logic [2:0]                                resident_descriptor_valid,
    output logic [2:0]                                resident_descriptor_ready,
    input  logic [(3*GATE_W)-1:0]                     resident_descriptor_gate_code,
    input  logic [(3*LANE_ID_W)-1:0]                  resident_descriptor_lane_id,
    input  logic [(3*8)-1:0]                          resident_descriptor_destination_count,
    input  logic [(3*RES_TERM_IDX_W)-1:0]             resident_descriptor_term_index,
    input  logic [2:0]                                resident_descriptor_last,
    input  logic [2:0]                                resident_word_valid,
    output logic [2:0]                                resident_word_ready,
    input  logic [(3*64)-1:0]                         resident_word_data,
    input  logic [(3*WORD_INDEX_W)-1:0]               resident_word_index,
    input  logic [2:0]                                resident_word_last,

    input  logic [2:0]                                ipd_word_valid,
    output logic [2:0]                                ipd_word_ready,
    input  logic [(3*64)-1:0]                         ipd_word_data,
    input  logic [(3*WORD_INDEX_W)-1:0]               ipd_word_index,
    input  logic [2:0]                                ipd_word_last,
    input  logic [2:0]                                raw_word_valid,
    output logic [2:0]                                raw_word_ready,
    input  logic [(3*64)-1:0]                         raw_word_data,
    input  logic [(3*WORD_INDEX_W)-1:0]               raw_word_index,
    input  logic [2:0]                                raw_word_last,

    output logic [2:0]                                ipd_fill_begin_valid,
    input  logic [2:0]                                ipd_fill_begin_ready,
    output logic [(3*TAG_W)-1:0]                      ipd_fill_begin_tag,
    output logic [(3*8)-1:0]                          ipd_fill_begin_term_count,
    output logic [2:0]                                ipd_fill_entry_valid,
    input  logic [2:0]                                ipd_fill_entry_ready,
    output logic [(3*GATE_W)-1:0]                     ipd_fill_gate_code,
    output logic [(3*LANE_ID_W)-1:0]                  ipd_fill_lane_id,
    output logic [(3*8)-1:0]                          ipd_fill_destination_count,
    output logic [2:0]                                ipd_fill_entry_last,
    output logic [2:0]                                ipd_fill_cache_allowed,

    output logic [2:0]                                weight_req_valid,
    input  logic [2:0]                                weight_req_ready,
    output logic [(3*TAG_W)-1:0]                      weight_req_tag,
    output logic [(3*INPUT_CH_W)-1:0]                 weight_req_input_channel,
    output logic [(3*OUTPUT_TILE_W)-1:0]              weight_req_output_tile,
    input  logic [2:0]                                weight_rsp_valid,
    output logic [2:0]                                weight_rsp_ready,
    input  logic [(3*TAG_W)-1:0]                      weight_rsp_tag,
    input  logic [(3*INPUT_CH_W)-1:0]                 weight_rsp_input_channel,
    input  logic [(3*OUTPUT_TILE_W)-1:0]              weight_rsp_output_tile,
    input  logic [(3*32*WEIGHT_W)-1:0]                weight_rsp_weights,
    output logic [2:0]                                bias_req_valid,
    input  logic [2:0]                                bias_req_ready,
    output logic [(3*TAG_W)-1:0]                      bias_req_tag,
    output logic [(3*OUTPUT_TILE_W)-1:0]              bias_req_output_tile,
    output logic [(3*TOKEN_ID_W)-1:0]                 bias_req_token_id,
    input  logic [2:0]                                bias_rsp_valid,
    output logic [2:0]                                bias_rsp_ready,
    input  logic [(3*TAG_W)-1:0]                      bias_rsp_tag,
    input  logic [(3*TOKEN_ID_W)-1:0]                 bias_rsp_token_id,
    input  logic [(3*32*ACC_W)-1:0]                   bias_rsp_values,
    output logic [(3*BANKS)-1:0]                      final_valid,
    input  logic [(3*BANKS)-1:0]                      final_ready,
    output logic [(3*BANKS*TOKEN_ID_W)-1:0]           final_token_ids,
    output logic [(3*TAG_W)-1:0]                      final_tag,
    output logic [(3*BANKS*32*ACC_W)-1:0]             final_values,

    output logic [2:0]                                decoder_done_valid,
    input  logic [2:0]                                decoder_done_ready,
    output logic [(3*TAG_W)-1:0]                      decoder_done_payload_tag,
    output logic [2:0]                                decoder_done_error,
    output logic [2:0]                                head_done_valid,
    input  logic [2:0]                                head_done_ready,
    output logic [(3*TAG_W)-1:0]                      head_done_tag,
    output logic [(3*HEAD_COUNT_W)-1:0]               head_done_index,
    output logic [2:0]                                head_done_last,
    output logic [2:0]                                head_done_error,
    output logic [2:0]                                tile_done_valid,
    input  logic [2:0]                                tile_done_ready,
    output logic [(3*TAG_W)-1:0]                      tile_done_tag,
    output logic [2:0]                                protocol_error,
    output logic [2:0]                                accumulator_overflow,
    output logic [(3*COUNTER_W)-1:0]                  count_heads,
    output logic [(3*COUNTER_W)-1:0]                  count_terms,
    output logic [(3*COUNTER_W)-1:0]                  count_completed_terms,
    output logic [(3*COUNTER_W)-1:0]                  count_bias_commits
);
    for (genvar bank = 32'd0; bank < 32'd3;
         bank = bank + 32'd1) begin : g_projection_bank
        gatestack_multihead_decoder_projection_top #(
            .TOKENS(TOKENS), .LANES(LANES), .MAX_TERMS(MAX_TERMS),
            .RESIDENT_TERMS(RESIDENT_TERMS),
            .CSR_FORMAT_FADC24(CSR_FORMAT_FADC24),
            .EVENT_WAYS(EVENT_WAYS), .OUT_TILE(32'd32), .BANKS(BANKS),
            .SEGMENT_TOKENS(SEGMENT_TOKENS), .GATE_W(GATE_W),
            .WEIGHT_W(WEIGHT_W), .PRODUCT_W(PRODUCT_W), .ACC_W(ACC_W),
            .BIAS_STATIONARY_ENABLE(BIAS_STATIONARY_ENABLE),
            .TAG_W(TAG_W), .INPUT_CH_W(INPUT_CH_W),
            .OUTPUT_TILE_W(OUTPUT_TILE_W), .ISSUE_SEQ_W(ISSUE_SEQ_W),
            .HEAD_COUNT_W(HEAD_COUNT_W), .WORD_INDEX_W(WORD_INDEX_W),
            .EVENT_COUNT_W(EVENT_COUNT_W), .COUNTER_W(COUNTER_W),
            .TOKEN_ID_W(TOKEN_ID_W), .LANE_ID_W(LANE_ID_W),
            .WAY_COUNT_W(WAY_COUNT_W), .ROUTE_W(ROUTE_W),
            .FORMAT_W(FORMAT_W), .RES_TERM_IDX_W(RES_TERM_IDX_W),
            .IPD_TERM_IDX_W(IPD_TERM_IDX_W)
        ) u_projection (
            .clk_core(clk_core), .rst_core(rst_core),
            .tile_start_valid(tile_start_valid[bank]),
            .tile_start_ready(tile_start_ready[bank]),
            .tile_start_tag(tile_start_tag[(bank*TAG_W) +: TAG_W]),
            .tile_start_output_tile(tile_start_output_tile[(bank*OUTPUT_TILE_W) +: OUTPUT_TILE_W]),
            .tile_start_head_count(tile_start_head_count[(bank*HEAD_COUNT_W) +: HEAD_COUNT_W]),
            .head_start_valid(head_start_valid[bank]),
            .head_start_ready(head_start_ready[bank]),
            .head_start_tag(head_start_tag[(bank*TAG_W) +: TAG_W]),
            .head_start_payload_tag(head_start_payload_tag[(bank*TAG_W) +: TAG_W]),
            .head_start_index(head_start_index[(bank*HEAD_COUNT_W) +: HEAD_COUNT_W]),
            .head_start_route_select(head_start_route_select[(bank*ROUTE_W) +: ROUTE_W]),
            .head_start_csr_format(head_start_csr_format[(bank*FORMAT_W) +: FORMAT_W]),
            .head_start_input_channel_base(head_start_input_channel_base[(bank*INPUT_CH_W) +: INPUT_CH_W]),
            .head_start_last(head_start_last[bank]),
            .resident_term_count(resident_term_count[(bank*8) +: 8]),
            .resident_event_count(resident_event_count[(bank*EVENT_COUNT_W) +: EVENT_COUNT_W]),
            .resident_descriptor_valid(resident_descriptor_valid[bank]),
            .resident_descriptor_ready(resident_descriptor_ready[bank]),
            .resident_descriptor_gate_code(resident_descriptor_gate_code[(bank*GATE_W) +: GATE_W]),
            .resident_descriptor_lane_id(resident_descriptor_lane_id[(bank*LANE_ID_W) +: LANE_ID_W]),
            .resident_descriptor_destination_count(resident_descriptor_destination_count[(bank*8) +: 8]),
            .resident_descriptor_term_index(resident_descriptor_term_index[(bank*RES_TERM_IDX_W) +: RES_TERM_IDX_W]),
            .resident_descriptor_last(resident_descriptor_last[bank]),
            .resident_word_valid(resident_word_valid[bank]),
            .resident_word_ready(resident_word_ready[bank]),
            .resident_word_data(resident_word_data[(bank*64) +: 64]),
            .resident_word_index(resident_word_index[(bank*WORD_INDEX_W) +: WORD_INDEX_W]),
            .resident_word_last(resident_word_last[bank]),
            .ipd_word_valid(ipd_word_valid[bank]),
            .ipd_word_ready(ipd_word_ready[bank]),
            .ipd_word_data(ipd_word_data[(bank*64) +: 64]),
            .ipd_word_index(ipd_word_index[(bank*WORD_INDEX_W) +: WORD_INDEX_W]),
            .ipd_word_last(ipd_word_last[bank]),
            .raw_word_valid(raw_word_valid[bank]),
            .raw_word_ready(raw_word_ready[bank]),
            .raw_word_data(raw_word_data[(bank*64) +: 64]),
            .raw_word_index(raw_word_index[(bank*WORD_INDEX_W) +: WORD_INDEX_W]),
            .raw_word_last(raw_word_last[bank]),
            .ipd_fill_begin_valid(ipd_fill_begin_valid[bank]),
            .ipd_fill_begin_ready(ipd_fill_begin_ready[bank]),
            .ipd_fill_begin_tag(ipd_fill_begin_tag[(bank*TAG_W) +: TAG_W]),
            .ipd_fill_begin_term_count(ipd_fill_begin_term_count[(bank*8) +: 8]),
            .ipd_fill_entry_valid(ipd_fill_entry_valid[bank]),
            .ipd_fill_entry_ready(ipd_fill_entry_ready[bank]),
            .ipd_fill_gate_code(ipd_fill_gate_code[(bank*GATE_W) +: GATE_W]),
            .ipd_fill_lane_id(ipd_fill_lane_id[(bank*LANE_ID_W) +: LANE_ID_W]),
            .ipd_fill_destination_count(ipd_fill_destination_count[(bank*8) +: 8]),
            .ipd_fill_entry_last(ipd_fill_entry_last[bank]),
            .ipd_fill_cache_allowed(ipd_fill_cache_allowed[bank]),
            .weight_req_valid(weight_req_valid[bank]),
            .weight_req_ready(weight_req_ready[bank]),
            .weight_req_tag(weight_req_tag[(bank*TAG_W) +: TAG_W]),
            .weight_req_input_channel(weight_req_input_channel[(bank*INPUT_CH_W) +: INPUT_CH_W]),
            .weight_req_output_tile(weight_req_output_tile[(bank*OUTPUT_TILE_W) +: OUTPUT_TILE_W]),
            .weight_rsp_valid(weight_rsp_valid[bank]),
            .weight_rsp_ready(weight_rsp_ready[bank]),
            .weight_rsp_tag(weight_rsp_tag[(bank*TAG_W) +: TAG_W]),
            .weight_rsp_input_channel(weight_rsp_input_channel[(bank*INPUT_CH_W) +: INPUT_CH_W]),
            .weight_rsp_output_tile(weight_rsp_output_tile[(bank*OUTPUT_TILE_W) +: OUTPUT_TILE_W]),
            .weight_rsp_weights(weight_rsp_weights[(bank*32*WEIGHT_W) +: (32*WEIGHT_W)]),
            .bias_req_valid(bias_req_valid[bank]),
            .bias_req_ready(bias_req_ready[bank]),
            .bias_req_tag(bias_req_tag[(bank*TAG_W) +: TAG_W]),
            .bias_req_output_tile(bias_req_output_tile[(bank*OUTPUT_TILE_W) +: OUTPUT_TILE_W]),
            .bias_req_token_id(bias_req_token_id[(bank*TOKEN_ID_W) +: TOKEN_ID_W]),
            .bias_rsp_valid(bias_rsp_valid[bank]),
            .bias_rsp_ready(bias_rsp_ready[bank]),
            .bias_rsp_tag(bias_rsp_tag[(bank*TAG_W) +: TAG_W]),
            .bias_rsp_token_id(bias_rsp_token_id[(bank*TOKEN_ID_W) +: TOKEN_ID_W]),
            .bias_rsp_values(bias_rsp_values[(bank*32*ACC_W) +: (32*ACC_W)]),
            .final_valid(final_valid[(bank*BANKS) +: BANKS]),
            .final_ready(final_ready[(bank*BANKS) +: BANKS]),
            .final_token_ids(final_token_ids[(bank*BANKS*TOKEN_ID_W) +: (BANKS*TOKEN_ID_W)]),
            .final_tag(final_tag[(bank*TAG_W) +: TAG_W]),
            .final_values(final_values[(bank*BANKS*32*ACC_W) +: (BANKS*32*ACC_W)]),
            .decoder_done_valid(decoder_done_valid[bank]),
            .decoder_done_ready(decoder_done_ready[bank]),
            .decoder_done_payload_tag(decoder_done_payload_tag[(bank*TAG_W) +: TAG_W]),
            .decoder_done_error(decoder_done_error[bank]),
            .head_done_valid(head_done_valid[bank]),
            .head_done_ready(head_done_ready[bank]),
            .head_done_tag(head_done_tag[(bank*TAG_W) +: TAG_W]),
            .head_done_index(head_done_index[(bank*HEAD_COUNT_W) +: HEAD_COUNT_W]),
            .head_done_last(head_done_last[bank]),
            .head_done_error(head_done_error[bank]),
            .tile_done_valid(tile_done_valid[bank]),
            .tile_done_ready(tile_done_ready[bank]),
            .tile_done_tag(tile_done_tag[(bank*TAG_W) +: TAG_W]),
            .protocol_error(protocol_error[bank]),
            .accumulator_overflow(accumulator_overflow[bank]),
            .count_heads(count_heads[(bank*COUNTER_W) +: COUNTER_W]),
            .count_terms(count_terms[(bank*COUNTER_W) +: COUNTER_W]),
            .count_completed_terms(count_completed_terms[(bank*COUNTER_W) +: COUNTER_W]),
            .count_bias_commits(count_bias_commits[(bank*COUNTER_W) +: COUNTER_W])
        );
    end
endmodule

`default_nettype wire
