artifact_uri: file:///root/private_data/work/sdformer_codex/SDformer/mlruns_local/214610415547705293/dc341814cbdf453ebbf92bbb3a9191d3/artifacts
end_time: 1783540200884
entry_point_name: ''
experiment_id: '214610415547705293'
lifecycle_stage: active
run_id: dc341814cbdf453ebbf92bbb3a9191d3
run_name: overjoyed-slug-911
source_name: ''
source_type: 4
source_version: ''
start_time: 1783499610153
status: 3
tags: []
user_id: root
