`timescale 1ns/1ps
`default_nettype none

bind gatestack_dctf96_banklocal_projection_top
    gatestack_dctf96_banklocal_projection_top_assertions #(
        .OUT_TILE(OUT_TILE),
        .ACC_W(ACC_W),
        .TAG_W(TAG_W),
        .INPUT_CH_W(INPUT_CH_W),
        .TOKEN_ID_W(TOKEN_ID_W),
        .OUTPUT_TILE_W(OUTPUT_TILE_W),
        .LOGICAL_SUPERTILE_W(LOGICAL_SUPERTILE_W),
        .HEAD_COUNT_W(HEAD_COUNT_W),
        .EPOCH_W(EPOCH_W)
    ) i_gatestack_dctf96_banklocal_projection_top_assertions (
        .clk_core(clk_core),
        .rst_core(rst_core),
        .flush(flush),
        .tile_start_valid(tile_start_valid),
        .tile_start_ready(tile_start_ready),
        .tile_start_tag(tile_start_tag),
        .tile_start_logical_supertile(tile_start_logical_supertile),
        .tile_start_head_count(tile_start_head_count),
        .head_start_valid(head_start_valid),
        .head_start_ready(head_start_ready),
        .head_start_tag(head_start_tag),
        .head_start_index(head_start_index),
        .head_start_input_channel_base(head_start_input_channel_base),
        .head_start_last(head_start_last),
        .term_ready(term_ready),
        .event_ready(event_ready),
        .source_done_ready(source_done_ready),
        .head_done_valid(head_done_valid),
        .head_done_ready(head_done_ready),
        .head_done_tag(head_done_tag),
        .head_done_index(head_done_index),
        .head_done_last(head_done_last),
        .head_done_error(head_done_error),
        .weight_req_valid(weight_req_valid),
        .weight_req_ready(weight_req_ready),
        .weight_req_tags(weight_req_tags),
        .weight_req_input_channels(weight_req_input_channels),
        .weight_req_output_tiles(weight_req_output_tiles),
        .weight_req_epochs(weight_req_epochs),
        .weight_rsp_ready(weight_rsp_ready),
        .bias_req_valid(bias_req_valid),
        .bias_req_ready(bias_req_ready),
        .bias_req_tags(bias_req_tags),
        .bias_req_output_tiles(bias_req_output_tiles),
        .bias_req_token_ids(bias_req_token_ids),
        .bias_req_epochs(bias_req_epochs),
        .bias_rsp_valid(bias_rsp_valid),
        .bias_rsp_ready(bias_rsp_ready),
        .bias_rsp_epochs(bias_rsp_epochs),
        .final_valid(final_valid),
        .final_ready(final_ready),
        .final_token_ids(final_token_ids),
        .final_tags(final_tags),
        .final_values(final_values),
        .tile_done_valid(tile_done_valid),
        .tile_done_ready(tile_done_ready),
        .tile_done_tag(tile_done_tag),
        .tile_done_error(tile_done_error),
        .protocol_error(protocol_error),
        .state_q(state_q),
        .tile_tag_q(tile_tag_q),
        .source_done_seen_q(source_done_seen_q),
        .source_done_fire(source_done_fire),
        .event_input_fire(event_input_fire),
        .flush_q(flush_q),
        .bias_epoch_q(bias_epoch_q),
        .bias_outstanding_q(bias_outstanding_q),
        .bias_rsp_stale(bias_rsp_stale),
        .bias_rsp_match(bias_rsp_match),
        .bias_rsp_wrong_current(bias_rsp_wrong_current),
        .bias_commit_fire(bias_commit_fire)
    );

`default_nettype wire
