inherit_from: ../sdformer_baseline.yaml

model:
  name: variant_b
  spike_encoder:
    type: temporal_contrast
    temporal_contrast_eps: 1.0e-5
  temporal:
    max_steps: 10
    adaptive_t: true
    early_exit_threshold: 0.02

