data:
  num_chunks: 1
  num_frames: 10
  path: ../../data/Datasets/DSEC/saved_flow_data
  preprocessed: true
  sequence_list_overrides:
    train: train_backend_benchmark_split_seq.csv
    valid: valid_backend_benchmark_split_seq.csv
  spike_th: null
  step_mode: m
experiment: E4_exp_tslif_official_tune_bs12w4_pinfalse_amp
experimental_neuron:
  enabled: true
loader:
  augment:
  - Horizontal
  - Vertical
  - Polarity
  augment_prob:
  - 0.5
  - 0.5
  - 0.0
  batch_multiplyer: 1
  batch_size: 12
  crop:
  - 288
  - 384
  gpu: 0
  max_drop_rate: 0.6
  n_epochs: 1
  n_workers: 4
  non_blocking: true
  parallel: false
  persistent_workers: true
  pin_memory: false
  polarity: true
  prefetch_factor: 4
  resolution:
  - 480
  - 640
  seed: 0
loss:
  clip_grad: 100.0
  flow_regul_weight: 0.001
  gamma: null
  lambda_ang: 0
  lambda_mod: 1
  overwrite_intermediate: false
  training: supervised
metrics:
  flow_scaling: 1
  mask_events: false
  name:
  - AEE
model:
  activations:
  - relu
  - null
  base_num_channels: 96
  encoding: voxel
  final_activation: null
  kernel_size: 3
  mask_output: true
  name: MS_SpikingformerFlowNet_en4
  norm: null
  norm_input: minmax
  num_bins: 10
  use_upsample_conv: false
optimizer:
  lr: 0.0001
  milestones:
  - 2
  - 4
  name: AdamW
  num_acc: 1
  scheduler: multistep
  use_amp: true
  wd: 0.0
runtime:
  snn_backend: torch
  cudnn_benchmark: true
  allow_tf32: true
spiking_neuron:
  detach_reset: false
  neuron_type: exp_tslif
  num_steps: 10
  spike_norm: BN
  surrogate_fun: surrogate.ATan()
  tau: 2.0
  v_reset: 0.0
  v_th: 1.0
swin_transformer:
  base_num_channels: 96
  mlp_ratio: 4
  pretrained_window_size:
  - 0
  - 0
  - 0
  state_combination: none
  swin_depths:
  - 2
  - 2
  - 6
  - 2
  swin_num_heads:
  - 3
  - 6
  - 12
  - 24
  swin_out_indices:
  - 0
  - 1
  - 2
  - 3
  swin_patch_size:
  - 1
  - 1
  - 2
  - 2
  use_arc:
  - swinv1
  - MS_PED_Spiking_PatchEmbed_Conv_sfn
  window_size:
  - 2
  - 9
  - 9
test:
  n_valid: 1
  sample: 10
vis:
  enabled: false
  mask_events: false
  px: 400
  store: false
  store_grads: false
  store_spike_rates: false
  verbose: false
