inherit_from: ../sdformer_baseline.yaml

model:
  name: variant_a
  attention:
    type: window_spike
    window_size: [2, 8, 8]
    pretrained_window_size: [0, 0, 0]
  norm:
    type: RMSNorm
  neuron:
    type: plif
    v_th: 0.1
    v_reset: null
    tau: 2.0

