experiment: E2_exp_atlif_corrected_bench_bs14w4
runtime:
  snn_backend: torch
data:
  path: ../../data/Datasets/DSEC/saved_flow_data
  preprocessed: true
  num_frames: 10
  num_chunks: 1
  step_mode: m
  spike_th: null
  sequence_list_overrides:
    train: train_backend_benchmark_split_seq.csv
    valid: valid_backend_benchmark_split_seq.csv
model:
  name: MS_SpikingformerFlowNet_en4
  encoding: voxel
  norm_input: minmax
  num_bins: 10
  base_num_channels: 96
  kernel_size: 3
  activations:
  - relu
  - null
  final_activation: null
  mask_output: true
  norm: null
  use_upsample_conv: false
swin_transformer:
  use_arc:
  - swinv1
  - MS_PED_Spiking_PatchEmbed_Conv_sfn
  state_combination: none
  base_num_channels: 96
  swin_depths:
  - 2
  - 2
  - 6
  - 2
  swin_num_heads:
  - 3
  - 6
  - 12
  - 24
  swin_out_indices:
  - 0
  - 1
  - 2
  - 3
  swin_patch_size:
  - 1
  - 1
  - 2
  - 2
  window_size:
  - 2
  - 9
  - 9
  pretrained_window_size:
  - 0
  - 0
  - 0
  mlp_ratio: 4
spiking_neuron:
  num_steps: 10
  v_th: 0.1
  v_reset: null
  neuron_type: exp_atlif
  surrogate_fun: surrogate.ATan()
  tau: 2.0
  detach_reset: true
  threshold_eta: 0.0001
  spike_norm: BN
loss:
  training: supervised
  lambda_mod: 1
  lambda_ang: 0
  flow_regul_weight: 0.001
  gamma: null
  clip_grad: 100.0
  overwrite_intermediate: false
optimizer:
  name: AdamW
  lr: 0.0001
  wd: 0.01
  scheduler: multistep
  milestones:
  - 10
  - 20
  - 30
  - 40
  - 50
  - 70
  - 90
  - 120
  use_amp: true
  num_acc: 1
loader:
  n_epochs: 1
  batch_size: 14
  batch_multiplyer: 1
  resolution:
  - 480
  - 640
  augment:
  - Horizontal
  - Vertical
  - Polarity
  augment_prob:
  - 0.5
  - 0.5
  - 0.0
  max_drop_rate: 0.6
  polarity: true
  crop:
  - 288
  - 384
  gpu: 0
  n_workers: 4
  persistent_workers: true
  prefetch_factor: 4
  non_blocking: true
  parallel: false
vis:
  verbose: false
  enabled: false
  px: 400
  store_grads: false
  store: false
  mask_events: false
  store_spike_rates: false
metrics:
  name:
  - AEE
  flow_scaling: 1
  mask_events: false
test:
  sample: 8
  n_valid: 1
experimental_neuron:
  enabled: true
  threshold_update: true
  threshold_lr_scale: 1.0
  activity_eta: 0.0
  min_threshold: 0.001
