name: sdformerflow-hw
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch=2.2
  - torchvision
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - pyyaml
  - tqdm
  - matplotlib
  - opencv
  - imageio
  - numba
  - h5py
  - pytables
  - pip:
      - spikingjelly==0.0.0.0.14
      - timm==0.6.13
      - einops
      - mlflow
      - hdf5plugin
      - omegaconf

