// Imported verbatim Engine and code0 stream helpers are generated by run.py.
#include "default_bn_stream.hpp"
constexpr int PED_STATE=16384;

static std::vector<uint8_t> read_bytes(const char* path) {
    std::ifstream f(path,std::ios::binary|std::ios::ate);assert(f);
    size_t n=f.tellg();f.seekg(0);std::vector<uint8_t>x(n);
    f.read(reinterpret_cast<char*>(x.data()),n);assert(f);return x;
}

struct Join {
    Engine& e;
    const std::vector<uint8_t>& external;
    uint64_t bytes_read=0,decode_slots=0,conversion_issues=0,address_slots=0;
    Join(Engine& engine,const std::vector<uint8_t>& bytes):e(engine),external(bytes){}
    void input(size_t p) {
        // Existing producer interface is spatial/P,T10,C96 packed24.
        // BN still traverses T10,spatial,C96. Each requested288B vector is
        // contiguous, but successive BN positions access a2880B stride.
        size_t t=p/19200,position=p%19200;
        size_t offset=(position*10+t)*288;
        e.tick();++address_slots;
        for(int i=0;i<288;i+=32) {
            e.transfer5();
            for(int j=0;j<4;++j)e.tick(-1,PED_STATE+i+j*8,
                reinterpret_cast<const char*>(external.data()+offset+i+j*8));
            bytes_read+=32;
        }
    }
    void convert(int hg) {
        std::array<uint8_t,24> payload{};
        for(int j=0;j<3;++j) {
            e.tick(PED_STATE+hg*24+j*8);
            if(j)std::memcpy(payload.data()+(j-1)*8,e.sword.data(),8);
        }
        e.tick();std::memcpy(payload.data()+16,e.sword.data(),8);
        // One paid packed24 decode and one vector int24->FP32 conversion.
        // Every signed24 integer is exactly representable in FP32; LOAD
        // executes the conversion value through the same latency4 RF path.
        e.tick();++decode_slots;
        for(int lane=0;lane<8;++lane) {
            uint32_t bits=uint32_t(payload[lane*3])|(uint32_t(payload[lane*3+1])<<8)|
                          (uint32_t(payload[lane*3+2])<<16);
            int32_t value=bits&0x800000?int32_t(bits)-0x1000000:int32_t(bits);
            e.load[lane]=float(value);
        }
        e.op(LOAD,82);++conversion_issues;
        e.op(MUL,83,82,74); // exact power-of-two f14 scale, still charged
    }
};

int main(int argc,char**argv) {
    // live raw projection, tags, affine input coefficients, packed24 PED,
    // intermediate BN output, final output, stress, mode1/2/3.
    assert(argc==9);int mode=std::stoi(argv[8]);assert(mode>=1&&mode<=3);
    auto raw=read(argv[1]);auto tags=read_tags(argv[2]);auto coefficients=read(argv[3]);
    auto ped=read_bytes(argv[4]);
    assert(tags.size()==24000&&ped.size()==55296000&&raw.size()%96==0);
    const size_t n=192000;Engine e(std::stoi(argv[7])!=0);CodeStream stream(e,tags);Join join(e,ped);
    uint64_t raw_bytes=0,intermediate_write_bytes=0,intermediate_read_bytes=0;
    uint64_t final_add_issues=0,zero_count=0;size_t cursor=0;
    e.phase=0;e.coefficients(coefficients);e.constant(74,1536);e.op(ZERO,95);
    for(int hg=0;hg<12;++hg) {
        e.constant(80,hg*32);e.constant(81,384+hg*32);
        e.constant(82,768+hg*32);e.constant(83,1152+hg*32);
        e.op(MUL,12+hg,81,82);e.op(MUL,84,80,12+hg);e.op(SUB,24+hg,83,84);
        e.op(MUL,85,95,12+hg);e.op(ADD,48+hg,85,24+hg);
    }
    std::ofstream intermediate;
    if(mode==1){intermediate.open(argv[5],std::ios::binary);assert(intermediate);}
    std::ofstream output(argv[6],std::ios::binary);assert(output);
    for(size_t p=0;p<n;++p) {
        e.phase=1;bool zero=stream.zero(p);zero_count+=zero;
        if(!zero)for(int hg=0;hg<12;++hg) {
            e.input(raw.data()+cursor*96+hg*8);raw_bytes+=32;
            e.op(MUL,81,80,12+hg);e.op(ADD,hg,81,24+hg);
        }
        cursor+=!zero;
        if(mode==1) {
            e.phase=4;
            for(int hg=0;hg<12;++hg){e.output(zero?48+hg:hg,intermediate);intermediate_write_bytes+=32;}
            continue;
        }
        // Ordinary normalize+PED fusion ALREADY supports a default reference
        // until the actual consumer ADD. Mode3 exposes that same tag interface;
        // there is no extra representation advantage or free consumer.
        e.phase=2;join.input(p);
        for(int hg=0;hg<12;++hg) {
            e.phase=2;join.convert(hg);
            e.phase=3;e.op(ADD,84,zero?48+hg:hg,83);++final_add_issues;e.output(84,output);
        }
    }
    assert(cursor*96==raw.size());
    if(mode==1) {
        intermediate.close();auto normalized=read(argv[5]);assert(normalized.size()==n*96);
        for(size_t p=0;p<n;++p) {
            e.phase=2;join.input(p);
            for(int hg=0;hg<12;++hg) {
                e.phase=4;e.input(normalized.data()+p*96+hg*8);intermediate_read_bytes+=32;
                e.phase=2;join.convert(hg);
                e.phase=3;e.op(ADD,84,80,83);++final_add_issues;e.output(84,output);
            }
        }
    }
    std::cout<<"{\"service_slots\":"<<e.t<<",\"stages\":[";
    for(int i=0;i<5;++i)std::cout<<(i?",":"")<<e.stages[i];
    std::cout<<"],\"SR64_reads\":"<<e.reads<<",\"SW64_writes\":"<<e.writes
        <<",\"CR256_reads\":"<<e.cr<<",\"CW256_writes\":"<<e.cw<<",\"ALU_vector_issues\":"<<e.alu
        <<",\"DMA_slots\":"<<e.dma<<",\"port_or_writeback_waits\":"<<e.waits
        <<",\"raw_read_bytes\":"<<raw_bytes<<",\"PED_packed24_read_bytes\":"<<join.bytes_read
        <<",\"PED_address_slots\":"<<join.address_slots<<",\"PED_decode_slots\":"<<join.decode_slots
        <<",\"PED_conversion_vector_issues\":"<<join.conversion_issues<<",\"final_ADD_vector_issues\":"<<final_add_issues
        <<",\"intermediate_BN_write_bytes\":"<<intermediate_write_bytes<<",\"intermediate_BN_read_bytes\":"<<intermediate_read_bytes
        <<",\"final_write_bytes\":"<<n*384<<",\"tag_read_bytes\":"<<stream.tag_bytes
        <<",\"tag_decode_slots\":"<<stream.decode_slots<<",\"tag_unpack_vector_issues\":"<<stream.tag_unpack
        <<",\"zero_vectors\":"<<zero_count<<"}\n";
}
