#!/usr/bin/env python3
"""batch_3 人工判读（Claude 主会话，2026-09-15）。"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
D = {
'W0004': ('INCORPORATED','多消费者稀疏接口','ExSpike/APEC 活动/乘积稀疏已试（G4 融合布局失败已记录）'),
'W0011': ('FAMILY_COVERED','fiber缓存','Gamma fiber cache 调度/merge 开销属行缓存家族'),
'W0018': ('FAMILY_COVERED','缓存/调度','Avalanche ROD 维护/缓存/调度，家族覆盖且无净硬件结果'),
'W0025': ('APPLICABLE_BLOCKED','平台','Eyeriss 无全文不可继承'),
'W0032': ('FAMILY_COVERED','位宽可组合','Bit Fusion bitbrick 组合属位宽/bityl 家族'),
'W0039': ('FAMILY_COVERED','离群+字典量化','GOBO 离群保真+主体字典，离群组织家族（T8）覆盖'),
'W0046': ('FAMILY_COVERED','稀疏数据流','FireFly-v2 属 SCNN 压缩稀疏数据流家族底座'),
'W0053': ('APPLICABLE_BLOCKED','待核','可配置 CSA 尖峰 Transformer 无全文'),
'W0060': ('FAMILY_COVERED','预测-验证稀疏','A³ 概率跳过属预测门控 attention 家族'),
'W0067': ('FAMILY_COVERED','token剪枝','HeatViT 自适应 token 剪枝+打包保留；本网无 token 稀疏'),
'W0074': ('FAMILY_COVERED','结构化稀疏引擎','FABNet 静态规则结构化稀疏+统一引擎'),
'W0081': ('FAMILY_COVERED','融合DSE','FuseMax 融合数据流设计空间，LoopTree 同族'),
'W0088': ('FAMILY_COVERED','LUT家族','LookupFFN hash 查表 FFN 需训练，LUT 家族覆盖'),
'W0095': ('NOT_APPLICABLE','训练侧','通道排列搜索需重训'),
'W0103': ('FAMILY_COVERED','预测早停','SnaPEA 排序预测执行，C1 精确证书更强'),
'W0110': ('FAMILY_COVERED','惰性执行','LazyGPU dead-write 跳过属 last-use/需求驱动家族，F1 双完成空间已探索'),
'W0117': ('NOT_APPLICABLE','训练协议','PACT 量化训练协议需新模型 AEE'),
'W0124': ('FAMILY_COVERED','融合调度','USEFUSE 融合排程/位序属调度家族'),
'W0131': ('FAMILY_COVERED','逻辑综合家族','LogicNets 低 fan-in 量化共训，da4ml/NeuraLUT 族'),
'W0138': ('FAMILY_COVERED','值复用','Gist memoization 编码生命周期属缓存复用家族'),
'W0145': ('FAMILY_COVERED','无损压缩','LCP 线性压缩页属通用无损压缩家族'),
'W0152': ('FAMILY_COVERED','bit级编码','Laconic 位级编码/负载平衡，BitWave/Stripes 族'),
'W0159': ('NOT_APPLICABLE','算法侧','深度分解学习需事件法向测量'),
'W0168': ('NOT_APPLICABLE','训练侧','活动预算需再生训练'),
'W0176': ('NOT_APPLICABLE','训练侧','Seneca 突触延迟需硬件感知重训；延迟队列供数思想已被时间依赖生存期叙事覆盖'),
'W0183': ('NOT_APPLICABLE','持续学习','CATFormer 阈值/路由持续学习域'),
'W0190': ('NOT_APPLICABLE','生物启发','TDE-3 方向选择先验属算法侧'),
'W0197': ('NOT_APPLICABLE','算法侧','IDNet 时空轨迹迭代去模糊'),
'W0204': ('NOT_APPLICABLE','输入侧','任务驱动事件抑制需掩码重训并改变 AEE 基准'),
'W0211': ('NOT_APPLICABLE','GNN域','EFGCN 事件图构图'),
'W0218': ('NOT_APPLICABLE','架构替换','S3Net 稀疏 stem 需重训'),
'W0225': ('NOT_APPLICABLE','架构替换','Spiking ST-former 未复核'),
'W0232': ('APPLICABLE_BLOCKED','光流算法','EEMFlow 无全文'),
'W0239': ('APPLICABLE_BLOCKED','待核','SNNIM 无全文'),
'W0246': ('NOT_APPLICABLE','前端编码','时差编码器神经元/在线接口未迁移'),
'W0253': ('APPLICABLE_BLOCKED','稀疏加速器','NullHop 无全文'),
'W0260': ('NOT_APPLICABLE','RRAM模拟','Yan RRAM 尖峰引擎'),
'W0267': ('NOT_APPLICABLE','算法侧','FPGA 平面拟合光流（同 W0336 族）'),
'W0286': ('NOT_APPLICABLE','算法侧','FlowFormer cost memory 压缩属算法'),
'W0294': ('NOT_APPLICABLE','平台','三星 6K-MAC NPU'),
'W0301': ('NOT_APPLICABLE','平台','DIANA 双阵列 SoC'),
'W0310': ('NOT_APPLICABLE','平台','UNPU 位宽控制'),
'W0317': ('NOT_APPLICABLE','平台','Marsellus ISSCC 系统'),
'W0324': ('NOT_APPLICABLE','模拟','Spoon 模拟精度训练'),
'W0331': ('APPLICABLE_BLOCKED','光流TCAS-I','2025 自适应光流无全文，同域对照'),
'W0338': ('INCORPORATED','本地变体','AT-LIF_Bu 本地变体'),
'W0345': ('FAMILY_COVERED','层跳过/时步早退','ASTER（与 W0175 重复条目）F2/F4 空间已探索'),
'W0352': ('FAMILY_COVERED','预测-验证稀疏','AccelTran（重复条目）'),
'W0359': ('NOT_APPLICABLE','架构替换','S3Net（重复条目）需重训'),
'W0366': ('APPLICABLE_BLOCKED','严格MSB界','CompRRAE 严格 MSB 界+按位需求门控是证书近邻，无全文待核验'),
'W0373': ('NOT_APPLICABLE','平台','三星 6KMAC（重复条目）'),
'W0380': ('NOT_APPLICABLE','平台','Eyeriss（重复条目）'),
'W0387': ('INCORPORATED','本地提案','PSN θg 判定即停提案'),
'W0394': ('INCORPORATED','本地实验','固定 BN cal32 整数 S0 实验'),
'W0456': ('NOT_APPLICABLE','基准','微眼跳事件基准'),
'W0463': ('NOT_APPLICABLE','数据集','eCARLA 合成事件数据集'),
'W0470': ('NOT_APPLICABLE','应用域','流式细胞术 SNN'),
'W0477': ('NOT_APPLICABLE','分析性工作','稀疏天花板分析可作叙事引用，非机制'),
'W0484': ('NOT_APPLICABLE','编译器','SNN-MLIR 编译桥'),
'W0491': ('NOT_APPLICABLE','量子RL','量子尖峰强化学习'),
'W0498': ('NOT_APPLICABLE','统计','对称随机扫描 Gibbs'),
'W0505': ('FAMILY_COVERED','稀疏供数','压缩权重+零激活门控+gated one-to-all 属 SCNN/零门控家族'),
'W0512': ('FAMILY_COVERED','Gustavson','对角 SpMSpM 脉动阵列属结构化稀疏乘法家族'),
'W0519': ('NOT_APPLICABLE','前端预处理','帧静事件动预处理方法'),
'W0526': ('NOT_APPLICABLE','多模态综述','RGB-事件融合综述'),
'W0533': ('NOT_APPLICABLE','算法侧','非线性运动引导时空注意力'),
'W0540': ('NOT_APPLICABLE','聚变诊断','DIII-D 实时诊断部署'),
'W0547': ('NOT_APPLICABLE','代理模型','Cellular-Potts 代理建模'),
'W0554': ('NOT_APPLICABLE','体系结构综述','分支预测综述'),
'W0561': ('NOT_APPLICABLE','算法侧','强化学习视觉 token 选择'),
'W0568': ('NOT_APPLICABLE','视频生成','DiT 重心插值平滑'),
'W0575': ('NOT_APPLICABLE','信号处理','自适应 chirplet 变换'),
'W0582': ('NOT_APPLICABLE','可持续转型','多系统转型探索性建模'),
'W0589': ('NOT_APPLICABLE','变分推断','熵传输粒子变分推断'),
'W0596': ('NOT_APPLICABLE','鸟类识别','方言鸟鸣识别'),
'W0603': ('NOT_APPLICABLE','Koopman','分布式 Koopman 学习'),
'W0610': ('NOT_APPLICABLE','理论','神经形态架构作数值求解器'),
'W0617': ('NOT_APPLICABLE','平台','SpikON 在线无监督 SNN 加速器'),
'W0624': ('NOT_APPLICABLE','电路CIM','亚阈 SRAM-CIM PVT 闭环'),
'W0631': ('NOT_APPLICABLE','NeRF','Spike-NeRF 辐射场'),
'W0638': ('FAMILY_COVERED','bit级列稀疏','BitWave 列级位稀疏，位平面/LUT 家族已覆盖（全零平面罕见）'),
'W0645': ('NOT_APPLICABLE','ReRAM','ReDy 动态量化 ReRAM'),
'W0652': ('FAMILY_COVERED','渐进精度','Ax-BxP 近似分块渐进精度家族'),
'W0659': ('NOT_APPLICABLE','符号回归','NestyNet 分析力学符号回归'),
'W0666': ('NOT_APPLICABLE','预训练','形式数据预训练'),
'W0673': ('NOT_APPLICABLE','LLM解码','投机解码并行'),
'W0680': ('FAMILY_COVERED','buffer多播','Buffets 多播信用/端口分配家族'),
'W0687': ('APPLICABLE_BLOCKED','待核','Cambricon-S 版本/架构未核'),
'W0694': ('FAMILY_COVERED','稀疏数据流','Systolic Cube 稀疏张量数据流家族'),
'W0701': ('FAMILY_COVERED','数据流tiling','Morph tiling/halo 时间复用家族'),
'W0708': ('INCORPORATED','低秩重组','SmartExchange Codex 接口审阅：40 系数 80B，大卷积权重迁移未试'),
'W0717': ('APPLICABLE_BLOCKED','待核','Celty ICCAD26 已接收待全文'),
'W0725': ('NOT_APPLICABLE','训练侧','SPSRC 谱/核/Frobenius 范数剪枝需训练侧适配'),
'W0732': ('NOT_APPLICABLE','CIM平台','Quartet 数字 CIM 异构张量引擎'),
'W0739': ('NOT_APPLICABLE','标准单元','18T 保持时钟门控触发器'),
'W0746': ('NOT_APPLICABLE','平台','D3TA 时空 attention 加速器；bitmask 家族已覆盖'),
'W0753': ('NOT_APPLICABLE','CIM','NeuC-CIM 电荷域校准宏'),
'W0760': ('NOT_APPLICABLE','LLM低秩','SVD-LLM 激活白化低秩'),
'W0767': ('NOT_APPLICABLE','LLM MoE','MiLo 交替量化补偿'),
'W0774': ('NOT_APPLICABLE','架构替换','ReverB-SNN 实值神经元训练'),
}

recs = json.loads((ROOT / 'input' / 'batch_3.json').read_text())
assert len(recs) == len(D) == 100, (len(recs), len(D))
out = []
for r in recs:
    disp, fam, reason = D[r['id']]
    out.append(json.dumps({'id': r['id'], 'name': r['name'], 'disposition': disp,
                           'family': fam, 'reason': reason}, ensure_ascii=False))
(ROOT / 'output' / 'batch_3.jsonl').write_text('\n'.join(out) + '\n')
print('batch_3 done:', len(out))
