#!/usr/bin/env python3
"""batch_6 人工判读（Claude 主会话，2026-09-15）。"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
D = {
'W0007': ('APPLICABLE_BLOCKED','压缩器近邻','Comperity 正文未取得，算术/状态/编码成本与 θg/T10 兼容性待核'),
'W0014': ('FAMILY_COVERED','调度/缓存','HYTE accessor/stream/buffer/bypass 属调度缓存家族，官方 artifact 完整迁移未做'),
'W0021': ('FAMILY_COVERED','结构化稀疏','VENOM 结构/模式稀疏+官方剪枝先验属结构化稀疏家族'),
'W0028': ('NOT_APPLICABLE','建模方法学','Sparseloop 解析建模框架非机制迁移'),
'W0035': ('FAMILY_COVERED','bit列稀疏','BBS/BitVert 比特列结构化稀疏+免重训二值剪枝属位级/列取消家族'),
'W0042': ('APPLICABLE_BLOCKED','SNN加速器','SpinalFlow 无全文不可继承'),
'W0049': ('FAMILY_COVERED','活动驱动供数','SpikeX 敏捷派发属稀疏供数家族；激活诱导权裁剪需训练侧不适用'),
'W0056': ('APPLICABLE_BLOCKED','电路','COMPASS 无全文不可继承'),
'W0063': ('NOT_APPLICABLE','训练侧','DOTA 检测器联合训练改变生产图'),
'W0070': ('NOT_APPLICABLE','GPU kernel','FlashAttention GPU kernel 工程不可继承到 28nm'),
'W0077': ('FAMILY_COVERED','重排/元数据','PARO 重排+元数据+稀疏量化属重排家族（token 域），元数据税已测'),
'W0084': ('NOT_APPLICABLE','MoE','MoE-OPU overlay/专家驻留需 MoE 网络'),
'W0091': ('NOT_APPLICABLE','传感','VideoTime3 传感差分生产/重置属传感域'),
'W0099': ('FAMILY_COVERED','符号预测','SparseInfer（与 W0357 重复条目）T9 实测符号终止 2.3–7.1% 弱'),
'W0106': ('FAMILY_COVERED','块稀疏tiling','SBNet 块操作+halo/残差属 tiling/halo 家族（Morph 同族）'),
'W0113': ('APPLICABLE_BLOCKED','条件执行','ADET AEU 付费墙未取得，严格/有损条件待核'),
'W0120': ('INCORPORATED','CSE底座','da4ml 精确 CMVM+MSB 界+懒求值已作 t10 CSE 家族对照底座'),
'W0127': ('NOT_APPLICABLE','训练侧','CMM 循环矩阵替换需完整重训'),
'W0134': ('NOT_APPLICABLE','训练侧','MatFormer 嵌套弹性子网需训练'),
'W0141': ('NOT_APPLICABLE','训练侧','DTR 在线策略需训练'),
'W0148': ('FAMILY_COVERED','位深','Dyn-Bitpool TCAS-I 版（与 W0147 同族重复），T1/T1b 已实测'),
'W0155': ('NOT_APPLICABLE','BN执行','FlexAcc BN 统计分阶段属校准/训练域，推理期 BN 已折入'),
'W0163': ('NOT_APPLICABLE','训练侧','Neuron Merging 相似度分解/补偿需重训'),
'W0171': ('APPLICABLE_BLOCKED','PSN谱系','MFPSN 通道独立 PSN+PoT 无乘法动力学为 lifting PSN 强近邻，无全文不可继承'),
'W0179': ('NOT_APPLICABLE','算法侧','脉冲编码+ANN 混合分工属架构对照'),
'W0186': ('NOT_APPLICABLE','前端表示','Spiking Patches 事件 token 分词属前端'),
'W0193': ('NOT_APPLICABLE','算法侧','EventShiftFlow 非学习移位光流基线，仅作对照引用'),
'W0200': ('INCORPORATED','任务底座','E-RAFT 事件相关+迭代光流为 EDCFlow 底座上游'),
'W0207': ('NOT_APPLICABLE','算法侧','DFlow 上下文感知迭代策略需学习策略'),
'W0214': ('FAMILY_COVERED','事件稀疏供数','SNE slice 并行+交叉开关+能量比例活动属稀疏事件供数家族'),
'W0221': ('NOT_APPLICABLE','算法侧','TS-LIF 双出口神经元需训练'),
'W0228': ('INCORPORATED','算法底座','Spike-driven Transformer V2/Meta-SpikeFormer 与 V1 同族，已消化为底座对照'),
'W0235': ('NOT_APPLICABLE','算法侧','尖峰 U-Net 光流前端对照'),
'W0242': ('FAMILY_COVERED','近似终止','Zhang CICC26 光流处理器通道排序推测跳过属近似终止家族（与零差证书冲突）；同域芯片必引对照'),
'W0249': ('NOT_APPLICABLE','前端表示','HD event frames 帧重建前端'),
'W0256': ('NOT_APPLICABLE','CIM','Neuro-CIM（与 W0269 同族重复条目）'),
'W0263': ('APPLICABLE_BLOCKED','光流FPGA','ERAFT FPGA 无全文不可继承'),
'W0270': ('APPLICABLE_BLOCKED','SNN','Clock-free multilevel-event SNN TCAS-I 无全文'),
'W0289': ('FAMILY_COVERED','运动对齐差分','MotionDeltaCNN 运动对齐差分属已否决方向（前端运动对齐 delta）；DeltaCNN 已实测'),
'W0297': ('NOT_APPLICABLE','平台','Wang ISSCC22 渐近稀疏 Transformer（与 W0375 重复条目）'),
'W0304': ('NOT_APPLICABLE','平台','Keller INT4（与 W0379 重复条目）无全文'),
'W0313': ('NOT_APPLICABLE','平台','Thinker 可配置执行底座参考'),
'W0320': ('FAMILY_COVERED','融合/复用','CFMP/ConvFormer 层融合 KV/权复用+注入冗余剪枝属复用/融合调度家族（与 W0369 同工作）'),
'W0327': ('NOT_APPLICABLE','CIM','Si Twin-8T SRAM CIM 未迁移'),
'W0334': ('NOT_APPLICABLE','算法侧','EDFLOW_ABMOF 自适应切片曝光算法'),
'W0341': ('APPLICABLE_BLOCKED','SNN加速器','FireFly-T（与 W0045 重复条目）无全文'),
'W0348': ('APPLICABLE_BLOCKED','待核','SMAM 全文与 venue 待核'),
'W0355': ('NOT_APPLICABLE','训练侧','FlexHiNM-GP_Gyro Hard Concrete 渐进训练需重训'),
'W0362': ('NOT_APPLICABLE','视频生成','SparseVideoGen 视频生成域'),
'W0369': ('APPLICABLE_BLOCKED','CIM','ISSCC25_ConvFormer（与 W0320 同工作）正文未取得'),
'W0376': ('NOT_APPLICABLE','CIM','Tu 位线转置 CIM（与 W0299 重复条目）无全文'),
'W0383': ('NOT_APPLICABLE','平台','Cha ISCAS25 DVS/CIS NPU 平台'),
'W0390': ('INCORPORATED','本地实验','NR4_cost_training_variant 本地变体'),
'W0397': ('APPLICABLE_BLOCKED','待核','HYTE_Buffets 身份待核'),
'W0459': ('NOT_APPLICABLE','光电器件','VCSEL 光子神经形态处理器'),
'W0466': ('NOT_APPLICABLE','光电器件','光子事件加速器模拟光谱切片预处理'),
'W0473': ('NOT_APPLICABLE','模拟前端','NDR 分岔工程尖峰检测属模拟传感前端'),
'W0480': ('NOT_APPLICABLE','训练侧','稳定 SNN 动态 BN 属训练稳定性'),
'W0487': ('NOT_APPLICABLE','训练侧','PrimeSVT 内存感知结构剪枝自动化需训练'),
'W0494': ('NOT_APPLICABLE','软件分析','Apple MPS 解码延迟非单调分析'),
'W0501': ('FAMILY_COVERED','差分族','Loihi 上 Sigma-Delta 阈值化 delta 编码属差分传播家族（DeltaCNN 已实测）；平台为 Loihi 2'),
'W0508': ('NOT_APPLICABLE','统计','贝叶斯多元线性回归'),
'W0515': ('FAMILY_COVERED','稀疏供数','RAMAN 双稀疏+峰值重叠存储+可重构 NoC 属稀疏供数家族'),
'W0522': ('NOT_APPLICABLE','机器人','事件 6D 位姿跟踪'),
'W0529': ('NOT_APPLICABLE','架构替换','SSM/Mamba 事件编码器需重训'),
'W0536': ('NOT_APPLICABLE','定位','EVLoc LiDAR 定位域'),
'W0543': ('NOT_APPLICABLE','NAS','设备条件化 NAS 机器人策略'),
'W0550': ('NOT_APPLICABLE','调谐','加速器 Bayesian 调谐'),
'W0557': ('NOT_APPLICABLE','近似电压域','BNN 电压缩放容错属近似时序域，与零差证书冲突'),
'W0564': ('NOT_APPLICABLE','天线测量','无人机近远场天线算法'),
'W0571': ('NOT_APPLICABLE','视频生成','Sol-Attn 视频生成稀疏注意'),
'W0578': ('NOT_APPLICABLE','数学','组合几何 MCTS'),
'W0585': ('NOT_APPLICABLE','Koopman','Koopman 模态近似'),
'W0592': ('NOT_APPLICABLE','几何','曲线细分神经张力算子'),
'W0599': ('NOT_APPLICABLE','GNN','Sheaf GNN PAC-Bayes'),
'W0606': ('NOT_APPLICABLE','机器人','偏瘫患者日常生活支持'),
'W0613': ('FAMILY_COVERED','时分供数','时分 SNN FSM 协调+尖峰广播+本地权查找属调度/供数家族'),
'W0620': ('NOT_APPLICABLE','平台','ReSCom 可重构 SNN 平台'),
'W0627': ('NOT_APPLICABLE','多模态','MFM 多模态基础模型加速'),
'W0634': ('FAMILY_COVERED','bit-serial','bitSMM 位串行矩阵乘属 bit-serial 家族'),
'W0641': ('FAMILY_COVERED','bit-serial','DSLR-CNN digit-serial 属 bit-serial 家族'),
'W0648': ('FAMILY_COVERED','bit-serial','Bit-balance 位平衡量化协同设计属 bit-serial 家族'),
'W0655': ('NOT_APPLICABLE','LLM剪枝','Debias-SparseGPT LLM 偏差感知剪枝'),
'W0662': ('NOT_APPLICABLE','VLM token','CoverPrune 3D VLM token 剪枝'),
'W0669': ('FAMILY_COVERED','结构化稀疏','列向核压缩+可变列宽 PE+GA 剪枝属结构化稀疏/供数家族'),
'W0676': ('NOT_APPLICABLE','图匹配','子图匹配聚合不变量'),
'W0683': ('FAMILY_COVERED','稀疏供数','Uni-STC 两级 bitmap+排序队列+预请求属 bitmap 供数家族（mode2 部分试过）'),
'W0690': ('APPLICABLE_BLOCKED','待核','OpenEye 身份/scope 未核验'),
'W0697': ('NOT_APPLICABLE','训练侧','SparseNN 预测器/筛选器需训练'),
'W0704': ('INCORPORATED','对照底座','DMP-SNN 线性展开/操作数驻留/寄存器融合已作四轴共同对照；官方 RTL 未迁'),
'W0711': ('NOT_APPLICABLE','LLM','DuoGPT LLM 双稀疏'),
'W0720': ('APPLICABLE_BLOCKED','待核','VSA 身份未核'),
'W0728': ('APPLICABLE_BLOCKED','稀疏阵列','CICC24 非结构稀疏脉冲阵列取数器/索引格式未取得正文'),
'W0735': ('NOT_APPLICABLE','平台','iMCU 数字 IMC 微控制器'),
'W0742': ('FAMILY_COVERED','稀疏供数','HIRB octree 坐标管理+核索引 LUT 取权+scatter 累加属稀疏数据流家族'),
'W0749': ('APPLICABLE_BLOCKED','压缩','跨分布压缩引擎二手摘要不可作已核原理，正文未读'),
'W0756': ('FAMILY_COVERED','值复用','Vecim 源向量跨输出复用+按需写回属复用/需求驱动家族'),
'W0763': ('NOT_APPLICABLE','训练域','FPGA 张量压缩训练，低秩中间驻留属训练'),
'W0770': ('NOT_APPLICABLE','CIM平台','BF16×1-bit CIM 硅数据不可定价本地数字实现'),
}

recs = json.loads((ROOT / 'input' / 'batch_6.json').read_text())
assert len(recs) == len(D) == 99, (len(recs), len(D))
out = []
for r in recs:
    disp, fam, reason = D[r['id']]
    out.append(json.dumps({'id': r['id'], 'name': r['name'], 'disposition': disp,
                           'family': fam, 'reason': reason}, ensure_ascii=False))
(ROOT / 'output' / 'batch_6.jsonl').write_text('\n'.join(out) + '\n')
print('batch_6 done:', len(out))
