#!/usr/bin/env python3
"""batch_4 人工判读（Claude 主会话，2026-09-15）。"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
D = {
'W0005': ('INCORPORATED','模式复用','Phi 层次 pattern/处理器式稀疏执行已作结构剪枝/执行解耦对照'),
'W0012': ('FAMILY_COVERED','Gustavson','Gustavson 算法家族已被稀疏数据流族消化'),
'W0019': ('FAMILY_COVERED','结构化稀疏','HighLight 层次约束+VFMU 不对齐取数属结构化稀疏家族'),
'W0026': ('NOT_APPLICABLE','平台','Eyeriss v2 压缩流/层级 mesh 平台'),
'W0033': ('FAMILY_COVERED','bit偏移编码','Bit-Pragmatic 非零位偏移属 bit-serial 家族；C1 位平面+证书覆盖该轴'),
'W0040': ('FAMILY_COVERED','离群配对','OliVe 离群-牺牲品配对属离群组织家族（T8 实测）'),
'W0047': ('FAMILY_COVERED','双端稀疏','FireFly-S 权+脉冲联合压缩+静默通道识别，SCNN/结构剪枝家族'),
'W0054': ('APPLICABLE_BLOCKED','待核','ESSA 无全文（与 W0342 同族近邻）'),
'W0061': ('APPLICABLE_BLOCKED','待核','Sanger 无全文'),
'W0068': ('NOT_APPLICABLE','平台','ViTCoD 两引擎平台'),
'W0075': ('NOT_APPLICABLE','LLM KV','PagedAttention 分页 KV'),
'W0082': ('NOT_APPLICABLE','MoE','UbiMoE 路由/专家缓存需真实训练'),
'W0089': ('FAMILY_COVERED','数制','并行精确 minifloat MAC 属数制/浮点压缩家族，C1 组级 BFP 覆盖供数域'),
'W0096': ('APPLICABLE_BLOCKED','待核','QP-SNN 无全文'),
'W0104': ('NOT_APPLICABLE','训练侧','CGNet gate/core/tail 需联合训练'),
'W0111': ('APPLICABLE_BLOCKED','待核','DPES 无全文'),
'W0118': ('NOT_APPLICABLE','形式验证','DeepPoly 抽象域传播'),
'W0125': ('NOT_APPLICABLE','训练侧','MADDNESS 森林 hash 训练；LUT 家族已覆盖'),
'W0132': ('NOT_APPLICABLE','LLM','DejaVu 上下文预测稀疏'),
'W0139': ('FAMILY_COVERED','memoization','Echo ISCA20 图变换 memoization 属 Gist 复用家族'),
'W0146': ('FAMILY_COVERED','差分压缩','BDI 基-增量压缩属无损压缩家族'),
'W0153': ('FAMILY_COVERED','bit-serial','BISMO 位串行矩阵引擎属 bit-serial 家族'),
'W0160': ('NOT_APPLICABLE','训练侧','条件低秩需预测训练'),
'W0169': ('NOT_APPLICABLE','训练侧','SOFTS 共享结构 STAR 需任务训练'),
'W0177': ('NOT_APPLICABLE','延迟通路','WVU 零跳转发依赖突触延迟队列，本网无该通路'),
'W0184': ('NOT_APPLICABLE','架构替换','SpiLiFormer 侧抑制掩码需重训'),
'W0191': ('NOT_APPLICABLE','算法侧','可扩展事件驱动时空特征提取'),
'W0198': ('NOT_APPLICABLE','算法侧','EVA-Flow 金字塔 warp+ConvGRU'),
'W0205': ('NOT_APPLICABLE','算法侧','法向流+不确定度过滤'),
'W0212': ('NOT_APPLICABLE','感存算器件','3DS-ISC 器件物理衰减时间戳'),
'W0219': ('NOT_APPLICABLE','算法侧','SAST DSEC mask 需训练'),
'W0226': ('INCORPORATED','算法底座','Spikformer 尖峰自注意力族已消化为本网底座'),
'W0233': ('INCORPORATED','算法底座','EV-FlowNet 事件输入表示/自监督合同底座'),
'W0240': ('NOT_APPLICABLE','CIM','IMPULSE 权膜同宏融合属 SSC CIM 域'),
'W0247': ('NOT_APPLICABLE','算法侧','EvT 事件 transformer 检测'),
'W0254': ('NOT_APPLICABLE','演示平台','DVS+NullHop 演示'),
'W0261': ('NOT_APPLICABLE','SoC平台','Lele 帧-事件跟踪 SoC'),
'W0268': ('NOT_APPLICABLE','前端编码','灵活事件编码'),
'W0287': ('NOT_APPLICABLE','算法侧','VideoFlow RAFT 族算法'),
'W0295': ('NOT_APPLICABLE','平台','蝶形互连 NPU'),
'W0302': ('NOT_APPLICABLE','平台','TinyVers 休眠唤醒'),
'W0311': ('NOT_APPLICABLE','平台','LNPU'),
'W0318': ('NOT_APPLICABLE','平台','SamurAI'),
'W0325': ('NOT_APPLICABLE','CIM','全数字 SRAM CIM'),
'W0332': ('APPLICABLE_BLOCKED','光流TCAS-I','2023 光流跟踪全文待读，同域对照'),
'W0339': ('APPLICABLE_BLOCKED','量化尖峰Transformer','无全文，量化尖峰驱动近邻待核'),
'W0346': ('FAMILY_COVERED','时间并行','PTB 概念经 LoAS/Gustav 时间并行家族已消化'),
'W0353': ('INCORPORATED','本地项目','Motion-XOR 身份（服务费用补测中）'),
'W0360': ('APPLICABLE_BLOCKED','待核','Graham SBNet/SSCN 无目录信息可判'),
'W0367': ('FAMILY_COVERED','CSE','SPARK CSE 属公共子表达式家族，da4ml 覆盖'),
'W0374': ('NOT_APPLICABLE','平台','Tambe ISSCC23 稀疏 transformer'),
'W0381': ('NOT_APPLICABLE','传感','堆叠 CIS/EVS'),
'W0388': ('INCORPORATED','本地实验','patch 连续检查 vs 单许可实验'),
'W0395': ('FAMILY_COVERED','提前终止','TermiNETor 动态卷积先验属终止家族（与 W0102 同族）'),
'W0457': ('NOT_APPLICABLE','训练侧','像素级学阈值需重训'),
'W0464': ('NOT_APPLICABLE','算法侧','TSkips 时间延迟跨层捷径'),
'W0471': ('NOT_APPLICABLE','应用域','事件 OCC 识别与跟踪'),
'W0478': ('NOT_APPLICABLE','存储可靠性','位位置敏感 UEP 属存储保护域；位敏感度思想可作动机引用'),
'W0485': ('NOT_APPLICABLE','DSE工具','MOSAIC 异构 NPU DSE 框架'),
'W0492': ('NOT_APPLICABLE','器件','ECRAM 非平衡动力学'),
'W0499': ('FAMILY_COVERED','稀疏供数','预压缩非零权遍历+尖峰门控累加属稀疏数据流家族'),
'W0506': ('NOT_APPLICABLE','分析性工作','尖峰路由冯诺依曼瓶颈分析'),
'W0513': ('NOT_APPLICABLE','软件HPC','MAGNUS 多线程 SpGEMM 局部性'),
'W0520': ('NOT_APPLICABLE','算法侧','事件 egomotion 几何学习'),
'W0527': ('NOT_APPLICABLE','除雪','事件去雪'),
'W0534': ('NOT_APPLICABLE','算法侧','扰动状态空间光流编码器'),
'W0541': ('NOT_APPLICABLE','DRM安全','Tessera 权重流加密'),
'W0548': ('NOT_APPLICABLE','数据工程','Deep RC 基因/气候数据工程'),
'W0555': ('NOT_APPLICABLE','可靠性','NVM 动态可靠性管理'),
'W0562': ('NOT_APPLICABLE','生成模型','掩码外指令锚定'),
'W0569': ('NOT_APPLICABLE','视频生成','SPADE 输入自适应稀疏注意力 vDiT'),
'W0576': ('NOT_APPLICABLE','扩散','DSTAR 扩散加速'),
'W0583': ('NOT_APPLICABLE','MRI','贝叶斯 MRI 重建 UQ'),
'W0590': ('NOT_APPLICABLE','量子ML','量子 Hilbert 几何原型'),
'W0597': ('NOT_APPLICABLE','SDE','对称 SDE 格式'),
'W0604': ('NOT_APPLICABLE','隐私','混淆表示'),
'W0611': ('NOT_APPLICABLE','众核映射','活动加权多播图划分'),
'W0618': ('FAMILY_COVERED','事件ΔV供数','Mega 九簇核偏移事件 ΔV+膜态交错属 Gustav 时间/事件并行供数家族'),
'W0625': ('NOT_APPLICABLE','多FPGA','NeuroRing 双向环流仿真平台'),
'W0632': ('NOT_APPLICABLE','光学成像','浑浊介质事件成像'),
'W0639': ('NOT_APPLICABLE','训练域','位串行监督学习训练能耗'),
'W0646': ('NOT_APPLICABLE','CIM','BRAMAC 存内 BRAM 计算'),
'W0653': ('FAMILY_COVERED','结构压缩','稠密矩阵结构压缩属权重压缩家族（权重非瓶颈）'),
'W0660': ('NOT_APPLICABLE','生成模型','Swift-Image 紧凑统一模型'),
'W0667': ('NOT_APPLICABLE','VLM token','少视觉 token 的延迟损益分析'),
'W0674': ('NOT_APPLICABLE','VLM token','熵引导 token 剪枝'),
'W0681': ('NOT_APPLICABLE','片上通信','通用片上通信网络'),
'W0688': ('FAMILY_COVERED','零值跳过','Cnvlutin 零激活跳过属经典零跳家族'),
'W0695': ('FAMILY_COVERED','幅值界终止','LeOPArd 幅值界早退属终止家族必引对照（近似界 vs C1 精确证书）'),
'W0702': ('NOT_APPLICABLE','退出头','TLEE 置信度退出头需训练且非严格证书'),
'W0709': ('NOT_APPLICABLE','训练侧','DeepShift 移位权重需共同码本重训'),
'W0718': ('NOT_APPLICABLE','平台','Eyeriss（重复条目）'),
'W0726': ('FAMILY_COVERED','ROM预计算','ROM-LTE 静态 θW 预计算属静态 LUT 基线口径'),
'W0733': ('NOT_APPLICABLE','平台','点云 BEV 处理器'),
'W0740': ('FAMILY_COVERED','条件计算','JSSC21 条件计算 CNN 加速器属条件执行家族'),
'W0747': ('NOT_APPLICABLE','Winograd CIM','Winograd 变换融合+混合域 CIM'),
'W0754': ('APPLICABLE_BLOCKED','混合超分','A-SSCC 混合 CNN/SNN 超分未取得正文'),
'W0761': ('FAMILY_COVERED','低秩','TwinQuant 两级低秩+中间再量化属低秩家族'),
'W0768': ('NOT_APPLICABLE','FPGA平台','HG-PIPE ViT FPGA 流程'),
'W0775': ('FAMILY_COVERED','bit-serial ViT','BSViT 位组量化属 bit-serial ViT 家族近邻，必引划界'),
}

recs = json.loads((ROOT / 'input' / 'batch_4.json').read_text())
assert len(recs) == len(D) == 100, (len(recs), len(D))
out = []
for r in recs:
    disp, fam, reason = D[r['id']]
    out.append(json.dumps({'id': r['id'], 'name': r['name'], 'disposition': disp,
                           'family': fam, 'reason': reason}, ensure_ascii=False))
(ROOT / 'output' / 'batch_4.jsonl').write_text('\n'.join(out) + '\n')
print('batch_4 done:', len(out))
