#!/usr/bin/env python3
"""batch_1 人工判读（Claude 主会话，2026-09-15）。"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
D = {
'W0002': ('INCORPORATED','供数/执行分母','GustavSNN CPTB/NRV/L1D/merger 分母已继承到 lifting 源字对齐'),
'W0009': ('FAMILY_COVERED','预处理压缩','Mailman 预处理收费家族；A 矩阵固定且小，无预处理空间'),
'W0016': ('FAMILY_COVERED','稀疏解码','RISCScalar 掩码压紧/scatter 属稀疏解码家族，CPU ISA 域'),
'W0023': ('FAMILY_COVERED','N:M稀疏','VEGETA 可变 N:M 属 N:M 家族，需协同训练'),
'W0030': ('FAMILY_COVERED','索引稀疏','Cambricon-X 步进索引属经典索引稀疏家族'),
'W0037': ('APPLICABLE_BLOCKED','CIM','BRIM 需正文明确数字 CMOS/CIM 边界'),
'W0044': ('APPLICABLE_BLOCKED','SNN加速器','STELLAR 无全文不可继承'),
'W0051': ('FAMILY_COVERED','零旁路编码','SMAM 位置编码+地址比较旁路零，bitmap 消费者已覆盖同族机制'),
'W0058': ('FAMILY_COVERED','近似算术','L-SPINE 无乘/近似 SIMD 与精确证书口径冲突'),
'W0065': ('FAMILY_COVERED','渐进位供数','Energon 多轮 LSB 请求属位平面供数家族，C1 MSB-first+证书更强'),
'W0072': ('NOT_APPLICABLE','GPU kernel','FlashAttention-3 异步 kernel 工程'),
'W0079': ('FAMILY_COVERED','预测-验证稀疏','SOFA 预测→top-k→正式算属 SparseInfer 同族；本网无 token 稀疏'),
'W0086': ('FAMILY_COVERED','LUT数据通路','LUT-NN 需 INT8 QAT 重训；机制层 LUT 点积已被 t10 无重训实现'),
'W0093': ('FAMILY_COVERED','排列+N:M','FlexHiNM-GP 协同训练家族'),
'W0101': ('INCORPORATED','动态终止','BitFair 学习终止+自适应位序，T1b 照抄对象'),
'W0108': ('APPLICABLE_BLOCKED','剪枝','CompRRAE 无全文不可继承'),
'W0115': ('FAMILY_COVERED','值复用','ConvReLU exact 参考挑选/缓存属 UCNN 复用家族'),
'W0122': ('NOT_APPLICABLE','HLS编译','SPARK-HLS 有条件综合属编译方法学'),
'W0129': ('NOT_APPLICABLE','级联','分类器级联需训练侧代价绑定'),
'W0136': ('NOT_APPLICABLE','训练侧','BNFF BN 重构属训练中间数据搬运优化'),
'W0143': ('NOT_APPLICABLE','DB布局','ByteSlice 数据库列布局，域失配'),
'W0150': ('FAMILY_COVERED','近似算术','控制变量纠偏属近似+校正家族，与零差证书冲突'),
'W0157': ('FAMILY_COVERED','LUT数据通路','LUT-GEMM 量化查表 kernel，t10 LUT 家族覆盖'),
'W0166': ('NOT_APPLICABLE','变换域网络','JPEG 域 ResNet 需字典训练重训'),
'W0174': ('NOT_APPLICABLE','随机比特流','Xpikeformer SSA 随机逻辑乘+模拟混合需重训，非数字路线'),
'W0181': ('NOT_APPLICABLE','架构替换','Spikingformer 需完整重训'),
'W0188': ('NOT_APPLICABLE','架构替换','SLIACF 局部通路+互补融合属算法侧'),
'W0195': ('INCORPORATED','任务底座','EDCFlow 事件光流算法底座（RAFT 下游簇）'),
'W0202': ('NOT_APPLICABLE','GNN域','EvGNN 事件图更新，本网无图层'),
'W0209': ('NOT_APPLICABLE','系统管线','HOMI 端到端系统级管线'),
'W0216': ('NOT_APPLICABLE','平台','TrueNorth 方向敏感前端部署'),
'W0223': ('NOT_APPLICABLE','近似相似度','α-XNOR 需重训近似相似度'),
'W0230': ('NOT_APPLICABLE','架构替换','三值脉冲幅值与二值 {0,θ} 输出身份冲突'),
'W0237': ('NOT_APPLICABLE','综述','事件视觉综述'),
'W0244': ('NOT_APPLICABLE','算法侧','EDFLOW 光流算法'),
'W0251': ('APPLICABLE_BLOCKED','传感触发','Cha DVS/CIS 无全文'),
'W0258': ('APPLICABLE_BLOCKED','SRAM','TFSRAM 无全文'),
'W0265': ('APPLICABLE_BLOCKED','光流加速器','Liu TCAS-I FPGA 无全文，同域对照'),
'W0284': ('INCORPORATED','任务底座','GMFlow 全局匹配算法底座'),
'W0291': ('APPLICABLE_BLOCKED','光流FPGA','RAFT-Lite 题名/全文待核'),
'W0299': ('NOT_APPLICABLE','模拟CIM','位线转置 CIM 变压器，模拟域'),
'W0306': ('NOT_APPLICABLE','平台','Alpha-Vision ISSCC 平台'),
'W0315': ('NOT_APPLICABLE','ISP域','AI-ISP tile/halo 属 ISP 域'),
'W0322': ('FAMILY_COVERED','数据分离','ReTransformer 静态/动态数据分离，C2 权重广播即该组织'),
'W0329': ('NOT_APPLICABLE','模拟域','JSSC 模拟互相关器'),
'W0336': ('NOT_APPLICABLE','算法侧','平面拟合光流 FPGA'),
'W0343': ('APPLICABLE_BLOCKED','SNN attention','Xpikeformer 期刊版无全文'),
'W0350': ('NOT_APPLICABLE','平台','ViTCoD 平台加速器'),
'W0357': ('FAMILY_COVERED','符号预测','SparseInfer 符号预测稀疏家族；T9 实测仅符号终止 2.3–7.1% 弱'),
'W0364': ('INCORPORATED','本地实验','hidden50 通道剪枝方法学实验'),
'W0371': ('NOT_APPLICABLE','CIM平台','X-Former_CIM 待核即平台'),
'W0378': ('NOT_APPLICABLE','平台','QNAP ISSCC 平台'),
'W0385': ('INCORPORATED','本地实验','C2 静态共模共享实验'),
'W0392': ('INCORPORATED','本地实验','support_set 投影共享实验'),
'W0454': ('NOT_APPLICABLE','算法侧','水下事件光流自监督方法'),
'W0461': ('NOT_APPLICABLE','数据集','事件异常检测数据集'),
'W0468': ('NOT_APPLICABLE','算法侧','尖峰相机动态时序表示'),
'W0475': ('NOT_APPLICABLE','片上学习','IMC 零阶微调域，本项目推理固定'),
'W0482': ('NOT_APPLICABLE','雷达通信','调制识别域失配'),
'W0489': ('NOT_APPLICABLE','MoE','SpikingMoE 动态专家融合'),
'W0496': ('NOT_APPLICABLE','激光物理','X 射线自由电子激光'),
'W0503': ('NOT_APPLICABLE','统计','贝叶斯 spike-and-slab 方程发现'),
'W0510': ('FAMILY_COVERED','Gustavson','稀疏张量收缩索引累加属 Gustavson 数据流家族'),
'W0517': ('FAMILY_COVERED','行驻留','GROW 行驻留+runahead 属稀疏数据流家族'),
'W0524': ('NOT_APPLICABLE','算法侧','事件 meshflow 估计'),
'W0531': ('NOT_APPLICABLE','数据集','水下事件数据集'),
'W0538': ('NOT_APPLICABLE','变异测试','DNN 变异无损加速域，机制不可迁移到推理供数'),
'W0545': ('NOT_APPLICABLE','分布式容错','分布式划分容错域'),
'W0552': ('NOT_APPLICABLE','平台','RISC-V IoT SoC'),
'W0559': ('NOT_APPLICABLE','可靠性','NBTI 老化依赖性'),
'W0566': ('NOT_APPLICABLE','音频','6-bit 音频编码 CPU'),
'W0573': ('NOT_APPLICABLE','LLM','相似度驱动层跳过'),
'W0580': ('NOT_APPLICABLE','视频生成','DiT 3D 注意力稀疏'),
'W0587': ('NOT_APPLICABLE','控制','Koopman 鲁棒 tube MPC'),
'W0594': ('NOT_APPLICABLE','UQ','神经算子不确定性量化'),
'W0601': ('NOT_APPLICABLE','流体代理','超图流体代理模型'),
'W0608': ('NOT_APPLICABLE','分子生成','分子图生成'),
'W0615': ('INCORPORATED','计费依据','Sparsity Tax 稀疏开销量化已作杀门计费依据引用'),
'W0622': ('NOT_APPLICABLE','众核NoC','UniSpike 众核尖峰通信压缩，非单核门路域'),
'W0629': ('NOT_APPLICABLE','应用域','水下目标检测 SNN'),
'W0636': ('FAMILY_COVERED','LUT数据通路','Platinum 离线路径+在线捷径 LUT 属 LUT 家族，t10 覆盖'),
'W0643': ('NOT_APPLICABLE','CIM','bit fluid 存内混合精度'),
'W0650': ('FAMILY_COVERED','权重压缩仲裁','bit-serial 权重池：权重供数非瓶颈+压缩仲裁元数据税'),
'W0657': ('NOT_APPLICABLE','LLM训练','N:M 可学习掩码训练'),
'W0664': ('NOT_APPLICABLE','扩散UQ','扩散模型主动采样'),
'W0671': ('NOT_APPLICABLE','工业部署','约束驱动模型优化'),
'W0678': ('NOT_APPLICABLE','LLM缓存','SeaCache KV fiber 缓存'),
'W0685': ('FAMILY_COVERED','重排','FEATHER 交错/重排属调度重排家族'),
'W0692': ('NOT_APPLICABLE','MoE','Pre-gated MoE 路由预测'),
'W0699': ('NOT_APPLICABLE','LLM','EdgeBERT 退出头'),
'W0706': ('INCORPORATED','算法侧','IM-SNN 已由 Codex patch_probe 针对性审阅'),
'W0713': ('APPLICABLE_BLOCKED','SNN稀疏','SpikeNM 身份/录用待核'),
'W0722': ('NOT_APPLICABLE','平台','OpenSpike 开源 SNN 芯片平台'),
'W0730': ('APPLICABLE_BLOCKED','缓存CIM','Pro-Cache-CIM 缓存对象/键/替换代价需正文'),
'W0737': ('NOT_APPLICABLE','CIM平台','22nm 稀疏感知 IMC 系统'),
'W0744': ('FAMILY_COVERED','稀疏供数','SIMO SPad 稀疏权重取激活+多 PE 共享，供数家族覆盖'),
'W0751': ('APPLICABLE_BLOCKED','预测免取','PredLM TCAS-II26 正文未得——预测后免 W 请求强近邻，必须核'),
'W0758': ('NOT_APPLICABLE','训练侧','有序低秩训练可提取多预算模型'),
'W0765': ('FAMILY_COVERED','无损压缩','Atalanta 算术编码张量压缩，ZipServ 同族本地模式已移植'),
'W0772': ('NOT_APPLICABLE','训练方法','时空代理训练+折入推理未移植，算法侧'),
}

recs = json.loads((ROOT / 'input' / 'batch_1.json').read_text())
assert len(recs) == len(D) == 100, (len(recs), len(D))
out = []
for r in recs:
    disp, fam, reason = D[r['id']]
    out.append(json.dumps({'id': r['id'], 'name': r['name'], 'disposition': disp,
                           'family': fam, 'reason': reason}, ensure_ascii=False))
(ROOT / 'output' / 'batch_1.jsonl').write_text('\n'.join(out) + '\n')
print('batch_1 done:', len(out))
