#!/usr/bin/env python3
"""batch_0 人工判读（Claude 主会话，2026-09-15）。DISPO: id -> (disposition, family, reason)"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
D = {
'W0001': ('FAMILY_COVERED','模式/部分和复用','Product sparsity 复用家族已被 Codex Prosperity 探针负结果覆盖'),
'W0008': ('FAMILY_COVERED','递归稀疏元数据','递归元数据+有限供数，元数据税定律下无独立立项价值'),
'W0015': ('FAMILY_COVERED','稀疏调度','动态稀疏重排属调度家族，TSBG 调度核已覆盖；本网无 token 稀疏'),
'W0022': ('FAMILY_COVERED','稀疏调度','时间/结构感知调度先验，TSBG 家族覆盖'),
'W0029': ('FAMILY_COVERED','稀疏GEMM数据流','稀疏数据流优化，无本网可用的非结构化稀疏输入'),
'W0036': ('FAMILY_COVERED','bit级稀疏执行','双操作数比特粒子化属 bit-serial 数据通路家族，t10 LUT 点积已覆盖；全零平面出现率低'),
'W0043': ('APPLICABLE_BLOCKED','attention加速器','无全文不可继承'),
'W0050': ('FAMILY_COVERED','组打包/组稀疏训练','TTB 打包+束级稀疏训练，被粒度定律+T8 元数据税实测覆盖'),
'W0057': ('APPLICABLE_BLOCKED','SNN流式加速','论文待消歧+无全文'),
'W0064': ('APPLICABLE_BLOCKED','attention加速器','无全文不可继承'),
'W0071': ('NOT_APPLICABLE','GPU kernel','FlashAttention-2 是 GPU kernel 工程，无可迁移硬件机制'),
'W0078': ('FAMILY_COVERED','值复用/缓存','复用判定/缓存属 UCNN 输入相似复用家族，已有对照'),
'W0085': ('FAMILY_COVERED','压缩解码','商用 NPU 压缩/解码链，元数据计费家族'),
'W0092': ('FAMILY_COVERED','排列+N:M协同训练','输入排列与 N:M 格式协同训练属结构化稀疏训练家族'),
'W0100': ('APPLICABLE_BLOCKED','幅值分组','GRASP 幅值分组/组预测待核全文与代价'),
'W0107': ('NOT_APPLICABLE','训练侧剪枝','依赖图自动剪枝是训练工具，5页硬件短文不适用'),
'W0114': ('NOT_APPLICABLE','训练侧剪枝','PS4 剪枝+恢复需重训'),
'W0121': ('FAMILY_COVERED','bit级跳零','BitSift 比特级跳零 GEMV；平面内零元已被 t10 LUT 点积自然吸收'),
'W0128': ('NOT_APPLICABLE','级联分类器','Greedy Miser 级联属训练侧，跨T查询并集成本未覆盖也难迁移'),
'W0135': ('FAMILY_COVERED','条件执行','动态 FC2 索引属条件执行家族，fusion_ten_trials 阶段错位已实测'),
'W0142': ('NOT_APPLICABLE','DB扫描编码','BitWeaving 是数据库列编码，域失配；阈值扫描思路已被位平面组织覆盖'),
'W0149': ('FAMILY_COVERED','近似算术','近似乘法+控制变量补偿与精确证书口径冲突，家族已否决'),
'W0156': ('NOT_APPLICABLE','训练侧统计','ACBN 统计精度方法属训练稳定化'),
'W0165': ('NOT_APPLICABLE','网络家族替换','ConvDLGN 换网络家族需重训+AEE 重评，与现网冻结冲突'),
'W0172': ('INCORPORATED','任务底座','SDformerFlow 本身即项目底座'),
'W0180': ('INCORPORATED','任务底座','可学习神经动态+事件体素，算法底座对照已引用'),
'W0187': ('NOT_APPLICABLE','注意力变体','LRF-SSA 需完整迁移重训'),
'W0194': ('INCORPORATED','任务底座','低频参考+高频残差为 HTR 算法底座'),
'W0201': ('INCORPORATED','任务底座','Spike-FlowNet 混合架构对照'),
'W0208': ('NOT_APPLICABLE','稀疏卷积数据流','本网前端已体素化稠密化，无稀疏卷积层可映射'),
'W0215': ('NOT_APPLICABLE','平台旁路','三引擎 SoC 平台级，无机制差分'),
'W0222': ('NOT_APPLICABLE','架构替换','SpikingSSM 需换架构重训'),
'W0229': ('NOT_APPLICABLE','算法侧','SEW 残差语义属算法侧，网络已定型'),
'W0236': ('NOT_APPLICABLE','多传感器','REVIO 依赖额外传感器与状态估计'),
'W0243': ('APPLICABLE_BLOCKED','事件加速器','Eventor 机制细节未核，不可从目录信息重建'),
'W0250': ('NOT_APPLICABLE','平台旁路','航天 neuromorphic FPGA 平台'),
'W0257': ('APPLICABLE_BLOCKED','SNN CIM','无全文不可继承'),
'W0264': ('APPLICABLE_BLOCKED','光流加速器','FlowAcc 无全文，仅能作同域对照基线'),
'W0283': ('INCORPORATED','任务底座','RAFT 全对相关+迭代精修为算法底座'),
'W0290': ('NOT_APPLICABLE','训练/搜索','MEET 内存预算下模型搜索属训练侧'),
'W0298': ('NOT_APPLICABLE','平台旁路','JSSC 芯片平台'),
'W0305': ('NOT_APPLICABLE','平台旁路','预测器芯片平台'),
'W0314': ('NOT_APPLICABLE','平台旁路','DNPU 芯片平台'),
'W0321': ('NOT_APPLICABLE','平台旁路','X-Former 双域平台架构'),
'W0328': ('NOT_APPLICABLE','模拟CIM','SRAM CIM 平台，项目为数字 RTL 路线'),
'W0335': ('NOT_APPLICABLE','算法侧光流','Ultra-Flow 为算法侧光流方法，非硬件机制'),
'W0342': ('APPLICABLE_BLOCKED','事件稀疏attention加速器','ESSA 无全文不可继承'),
'W0349': ('NOT_APPLICABLE','GPU kernel','FlashAttention 无新机制'),
'W0356': ('NOT_APPLICABLE','训练掩码','Avalanche 训练掩码约束属训练侧'),
'W0363': ('INCORPORATED','本地实验','Codex 侧 2:4 方法学实验'),
'W0370': ('APPLICABLE_BLOCKED','SNN CIM','无全文不可继承'),
'W0377': ('NOT_APPLICABLE','平台旁路','ISSCC CIM 芯片平台'),
'W0384': ('INCORPORATED','本地实验','C1-Prosperity 融合 G2G4 本地实验'),
'W0391': ('INCORPORATED','本地实验','class_vs_packed 本地实验'),
'W0398': ('INCORPORATED','本地实验','Flextron 嵌套宽度本地实验'),
'W0460': ('NOT_APPLICABLE','传感侧','神经节式事件传感属传感-任务共训，非加速器机制'),
'W0467': ('NOT_APPLICABLE','多模态算法','RGB-Event 对称融合属算法侧'),
'W0474': ('NOT_APPLICABLE','电力电子','故障穿越限流控制，离主岛'),
'W0481': ('NOT_APPLICABLE','射电天文','太阳射电精细结构，域失配'),
'W0488': ('NOT_APPLICABLE','训练侧剪枝','PSViT 结构化剪枝需重训'),
'W0495': ('NOT_APPLICABLE','弹性架构','Matryoshka 嵌套宽度需嵌套重训，非供数/终止机制'),
'W0502': ('NOT_APPLICABLE','通信','离网盲反卷积/物联网接入，域失配'),
'W0509': ('NOT_APPLICABLE','统计理论','尖峰随机矩阵检测极限'),
'W0516': ('FAMILY_COVERED','稀疏数据流','Flexagon 多数据流 SpMSpM，由 bitmap 消费者/TSBG 家族覆盖'),
'W0523': ('NOT_APPLICABLE','机器人导航','nano-UAV 综述，域失配'),
'W0530': ('NOT_APPLICABLE','算法侧','自监督运动分割，非硬件机制'),
'W0537': ('NOT_APPLICABLE','科学计算','分数阶 SciML 算子，域失配'),
'W0544': ('NOT_APPLICABLE','形式验证','早退网络形式验证，目标与运行时证书不同'),
'W0551': ('NOT_APPLICABLE','GPU可靠性','GPU 永久故障分析'),
'W0558': ('NOT_APPLICABLE','架构替换','动态分组卷积需重训'),
'W0565': ('FAMILY_COVERED','LUT数据通路','FluxBin LUT 化超低位推理，t10 子集和 LUT 已实测同族机制'),
'W0572': ('NOT_APPLICABLE','视频生成','扩散视频生成，域失配'),
'W0579': ('NOT_APPLICABLE','PDE数值','稀疏谱方法，域失配'),
'W0586': ('NOT_APPLICABLE','理论','Lipschitz 认证复杂度下界'),
'W0593': ('NOT_APPLICABLE','最优传输','Monge 映射估计，域失配'),
'W0600': ('NOT_APPLICABLE','算法单元','小波单元需重训'),
'W0607': ('NOT_APPLICABLE','PDE数值','HJ 方程数值解，域失配'),
'W0614': ('NOT_APPLICABLE','平台旁路','SpiNNaker2 众核平台，TOPS/W 旁路计费'),
'W0621': ('FAMILY_COVERED','SNN调度/组播','SupraSNN 映射调度+组播树，TSBG 调度核覆盖'),
'W0628': ('NOT_APPLICABLE','应用域','声纳目标检测 SNN 应用'),
'W0635': ('APPLICABLE_BLOCKED','电路级','GAVINA 欠压需真实电路/PVT 设计，无法由跳过率推频率'),
'W0642': ('NOT_APPLICABLE','模拟CIM','电荷域 CIM，数字 RTL 路线不适用'),
'W0649': ('NOT_APPLICABLE','PIM平台','PIM-DRAM 综述平台'),
'W0656': ('NOT_APPLICABLE','LLM','多模态统一模型路由，域失配'),
'W0663': ('NOT_APPLICABLE','LLM训练','MoE 代理复现失败，域失配'),
'W0670': ('NOT_APPLICABLE','3DGS','高斯泼溅结构简约，域失配'),
'W0677': ('NOT_APPLICABLE','LLM token剪枝','MLLM 视觉 token 剪枝，本网无 token 稀疏门'),
'W0684': ('APPLICABLE_BLOCKED','复用家族','CREW 机制未核，需全文与 UCNN/Phi/TA 对照'),
'W0691': ('NOT_APPLICABLE','视频生成','3DFlashAttention 视频生成域'),
'W0698': ('FAMILY_COVERED','输出组复用','GANAX output-group 属 UCNN 复用家族'),
'W0705': ('NOT_APPLICABLE','训练加速','SNN 并行训练，非推理硬件机制'),
'W0712': ('NOT_APPLICABLE','算法侧','TCJA 时空联合注意力属算法侧'),
'W0721': ('APPLICABLE_BLOCKED','SNN加速器','Spiker+ 机制未核，无目录信息可重建'),
'W0729': ('FAMILY_COVERED','压缩解码','SparseTrim 权重压缩解码：权重广播非激活供数瓶颈+元数据税'),
'W0736': ('APPLICABLE_BLOCKED','电路级','稀疏自适应动态频率需真实关键路径/时钟/PVT'),
'W0743': ('FAMILY_COVERED','近存储驻留','DNC 本地驻留/转向累加已被覆盖（目录 B 注记）'),
'W0750': ('APPLICABLE_BLOCKED','SNN加速器','FSNAP 时间窗自适应机制待核身份'),
'W0757': ('FAMILY_COVERED','列集合','SPIDER 包含依赖列集合，本地 NRV 表示已覆盖该思路'),
'W0764': ('INCORPORATED','压缩','ZipServ 本地 FP32 顺序打包模式已由 Codex 移植'),
'W0771': ('FAMILY_COVERED','离群量化','OFQ-LLM 离群感知量化，T8 同族实测同端口元数据税'),
}

recs = json.loads((ROOT / 'input' / 'batch_0.json').read_text())
assert len(recs) == len(D) == 100, (len(recs), len(D))
out = []
for r in recs:
    disp, fam, reason = D[r['id']]
    out.append(json.dumps({'id': r['id'], 'name': r['name'], 'disposition': disp,
                           'family': fam, 'reason': reason}, ensure_ascii=False))
(ROOT / 'output' / 'batch_0.jsonl').write_text('\n'.join(out) + '\n')
print('batch_0 done:', len(out))
