#!/usr/bin/env python3
"""batch_5 人工判读（Claude 主会话，2026-09-15）。"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
D = {
'W0006': ('INCORPORATED','模式复用','Transitive Array 阵列/虚拟节点调度已作复用家族对照'),
'W0013': ('FAMILY_COVERED','驻留/生存期','ELSA-SNN 权/膜驻留+spine 流水属 F5 生存期/驻留空间（完整双引擎未迁但家族已探索）'),
'W0020': ('NOT_APPLICABLE','训练侧剪枝','CRISP 梯度目标混合剪枝需恢复训练'),
'W0027': ('INCORPORATED','输入复用','UCNN 输入相似复用已作复用家族对照'),
'W0034': ('FAMILY_COVERED','稀疏供数','MASR 双稀疏 bitmask+前后端解耦流水属稀疏供数家族'),
'W0041': ('APPLICABLE_BLOCKED','待核','ANT 无全文'),
'W0048': ('FAMILY_COVERED','二值注意力执行','FireFly-T AND-PopCount 二值注意力引擎属 spike-driven attention popcount 执行家族'),
'W0055': ('FAMILY_COVERED','调度均衡','Skydiver 离线通道负载先验+调度均衡属调度家族'),
'W0062': ('APPLICABLE_BLOCKED','待核','ELSA ISCA21 无全文'),
'W0069': ('NOT_APPLICABLE','DSE工具','Auto-ViT-Acc 自动搜索框架'),
'W0076': ('NOT_APPLICABLE','视频生成','FlightVGM 在线稀疏化视频生成'),
'W0083': ('NOT_APPLICABLE','MoE','Edge-MoE 任务路由'),
'W0090': ('FAMILY_COVERED','LoAS延伸','APEX 近似/精度可调+早退先验属 LoAS 家族延伸'),
'W0098': ('APPLICABLE_BLOCKED','联合剪枝','DJP 全文未取得'),
'W0105': ('NOT_APPLICABLE','训练侧','DynConv 条件卷积需任务损失训练'),
'W0112': ('FAMILY_COVERED','预测压缩','ComPreEND 预测/误差控制压缩家族'),
'W0119': ('FAMILY_COVERED','位平面kernel','T-MAC 低比特位平面+LUT kernel 属位平面数据流家族（软件侧）'),
'W0126': ('NOT_APPLICABLE','训练侧','FFF 森林训练'),
'W0133': ('NOT_APPLICABLE','训练侧','Flextron 弹性子网路由需训练'),
'W0140': ('NOT_APPLICABLE','求解器','Checkmate 训练调度 ILP'),
'W0147': ('FAMILY_COVERED','动态位分配','Dyn-Bitpool 属位深家族（T1/T1b 实测）'),
'W0154': ('NOT_APPLICABLE','训练侧','OPN 离群剪枝需原训练'),
'W0162': ('NOT_APPLICABLE','形式认证','CNN-Cert 认证域'),
'W0170': ('INCORPORATED','PSN底座','并行/带状/滑动 PSN 公式族为本地 T10/lifting PSN 底座'),
'W0178': ('NOT_APPLICABLE','架构替换','MB-LIF 多位机制需新训练'),
'W0185': ('NOT_APPLICABLE','算法侧','SpikePool 池化注意力替换'),
'W0192': ('NOT_APPLICABLE','算法侧','精确事件时序 egomotion'),
'W0199': ('NOT_APPLICABLE','算法侧','TMA 时密相关+lookup 对齐'),
'W0206': ('NOT_APPLICABLE','算法侧','SciFlow 自清洁迭代'),
'W0213': ('NOT_APPLICABLE','前端算法','hARMS 多尺度孔径局部流'),
'W0220': ('FAMILY_COVERED','时间打包+压缩','SpikePack 全时序打包膜电位+zip 压缩属时间折叠/无损压缩家族'),
'W0227': ('INCORPORATED','算法底座','Spike-driven Transformer SDSA 已消化为本网对照底座'),
'W0234': ('NOT_APPLICABLE','算法侧','STE-FlowNet 题名待核的光流算法'),
'W0241': ('FAMILY_COVERED','零跳过/稀疏供数','SpiDR 65nm DSEC 光流芯片属零跳过家族；同域芯片必引对照，迁移未试但家族已覆盖'),
'W0248': ('NOT_APPLICABLE','综述','FPGA 事件视觉综述'),
'W0255': ('APPLICABLE_BLOCKED','光流FPGA','Lele 融合光流无全文'),
'W0262': ('APPLICABLE_BLOCKED','光流','ASNA-Flow 无全文'),
'W0269': ('NOT_APPLICABLE','CIM','Neuro-CIM JSSC 扩展'),
'W0288': ('INCORPORATED','差分传播','DeltaCNN Codex 已测全链（连续基值不适用，1.529×/295MB 记录在案）'),
'W0296': ('NOT_APPLICABLE','平台','Tambe 稀疏 Transformer 处理器'),
'W0303': ('NOT_APPLICABLE','平台','QNAP/EWC/ECP 处理器'),
'W0312': ('NOT_APPLICABLE','平台','Envision'),
'W0319': ('INCORPORATED','CIM同语境','FlexSpIM ISCAS25（与 W0609 同工作）已精读划界'),
'W0326': ('NOT_APPLICABLE','CIM','Khwa 二值 SRAM CIM'),
'W0333': ('NOT_APPLICABLE','传感域','VD56G3 片上 FAST/BRIEF 光流'),
'W0340': ('APPLICABLE_BLOCKED','待核','Spike_Firing_Approx_V3 无目录信息'),
'W0347': ('APPLICABLE_BLOCKED','待核','ISSCC22 UED SNN 无全文'),
'W0354': ('FAMILY_COVERED','排列+N:M','HiNM 输入重排/OBS 补偿（与 W0092 同族）'),
'W0361': ('INCORPORATED','本地笔记','DeltaCNN ASIC 候选映射探索'),
'W0368': ('FAMILY_COVERED','融合调度','USEFUSE 期刊版（与 W0124 同族）'),
'W0375': ('NOT_APPLICABLE','平台','Wang ISSCC22 近似 Transformer'),
'W0382': ('NOT_APPLICABLE','传感','Prophesee/Sony EVS'),
'W0389': ('INCORPORATED','本地实验','patch row34 时间结构实验'),
'W0396': ('INCORPORATED','本地方法学','BNFF+AVP+DavisArel 组合方法学'),
'W0458': ('NOT_APPLICABLE','应用域','微表情瞳孔轨迹后处理'),
'W0465': ('NOT_APPLICABLE','仿真器','SCSim 尖峰相机仿真器'),
'W0472': ('NOT_APPLICABLE','机器人','反重力人形步行控制'),
'W0479': ('NOT_APPLICABLE','算法侧','SpikeDS 双稀疏窗剪枝需训练'),
'W0486': ('NOT_APPLICABLE','映射域','BIDENT 异构算子级映射'),
'W0493': ('NOT_APPLICABLE','信号编码','尖峰带通小波编解码'),
'W0500': ('NOT_APPLICABLE','光电器件','Otters 光 TFT TTFS'),
'W0507': ('NOT_APPLICABLE','训练侧','训练诱导时间差分稀疏'),
'W0514': ('NOT_APPLICABLE','GNN域','NeuraChip GNN 哈希加速'),
'W0521': ('NOT_APPLICABLE','算法侧','LC-Flow 局部连续光流'),
'W0528': ('NOT_APPLICABLE','中微子','IceCube-Gen2 机器学习工具'),
'W0535': ('NOT_APPLICABLE','算法侧','光流+分割联合无监督'),
'W0542': ('NOT_APPLICABLE','HPC','CRONet Versal 拓扑优化'),
'W0549': ('NOT_APPLICABLE','隐私','MLaaS 层划分隐私'),
'W0556': ('NOT_APPLICABLE','DRL调度','SoCRATES 资源自适应调度'),
'W0563': ('NOT_APPLICABLE','视频token','免训练块稀疏视频注意力'),
'W0570': ('NOT_APPLICABLE','材料设计','光催化材料 ML'),
'W0577': ('FAMILY_COVERED','N:M','Micro-Dense 可实现 N:M 推理属 N:M 家族'),
'W0584': ('NOT_APPLICABLE','信号处理','层可调提升小波'),
'W0591': ('NOT_APPLICABLE','Koopman','SACK 安全主动持续学习'),
'W0598': ('NOT_APPLICABLE','空间机器人','空间站机械臂多模态 SNN'),
'W0605': ('NOT_APPLICABLE','Koopman','自调滚动时域估计'),
'W0612': ('NOT_APPLICABLE','训练域','Lonic 在线 SNN 训练共设计；DCOM 零门控属零跳家族已覆盖'),
'W0619': ('FAMILY_COVERED','权重压缩','VQ4SNN 指针+共享码本属权重压缩家族（权重非瓶颈）'),
'W0626': ('NOT_APPLICABLE','平台','低成本 FPGA 事件 SNN 工作流'),
'W0633': ('NOT_APPLICABLE','模拟CIM','YOCO 2.0 端到端模拟 CIM'),
'W0640': ('FAMILY_COVERED','精度缩放','灵活精度缩放属精度/位深家族'),
'W0647': ('NOT_APPLICABLE','PIM器件','AGNI 随机-二进制转换 DRAM'),
'W0654': ('NOT_APPLICABLE','树匹配','阈值树编辑距离'),
'W0661': ('NOT_APPLICABLE','LLM缓存','ReCache KV 复用'),
'W0668': ('NOT_APPLICABLE','LLM token','WIDE 自适应推理 token 剪枝'),
'W0675': ('NOT_APPLICABLE','TSP','图边稀疏化 TSP'),
'W0682': ('FAMILY_COVERED','训练侧格式','TB-STC 二维格式训练，Codex 评估无优势'),
'W0689': ('APPLICABLE_BLOCKED','待核','SpikeSim/SpikeFlow 身份/工具未核'),
'W0696': ('FAMILY_COVERED','预测-验证稀疏','EVA² 预测流加速属 A³/AccelTran 预测家族'),
'W0703': ('APPLICABLE_BLOCKED','神经元剪枝','样本自适应动态神经元剪枝 CICC25 缺正文，边界/恢复未核'),
'W0710': ('NOT_APPLICABLE','训练侧','Monarch 结构化矩阵需训练'),
'W0719': ('NOT_APPLICABLE','平台','ReckOn 在线学习芯片'),
'W0727': ('NOT_APPLICABLE','CIM','OS-CIM 跳权窗口宏'),
'W0734': ('NOT_APPLICABLE','CIM平台','1-TFLOPS BF16 IMC 在线压缩'),
'W0741': ('NOT_APPLICABLE','平台','C-DNN CNN/SNN 异构处理器'),
'W0748': ('APPLICABLE_BLOCKED','待核','ALSCA position-first dataflow 合并规则未核'),
'W0755': ('NOT_APPLICABLE','编译器','Finch 结构化张量编译器'),
'W0762': ('FAMILY_COVERED','低秩','LowRank-SSM 两段 MVM 属低秩家族'),
'W0769': ('NOT_APPLICABLE','平台','SpikeStream Snitch RTL 平台'),
}

recs = json.loads((ROOT / 'input' / 'batch_5.json').read_text())
assert len(recs) == len(D) == 99, (len(recs), len(D))
out = []
for r in recs:
    disp, fam, reason = D[r['id']]
    out.append(json.dumps({'id': r['id'], 'name': r['name'], 'disposition': disp,
                           'family': fam, 'reason': reason}, ensure_ascii=False))
(ROOT / 'output' / 'batch_5.jsonl').write_text('\n'.join(out) + '\n')
print('batch_5 done:', len(out))
