#!/usr/bin/env python3
"""batch_2 人工判读（Claude 主会话，2026-09-15）。"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
D = {
'W0003': ('INCORPORATED','时间并行双稀疏','LoAS FTP+dual-sparse 已作时间打包对照/分母'),
'W0010': ('FAMILY_COVERED','值复用','SumMerge 交集聚合/共享值物化属复用家族'),
'W0017': ('APPLICABLE_BLOCKED','扫描窗调度','ScanNow ICCAD25 IEEE 付费墙，C5 前置杀门未过'),
'W0024': ('INCORPORATED','压缩稀疏数据流','SCNN 经典底座已作非零供数计费分母'),
'W0031': ('FAMILY_COVERED','bit-serial调度','Stripes 位串行宽度分组，C1 位平面组织已覆盖该轴'),
'W0038': ('FAMILY_COVERED','熵编码压缩','EBPC 目录/字对齐收费，压缩元数据税家族'),
'W0045': ('APPLICABLE_BLOCKED','稀疏数据流','FireFly-T 双引擎无全文未迁'),
'W0052': ('FAMILY_COVERED','时间并行','时间步展开 LIF+IAND 属 LoAS/Gustav 时间并行家族'),
'W0059': ('FAMILY_COVERED','级联剪枝+渐进位宽','SpAtten 重要性级联+渐进位宽，剪枝/位深家族已覆盖'),
'W0066': ('FAMILY_COVERED','预测-验证稀疏','AccelTran 动态稀疏 transformer，预测门控家族'),
'W0073': ('FAMILY_COVERED','近似attention','H-FA 近似误差数据流属近似家族'),
'W0080': ('NOT_APPLICABLE','架构替换','FLAT gated-K 替代 softmax 需等价重训'),
'W0087': ('FAMILY_COVERED','LUT算术','LUT-DLA 查表算术，t10+da4ml CSE 家族覆盖'),
'W0094': ('NOT_APPLICABLE','训练侧剪枝','WINS 变换训练开销'),
'W0102': ('FAMILY_COVERED','提前终止','TermiNETor 符号终止，C1 精确区间证书更强且已实测'),
'W0109': ('FAMILY_COVERED','有损近似完成','ThUnderVolt TE-Drop 时序错跳过，与零差证书口径冲突'),
'W0116': ('FAMILY_COVERED','值复用','ConvReLU++ 匹配/参考组织属 UCNN 复用家族'),
'W0123': ('FAMILY_COVERED','CSE','动态 CSE 属公共子表达式家族，da4ml 已覆盖'),
'W0130': ('FAMILY_COVERED','LUT家族','NeuraLUT 稀疏壳+LUT 藏稠密，t10 已把门核点积 LUT 化'),
'W0137': ('NOT_APPLICABLE','训练侧','AVP 训练假设/相关性处理'),
'W0144': ('FAMILY_COVERED','熵编码压缩','tileANS 目录/状态收费，Atalanta/ZipServ 同族'),
'W0151': ('APPLICABLE_BLOCKED','待核','MACISH 无全文'),
'W0158': ('NOT_APPLICABLE','训练侧','Network Deconvolution whitening 需重训'),
'W0167': ('NOT_APPLICABLE','LLM量化','QuaRot 旋转量化域失配'),
'W0175': ('FAMILY_COVERED','层跳过/时步早退','ASTER 任务感知层跳过+置信度早退，F2/F4 空间已探索；PIM 域旁路'),
'W0182': ('NOT_APPLICABLE','架构替换','QKFormer 稠密光流输出需完整训练'),
'W0189': ('NOT_APPLICABLE','架构替换','A²OS²A score/value 编码需重训'),
'W0196': ('NOT_APPLICABLE','算法侧','BAT 双向时间相关运动打包'),
'W0203': ('NOT_APPLICABLE','算法侧','SENeca 同核激活/稀疏正则需重训'),
'W0210': ('NOT_APPLICABLE','前端表示','SSER 异步递归事件表示'),
'W0217': ('INCORPORATED','AT-LIF','AT-LIF 身份已锁定 {0,θ}（θ 折入 W）；原 activity-pruning 日程未复现属算法侧'),
'W0224': ('NOT_APPLICABLE','架构替换','SQKformer 需完整训练'),
'W0231': ('APPLICABLE_BLOCKED','待消歧','MLF neuron 旧笔记身份待核'),
'W0238': ('APPLICABLE_BLOCKED','待核','SpikeSim 身份/框架未补齐'),
'W0245': ('NOT_APPLICABLE','算法侧','BMOF 事件光流块匹配'),
'W0252': ('APPLICABLE_BLOCKED','待核','SPARTA ICCAD25 原文未读'),
'W0259': ('NOT_APPLICABLE','时域模拟','Park 时域 SNN 处理器'),
'W0266': ('APPLICABLE_BLOCKED','光流FPGA','无全文'),
'W0285': ('NOT_APPLICABLE','算法侧','CRAFT 相关体构造'),
'W0292': ('NOT_APPLICABLE','算法侧','Ultra-Flow 光流方法'),
'W0300': ('APPLICABLE_BLOCKED','待核','C-Transformer ISSCC24 无全文'),
'W0307': ('NOT_APPLICABLE','SoC平台','CIS 动作识别 SoC'),
'W0316': ('NOT_APPLICABLE','CIM','集合关联跳零 CIM 宏'),
'W0323': ('NOT_APPLICABLE','模拟','RACE-IT 模拟架构'),
'W0330': ('NOT_APPLICABLE','平台','Eyeriss 经典平台'),
'W0337': ('NOT_APPLICABLE','算法侧','帧-事件融合光流'),
'W0344': ('APPLICABLE_BLOCKED','待核','SPARTA 无全文（与 W0252 重复条目）'),
'W0351': ('APPLICABLE_BLOCKED','待核','A3 近似 attention venue 待核'),
'W0358': ('FAMILY_COVERED','数据流设计空间','LoopTree 保留/重取/重算联合设计已作供数义务叙事先验'),
'W0365': ('NOT_APPLICABLE','MoE','Pre-gated MoE（重复条目）'),
'W0372': ('NOT_APPLICABLE','CIM','Chih ISSCC21 数字 CIM'),
'W0379': ('NOT_APPLICABLE','平台','Keller INT4 处理器'),
'W0386': ('INCORPORATED','本地提案','support_code_zero_response 本地提案'),
'W0393': ('INCORPORATED','本地实验','SVD 低秩 PSN 门实验'),
'W0455': ('NOT_APPLICABLE','训练方法','事件分箱无偏梯度'),
'W0462': ('NOT_APPLICABLE','算法侧','ST-FlowNet 尖峰前端'),
'W0469': ('NOT_APPLICABLE','训练方法','STDP 局部三因子学习'),
'W0476': ('NOT_APPLICABLE','植入式接口','神经信号特征提取'),
'W0483': ('NOT_APPLICABLE','光电器件','Otters++ 光子 TTFS 器件域'),
'W0490': ('NOT_APPLICABLE','LLM','尖峰门控双路径语言模型'),
'W0497': ('NOT_APPLICABLE','统计','组动态因果建模'),
'W0504': ('NOT_APPLICABLE','统计','高维稀疏 GMM 极小极大'),
'W0511': ('FAMILY_COVERED','Gustavson','SegFold 细粒度动态 SpGEMM 数据流家族'),
'W0518': ('NOT_APPLICABLE','HPC软件','FSpGEMM OpenCL 框架'),
'W0525': ('NOT_APPLICABLE','算法侧','立体事件视觉里程计'),
'W0532': ('NOT_APPLICABLE','算法侧','层次稀疏注意力分类'),
'W0539': ('NOT_APPLICABLE','演化计算','自复制与功能涌现'),
'W0546': ('NOT_APPLICABLE','通信','频谱复用'),
'W0553': ('NOT_APPLICABLE','机器人控制','用户条件控制策略'),
'W0560': ('NOT_APPLICABLE','隐私计算','Origami 飞地推理'),
'W0567': ('NOT_APPLICABLE','视频生成','LoSA 稀疏注意力扩散'),
'W0574': ('NOT_APPLICABLE','光电子+训练','Opto-ViT-v2 片上微调'),
'W0581': ('NOT_APPLICABLE','LLM压缩','SCENIC 指令式压缩'),
'W0588': ('NOT_APPLICABLE','神经算子','LiNO 多分辨神经算子'),
'W0595': ('NOT_APPLICABLE','图论','WL 范畴超图'),
'W0602': ('NOT_APPLICABLE','PDE','Lift-and-Embed 求解器'),
'W0609': ('INCORPORATED','CIM同语境','FlexSpIM 已精读并作必引差分对象（全文零处 early termination）'),
'W0616': ('NOT_APPLICABLE','平台框架','AIGOR 模块化神经形态框架'),
'W0623': ('NOT_APPLICABLE','SoC平台','RSNN 异构 SoC'),
'W0630': ('NOT_APPLICABLE','应用域','散射介质神经形态跟踪'),
'W0637': ('FAMILY_COVERED','指数对齐/字宽','分段指针对齐+动态字宽属 BFP/位深家族（CIM 语境），C1 组级 BFP 已覆盖数字域'),
'W0644': ('NOT_APPLICABLE','网络家族','Auto Resonance Network 加速'),
'W0651': ('FAMILY_COVERED','bit级权重稀疏','SWIS 共享权重位稀疏，t10 已覆盖位级执行+权重非瓶颈'),
'W0658': ('NOT_APPLICABLE','机器人规划','宏算子生成'),
'W0665': ('NOT_APPLICABLE','3D VLM','层次空间聚类 token 压缩'),
'W0672': ('NOT_APPLICABLE','3DGS','SpeedyGS 内容感知渲染'),
'W0679': ('FAMILY_COVERED','混合数据流','HyMM buffer 模式切换/依赖转发属数据流家族'),
'W0686': ('FAMILY_COVERED','稀疏求交','SparTen 求交/编排/负载均衡家族'),
'W0693': ('FAMILY_COVERED','量化LUT','PQA PQ 编码+查表消费者，LUT 家族覆盖'),
'W0700': ('NOT_APPLICABLE','平台','Neurocube 经典平台'),
'W0707': ('INCORPORATED','精度门控','Precision Gating Codex 已测 V 整图+粗细门（low8 未胜出，机制未全否）'),
'W0714': ('APPLICABLE_BLOCKED','待核','SLAMP 层自适应剪枝身份待核'),
'W0724': ('FAMILY_COVERED','条件执行','通道门控 NN，fusion_ten_trials 条件执行已实测'),
'W0731': ('NOT_APPLICABLE','CIM','SP-IMC 稀疏存内宏'),
'W0738': ('NOT_APPLICABLE','平台','DualLearn SNN-ANN 处理器'),
'W0745': ('NOT_APPLICABLE','训练域','FP4/FP8 shift-add 训练处理器；shift-add 家族 t10 已覆盖推理域'),
'W0752': ('NOT_APPLICABLE','混合信号','SENNA 电路交换混合信号，非数字 RTL 路线'),
'W0759': ('NOT_APPLICABLE','训练侧低秩','FLRC 逐层秩分配'),
'W0766': ('FAMILY_COVERED','熵编码压缩','Shannonic 熵最优压缩，Atalanta/ZipServ 同族'),
'W0773': ('NOT_APPLICABLE','算法侧','VISTREAM 时空分叉流式推理'),
}

recs = json.loads((ROOT / 'input' / 'batch_2.json').read_text())
assert len(recs) == len(D) == 100, (len(recs), len(D))
out = []
for r in recs:
    disp, fam, reason = D[r['id']]
    out.append(json.dumps({'id': r['id'], 'name': r['name'], 'disposition': disp,
                           'family': fam, 'reason': reason}, ensure_ascii=False))
(ROOT / 'output' / 'batch_2.jsonl').write_text('\n'.join(out) + '\n')
print('batch_2 done:', len(out))
