`timescale 1ns/1ps
`default_nettype none

// Integration boundary for the C0 on-chip builder backend. This module only
// wires the checked serializer commit stream into the shared typed head slots.
module gatestack_typed_builder_commit_top #(
    parameter int TOKENS             = 162,
    parameter int LANES              = 32,
    parameter int GATE_W             = 9,
    parameter int MAX_TERMS          = 128,
    parameter int CONTEXTS           = 2,
    parameter int HEADS              = 24,
    parameter int SLOT_WORDS         = 104,
    parameter int WORD_W             = 64,
    parameter int TAG_W              = 32,
    parameter int FORMAT_W           = 2,
    parameter int SIZE_W             = 16,
    parameter int COUNTER_W          = 32,
    parameter int BITMAP_BYPASS_ENABLE = 0,
    parameter int CONTEXT_ID_W       = (CONTEXTS <= 1) ? 1 : $clog2(CONTEXTS),
    parameter int HEAD_ID_W          = (HEADS <= 1) ? 1 : $clog2(HEADS),
    parameter int WORD_INDEX_W       = (SLOT_WORDS <= 1) ? 1 : $clog2(SLOT_WORDS)
) (
    input  logic                         clk_core,
    input  logic                         rst_core,

    input  logic                         begin_valid,
    output logic                         begin_ready,
    input  logic [CONTEXT_ID_W-1:0]      begin_context_id,
    input  logic [HEAD_ID_W-1:0]         begin_head_id,
    input  logic [TAG_W-1:0]             begin_tag,
    input  logic [FORMAT_W-1:0]          begin_format,
    input  logic [SIZE_W-1:0]            begin_expected_payload_bits,
    input  logic [3:0]                   begin_active_classes,
    input  logic [7:0]                   begin_active_tokens,
    input  logic [7:0]                   begin_term_count,
    input  logic [12:0]                  begin_event_count,
    input  logic [7:0]                   begin_bitmap_term_count,
    input  logic [12:0]                  begin_fadc_destination_bytes,
    input  logic                         descriptor_valid,
    output logic                         descriptor_ready,
    input  logic [8:0]                   descriptor_gate_code,
    input  logic [4:0]                   descriptor_lane_id,
    input  logic [7:0]                   descriptor_destination_count,
    input  logic                         descriptor_last,
    input  logic                         destination_valid,
    output logic                         destination_ready,
    input  logic [7:0]                   destination_token_id,
    input  logic                         destination_last_for_term,
    input  logic                         destination_bitmap_valid,
    output logic                         destination_bitmap_ready,
    input  logic [TOKENS-1:0]            destination_bitmap,
    input  logic                         raw_token_valid,
    output logic                         raw_token_ready,
    input  logic [7:0]                   raw_token_id,
    input  logic [GATE_W-1:0]            raw_gate_code,
    input  logic [LANES-1:0]             raw_k_bits,

    output logic                         builder_done_valid,
    input  logic                         builder_done_ready,
    output logic [TAG_W-1:0]             builder_done_tag,
    output logic [FORMAT_W-1:0]          builder_done_format,
    output logic                         builder_done_error,
    output logic [7:0]                   builder_done_word_count,

    input  logic                         inspect_valid,
    output logic                         inspect_ready,
    input  logic [CONTEXT_ID_W-1:0]      inspect_context_id,
    input  logic [HEAD_ID_W-1:0]         inspect_head_id,
    output logic                         inspect_meta_valid,
    input  logic                         inspect_meta_ready,
    output logic                         inspect_exists,
    output logic [TAG_W-1:0]             inspect_tag,
    output logic                         inspect_mode_is_csr,
    output logic [FORMAT_W-1:0]          inspect_format,
    output logic [SIZE_W-1:0]            inspect_payload_bits,
    output logic [SIZE_W-1:0]            inspect_word_count,

    input  logic                         replay_begin_valid,
    output logic                         replay_begin_ready,
    input  logic [CONTEXT_ID_W-1:0]      replay_context_id,
    input  logic [HEAD_ID_W-1:0]         replay_head_id,
    input  logic [WORD_INDEX_W-1:0]      replay_start_word,
    output logic                         replay_word_valid,
    input  logic                         replay_word_ready,
    output logic [WORD_W-1:0]            replay_word_data,
    output logic [WORD_INDEX_W-1:0]      replay_word_index,
    output logic                         replay_word_last,
    output logic [TAG_W-1:0]             replay_tag,
    output logic                         replay_mode_is_csr,
    output logic [FORMAT_W-1:0]          replay_format,
    output logic [SIZE_W-1:0]            replay_payload_bits,

    input  logic                         release_valid,
    output logic                         release_ready,
    input  logic [CONTEXT_ID_W-1:0]      release_context_id,
    input  logic [HEAD_ID_W-1:0]         release_head_id,

    output logic [(CONTEXTS*HEADS)-1:0]  slot_valid_flat,
    output logic                         commit_session_active,
    output logic                         replay_session_active,
    output logic                         serializer_protocol_error,
    output logic                         slot_protocol_error,
    output logic [COUNTER_W-1:0]         count_builder_heads,
    output logic [COUNTER_W-1:0]         count_builder_committed_heads,
    output logic [COUNTER_W-1:0]         count_builder_aborted_heads,
    output logic [COUNTER_W-1:0]         count_builder_committed_words,
    output logic [COUNTER_W-1:0]         count_builder_input_stall_cycles,
    output logic [COUNTER_W-1:0]         count_builder_output_stall_cycles,
    output logic [COUNTER_W-1:0]         count_slot_commit_heads,
    output logic [COUNTER_W-1:0]         count_slot_replay_heads,
    output logic [COUNTER_W-1:0]         count_slot_release_heads,
    output logic [COUNTER_W-1:0]         count_slot_invalid_headers,
    output logic [COUNTER_W-1:0]         count_slot_commit_stall_cycles,
    output logic [COUNTER_W-1:0]         count_slot_replay_stall_cycles
);

    logic commit_begin_valid;
    logic commit_begin_ready;
    logic [CONTEXT_ID_W-1:0] commit_context_id;
    logic [HEAD_ID_W-1:0] commit_head_id;
    logic [TAG_W-1:0] commit_tag;
    logic commit_mode_is_csr;
    logic [SIZE_W-1:0] commit_payload_bits;
    logic commit_word_valid;
    logic commit_word_ready;
    logic [WORD_W-1:0] commit_word_data;
    logic commit_word_last;

    gatestack_typed_payload_serializer #(
        .TOKENS(TOKENS),
        .LANES(LANES),
        .GATE_W(GATE_W),
        .MAX_TERMS(MAX_TERMS),
        .SLOT_WORDS(SLOT_WORDS),
        .WORD_W(WORD_W),
        .TAG_W(TAG_W),
        .FORMAT_W(FORMAT_W),
        .SIZE_W(SIZE_W),
        .CONTEXTS(CONTEXTS),
        .HEADS(HEADS),
        .COUNTER_W(COUNTER_W),
        .BITMAP_BYPASS_ENABLE(BITMAP_BYPASS_ENABLE)
    ) u_serializer (
        .clk_core,
        .rst_core,
        .begin_valid,
        .begin_ready,
        .begin_context_id,
        .begin_head_id,
        .begin_tag,
        .begin_format,
        .begin_expected_payload_bits,
        .begin_active_classes,
        .begin_active_tokens,
        .begin_term_count,
        .begin_event_count,
        .begin_bitmap_term_count,
        .begin_fadc_destination_bytes,
        .descriptor_valid,
        .descriptor_ready,
        .descriptor_gate_code,
        .descriptor_lane_id,
        .descriptor_destination_count,
        .descriptor_last,
        .destination_valid,
        .destination_ready,
        .destination_token_id,
        .destination_last_for_term,
        .destination_bitmap_valid,
        .destination_bitmap_ready,
        .destination_bitmap,
        .raw_token_valid,
        .raw_token_ready,
        .raw_token_id,
        .raw_gate_code,
        .raw_k_bits,
        .commit_begin_valid,
        .commit_begin_ready,
        .commit_context_id,
        .commit_head_id,
        .commit_tag,
        .commit_mode_is_csr,
        .commit_payload_bits,
        .commit_word_valid,
        .commit_word_ready,
        .commit_word_data,
        .commit_word_last,
        .done_valid(builder_done_valid),
        .done_ready(builder_done_ready),
        .done_tag(builder_done_tag),
        .done_format(builder_done_format),
        .done_error(builder_done_error),
        .done_word_count(builder_done_word_count),
        .protocol_error(serializer_protocol_error),
        .count_heads(count_builder_heads),
        .count_committed_heads(count_builder_committed_heads),
        .count_aborted_heads(count_builder_aborted_heads),
        .count_committed_words(count_builder_committed_words),
        .count_input_stall_cycles(count_builder_input_stall_cycles),
        .count_output_stall_cycles(count_builder_output_stall_cycles)
    );

    gatestack_head_slot_sram_adapter #(
        .CONTEXTS(CONTEXTS),
        .HEADS(HEADS),
        .HEAD_BITS(TOKENS * (LANES + GATE_W)),
        .WORD_W(WORD_W),
        .SLOT_CAPACITY_BITS(SLOT_WORDS * WORD_W),
        .TAG_W(TAG_W),
        .SIZE_W(SIZE_W),
        .FORMAT_W(FORMAT_W),
        .COUNTER_W(COUNTER_W)
    ) u_slot_adapter (
        .clk_core,
        .rst_core,
        .commit_begin_valid,
        .commit_begin_ready,
        .commit_context_id,
        .commit_head_id,
        .commit_tag,
        .commit_mode_is_csr,
        .commit_payload_bits,
        .commit_word_valid,
        .commit_word_ready,
        .commit_word_data,
        .commit_word_last,
        .inspect_valid,
        .inspect_ready,
        .inspect_context_id,
        .inspect_head_id,
        .inspect_meta_valid,
        .inspect_meta_ready,
        .inspect_exists,
        .inspect_tag,
        .inspect_mode_is_csr,
        .inspect_format,
        .inspect_payload_bits,
        .inspect_word_count,
        .replay_begin_valid,
        .replay_begin_ready,
        .replay_context_id,
        .replay_head_id,
        .replay_start_word,
        .replay_word_valid,
        .replay_word_ready,
        .replay_word_data,
        .replay_word_index,
        .replay_word_last,
        .replay_tag,
        .replay_mode_is_csr,
        .replay_format,
        .replay_payload_bits,
        .release_valid,
        .release_ready,
        .release_context_id,
        .release_head_id,
        .commit_session_active,
        .replay_session_active,
        .slot_valid_flat,
        .protocol_error(slot_protocol_error),
        .count_commit_heads(count_slot_commit_heads),
        .count_replay_heads(count_slot_replay_heads),
        .count_release_heads(count_slot_release_heads),
        .count_invalid_headers(count_slot_invalid_headers),
        .count_commit_stall_cycles(count_slot_commit_stall_cycles),
        .count_replay_stall_cycles(count_slot_replay_stall_cycles)
    );

endmodule

`default_nettype wire
