artifact_location: file:///root/private_data/work/sdformer_codex/SDformer/mlruns_local/791161773545750616
creation_time: 1782821068176
experiment_id: '791161773545750616'
last_update_time: 1782821068176
lifecycle_stage: active
name: date11_ttx_mdr_mvsec_route_fast_workers6_cpuvoxel
trace_location: null
workspace: default
