artifact_uri: file:///root/private_data/work/sdformer_codex/SDformer/mlruns_local/791161773545750616/0b69b94caea44bba81dfd7f4914df8ca/artifacts
end_time: 1783266388150
entry_point_name: ''
experiment_id: '791161773545750616'
lifecycle_stage: active
run_id: 0b69b94caea44bba81dfd7f4914df8ca
run_name: overjoyed-slug-911
source_name: ''
source_type: 4
source_version: ''
start_time: 1782980401396
status: 3
tags: []
user_id: root
