`timescale 1ns/1ps
`default_nettype none

bind gatestack_dctf96_term_datapath_top
    gatestack_dctf96_term_datapath_top_assertions #(
        .Q(Q),
        .OUT_TILE(OUT_TILE),
        .PRODUCT_W(PRODUCT_W),
        .GROUP_TAG_W(GROUP_TAG_W),
        .ISSUE_SEQ_W(ISSUE_SEQ_W),
        .INPUT_CH_W(INPUT_CH_W),
        .TOKEN_ID_W(TOKEN_ID_W),
        .OUTPUT_TILE_W(OUTPUT_TILE_W),
        .EPOCH_W(EPOCH_W),
        .COUNTER_W(COUNTER_W)
    ) i_gatestack_dctf96_term_datapath_top_assertions (
        .clk_core(clk_core),
        .rst_core(rst_core),
        .flush(flush),
        .clear_error(clear_error),
        .term_valid(term_valid),
        .term_ready(term_ready),
        .adapter_term_ready(adapter_term_ready),
        .adapter_idle(adapter_idle),
        .event_ready(event_ready),
        .term_metadata_legal(term_metadata_legal),
        .adapter_term_valid(adapter_term_valid),
        .adapter_event_valid(adapter_event_valid),
        .legal_term_fire(legal_term_fire),
        .illegal_term_fire(illegal_term_fire),
        .illegal_event_fire(illegal_event_fire),
        .illegal_drop_active_q(illegal_drop_active_q),
        .term_destination_count(term_destination_count),
        .event_term_last(event_term_last),
        .issue_term_fire(issue_term_fire),
        .weight_req_valid(weight_req_valid),
        .weight_req_ready(weight_req_ready),
        .weight_req_tags(weight_req_tags),
        .weight_req_input_channels(weight_req_input_channels),
        .weight_req_output_tiles(weight_req_output_tiles),
        .weight_req_epochs(weight_req_epochs),
        .weight_rsp_ready(weight_rsp_ready),
        .acc_update_valid(acc_update_valid),
        .acc_update_ready(acc_update_ready),
        .acc_update_token_ids(acc_update_token_ids),
        .acc_update_tags(acc_update_tags),
        .acc_update_values(acc_update_values),
        .bank_term_done(bank_term_done),
        .bank_term_done_match(bank_done_match),
        .head_compute_done(head_compute_done),
        .head_compute_done_group_tag(head_compute_done_group_tag),
        .head_compute_done_issue_seq(head_compute_done_issue_seq),
        .dispatch_retire_valid(dispatch_retire_valid),
        .track_pop(track_pop),
        .tracked_head_last(track_head_last_q[track_head_q]),
        .head_done_mask_after(head_done_mask_after),
        .tracked_head_tag(track_tag_q[track_head_q]),
        .tracked_head_issue_seq(track_issue_seq_q[track_head_q]),
        .track_valid_q(track_valid_q),
        .track_count_q(track_count_q),
        .fabric_occupancy(fabric_occupancy),
        .issued_terms(issued_terms),
        .completed_terms(completed_terms),
        .datapath_idle(datapath_idle),
        .protocol_error(protocol_error)
    );

`default_nettype wire
