###################################################################

# Created by write_sdc on Tue Sep 15 22:10:19 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions ssg0p9v125c -library tcbn28hpcplusbwp35p140ssg0p9v125c
set_wire_load_model -name ZeroWireload -library                                \
tcbn28hpcplusbwp35p140ssg0p9v125c
set_max_fanout 32 [current_design]
set_load -pin_load 0.01 [get_ports gate_out]
set_load -pin_load 0.01 [get_ports locked_out]
set_load -pin_load 0.01 [get_ports lower_hit_out]
set_load -pin_load 0.01 [get_ports upper_hit_out]
create_clock [get_ports clk_core]  -name core_clk  -period 3  -waveform {0 1.5}
set_clock_uncertainty -setup 0.2  [get_clocks core_clk]
set_clock_uncertainty -hold 0.05  [get_clocks core_clk]
set_input_delay -clock core_clk  0.25  [get_ports rst_core]
set_input_delay -clock core_clk  0.25  [get_ports cfg_we]
set_input_delay -clock core_clk  0.25  [get_ports cfg_half]
set_input_delay -clock core_clk  0.25  [get_ports {cfg_addr[4]}]
set_input_delay -clock core_clk  0.25  [get_ports {cfg_addr[3]}]
set_input_delay -clock core_clk  0.25  [get_ports {cfg_addr[2]}]
set_input_delay -clock core_clk  0.25  [get_ports {cfg_addr[1]}]
set_input_delay -clock core_clk  0.25  [get_ports {cfg_addr[0]}]
set_input_delay -clock core_clk  0.25  [get_ports {cfg_data[15]}]
set_input_delay -clock core_clk  0.25  [get_ports {cfg_data[14]}]
set_input_delay -clock core_clk  0.25  [get_ports {cfg_data[13]}]
set_input_delay -clock core_clk  0.25  [get_ports {cfg_data[12]}]
set_input_delay -clock core_clk  0.25  [get_ports {cfg_data[11]}]
set_input_delay -clock core_clk  0.25  [get_ports {cfg_data[10]}]
set_input_delay -clock core_clk  0.25  [get_ports {cfg_data[9]}]
set_input_delay -clock core_clk  0.25  [get_ports {cfg_data[8]}]
set_input_delay -clock core_clk  0.25  [get_ports {cfg_data[7]}]
set_input_delay -clock core_clk  0.25  [get_ports {cfg_data[6]}]
set_input_delay -clock core_clk  0.25  [get_ports {cfg_data[5]}]
set_input_delay -clock core_clk  0.25  [get_ports {cfg_data[4]}]
set_input_delay -clock core_clk  0.25  [get_ports {cfg_data[3]}]
set_input_delay -clock core_clk  0.25  [get_ports {cfg_data[2]}]
set_input_delay -clock core_clk  0.25  [get_ports {cfg_data[1]}]
set_input_delay -clock core_clk  0.25  [get_ports {cfg_data[0]}]
set_input_delay -clock core_clk  0.25  [get_ports context_we]
set_input_delay -clock core_clk  0.25  [get_ports codes_we]
set_input_delay -clock core_clk  0.25  [get_ports group_go]
set_input_delay -clock core_clk  0.25  [get_ports step_go]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[47]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[46]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[45]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[44]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[43]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[42]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[41]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[40]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[39]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[38]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[37]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[36]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[35]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[34]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[33]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[32]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[31]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[30]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[29]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[28]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[27]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[26]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[25]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[24]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[23]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[22]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[21]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[20]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[19]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[18]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[17]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[16]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[15]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[14]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[13]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[12]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[11]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[10]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[9]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[8]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[7]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[6]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[5]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[4]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[3]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[2]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[1]}]
set_input_delay -clock core_clk  0.25  [get_ports {prefix_in[0]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[47]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[46]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[45]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[44]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[43]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[42]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[41]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[40]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[39]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[38]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[37]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[36]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[35]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[34]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[33]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[32]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[31]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[30]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[29]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[28]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[27]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[26]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[25]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[24]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[23]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[22]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[21]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[20]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[19]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[18]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[17]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[16]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[15]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[14]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[13]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[12]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[11]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[10]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[9]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[8]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[7]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[6]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[5]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[4]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[3]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[2]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[1]}]
set_input_delay -clock core_clk  0.25  [get_ports {tau_in[0]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[47]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[46]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[45]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[44]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[43]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[42]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[41]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[40]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[39]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[38]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[37]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[36]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[35]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[34]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[33]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[32]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[31]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[30]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[29]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[28]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[27]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[26]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[25]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[24]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[23]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[22]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[21]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[20]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[19]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[18]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[17]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[16]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[15]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[14]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[13]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[12]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[11]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[10]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[9]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[8]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[7]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[6]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[5]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[4]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[3]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[2]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[1]}]
set_input_delay -clock core_clk  0.25  [get_ports {p_in[0]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[47]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[46]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[45]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[44]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[43]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[42]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[41]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[40]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[39]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[38]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[37]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[36]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[35]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[34]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[33]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[32]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[31]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[30]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[29]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[28]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[27]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[26]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[25]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[24]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[23]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[22]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[21]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[20]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[19]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[18]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[17]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[16]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[15]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[14]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[13]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[12]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[11]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[10]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[9]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[8]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[7]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[6]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[5]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[4]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[3]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[2]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[1]}]
set_input_delay -clock core_clk  0.25  [get_ports {n_in[0]}]
set_input_delay -clock core_clk  0.25  [get_ports {lo_code_in[4]}]
set_input_delay -clock core_clk  0.25  [get_ports {lo_code_in[3]}]
set_input_delay -clock core_clk  0.25  [get_ports {lo_code_in[2]}]
set_input_delay -clock core_clk  0.25  [get_ports {lo_code_in[1]}]
set_input_delay -clock core_clk  0.25  [get_ports {lo_code_in[0]}]
set_input_delay -clock core_clk  0.25  [get_ports {hi_code_in[4]}]
set_input_delay -clock core_clk  0.25  [get_ports {hi_code_in[3]}]
set_input_delay -clock core_clk  0.25  [get_ports {hi_code_in[2]}]
set_input_delay -clock core_clk  0.25  [get_ports {hi_code_in[1]}]
set_input_delay -clock core_clk  0.25  [get_ports {hi_code_in[0]}]
set_input_delay -clock core_clk  0.25  [get_ports {m_in[4]}]
set_input_delay -clock core_clk  0.25  [get_ports {m_in[3]}]
set_input_delay -clock core_clk  0.25  [get_ports {m_in[2]}]
set_input_delay -clock core_clk  0.25  [get_ports {m_in[1]}]
set_input_delay -clock core_clk  0.25  [get_ports {m_in[0]}]
set_input_delay -clock core_clk  0.25  [get_ports positive_in]
set_input_delay -clock core_clk  0.25  [get_ports constant_in]
set_input_delay -clock core_clk  0.25  [get_ports constant_gate_in]
set_output_delay -clock core_clk  0.25  [get_ports gate_out]
set_output_delay -clock core_clk  0.25  [get_ports locked_out]
set_output_delay -clock core_clk  0.25  [get_ports lower_hit_out]
set_output_delay -clock core_clk  0.25  [get_ports upper_hit_out]
set_input_transition -max 0.1  [get_ports rst_core]
set_input_transition -min 0.1  [get_ports rst_core]
set_input_transition -max 0.1  [get_ports cfg_we]
set_input_transition -min 0.1  [get_ports cfg_we]
set_input_transition -max 0.1  [get_ports cfg_half]
set_input_transition -min 0.1  [get_ports cfg_half]
set_input_transition -max 0.1  [get_ports {cfg_addr[4]}]
set_input_transition -min 0.1  [get_ports {cfg_addr[4]}]
set_input_transition -max 0.1  [get_ports {cfg_addr[3]}]
set_input_transition -min 0.1  [get_ports {cfg_addr[3]}]
set_input_transition -max 0.1  [get_ports {cfg_addr[2]}]
set_input_transition -min 0.1  [get_ports {cfg_addr[2]}]
set_input_transition -max 0.1  [get_ports {cfg_addr[1]}]
set_input_transition -min 0.1  [get_ports {cfg_addr[1]}]
set_input_transition -max 0.1  [get_ports {cfg_addr[0]}]
set_input_transition -min 0.1  [get_ports {cfg_addr[0]}]
set_input_transition -max 0.1  [get_ports {cfg_data[15]}]
set_input_transition -min 0.1  [get_ports {cfg_data[15]}]
set_input_transition -max 0.1  [get_ports {cfg_data[14]}]
set_input_transition -min 0.1  [get_ports {cfg_data[14]}]
set_input_transition -max 0.1  [get_ports {cfg_data[13]}]
set_input_transition -min 0.1  [get_ports {cfg_data[13]}]
set_input_transition -max 0.1  [get_ports {cfg_data[12]}]
set_input_transition -min 0.1  [get_ports {cfg_data[12]}]
set_input_transition -max 0.1  [get_ports {cfg_data[11]}]
set_input_transition -min 0.1  [get_ports {cfg_data[11]}]
set_input_transition -max 0.1  [get_ports {cfg_data[10]}]
set_input_transition -min 0.1  [get_ports {cfg_data[10]}]
set_input_transition -max 0.1  [get_ports {cfg_data[9]}]
set_input_transition -min 0.1  [get_ports {cfg_data[9]}]
set_input_transition -max 0.1  [get_ports {cfg_data[8]}]
set_input_transition -min 0.1  [get_ports {cfg_data[8]}]
set_input_transition -max 0.1  [get_ports {cfg_data[7]}]
set_input_transition -min 0.1  [get_ports {cfg_data[7]}]
set_input_transition -max 0.1  [get_ports {cfg_data[6]}]
set_input_transition -min 0.1  [get_ports {cfg_data[6]}]
set_input_transition -max 0.1  [get_ports {cfg_data[5]}]
set_input_transition -min 0.1  [get_ports {cfg_data[5]}]
set_input_transition -max 0.1  [get_ports {cfg_data[4]}]
set_input_transition -min 0.1  [get_ports {cfg_data[4]}]
set_input_transition -max 0.1  [get_ports {cfg_data[3]}]
set_input_transition -min 0.1  [get_ports {cfg_data[3]}]
set_input_transition -max 0.1  [get_ports {cfg_data[2]}]
set_input_transition -min 0.1  [get_ports {cfg_data[2]}]
set_input_transition -max 0.1  [get_ports {cfg_data[1]}]
set_input_transition -min 0.1  [get_ports {cfg_data[1]}]
set_input_transition -max 0.1  [get_ports {cfg_data[0]}]
set_input_transition -min 0.1  [get_ports {cfg_data[0]}]
set_input_transition -max 0.1  [get_ports context_we]
set_input_transition -min 0.1  [get_ports context_we]
set_input_transition -max 0.1  [get_ports codes_we]
set_input_transition -min 0.1  [get_ports codes_we]
set_input_transition -max 0.1  [get_ports group_go]
set_input_transition -min 0.1  [get_ports group_go]
set_input_transition -max 0.1  [get_ports step_go]
set_input_transition -min 0.1  [get_ports step_go]
set_input_transition -max 0.1  [get_ports {prefix_in[47]}]
set_input_transition -min 0.1  [get_ports {prefix_in[47]}]
set_input_transition -max 0.1  [get_ports {prefix_in[46]}]
set_input_transition -min 0.1  [get_ports {prefix_in[46]}]
set_input_transition -max 0.1  [get_ports {prefix_in[45]}]
set_input_transition -min 0.1  [get_ports {prefix_in[45]}]
set_input_transition -max 0.1  [get_ports {prefix_in[44]}]
set_input_transition -min 0.1  [get_ports {prefix_in[44]}]
set_input_transition -max 0.1  [get_ports {prefix_in[43]}]
set_input_transition -min 0.1  [get_ports {prefix_in[43]}]
set_input_transition -max 0.1  [get_ports {prefix_in[42]}]
set_input_transition -min 0.1  [get_ports {prefix_in[42]}]
set_input_transition -max 0.1  [get_ports {prefix_in[41]}]
set_input_transition -min 0.1  [get_ports {prefix_in[41]}]
set_input_transition -max 0.1  [get_ports {prefix_in[40]}]
set_input_transition -min 0.1  [get_ports {prefix_in[40]}]
set_input_transition -max 0.1  [get_ports {prefix_in[39]}]
set_input_transition -min 0.1  [get_ports {prefix_in[39]}]
set_input_transition -max 0.1  [get_ports {prefix_in[38]}]
set_input_transition -min 0.1  [get_ports {prefix_in[38]}]
set_input_transition -max 0.1  [get_ports {prefix_in[37]}]
set_input_transition -min 0.1  [get_ports {prefix_in[37]}]
set_input_transition -max 0.1  [get_ports {prefix_in[36]}]
set_input_transition -min 0.1  [get_ports {prefix_in[36]}]
set_input_transition -max 0.1  [get_ports {prefix_in[35]}]
set_input_transition -min 0.1  [get_ports {prefix_in[35]}]
set_input_transition -max 0.1  [get_ports {prefix_in[34]}]
set_input_transition -min 0.1  [get_ports {prefix_in[34]}]
set_input_transition -max 0.1  [get_ports {prefix_in[33]}]
set_input_transition -min 0.1  [get_ports {prefix_in[33]}]
set_input_transition -max 0.1  [get_ports {prefix_in[32]}]
set_input_transition -min 0.1  [get_ports {prefix_in[32]}]
set_input_transition -max 0.1  [get_ports {prefix_in[31]}]
set_input_transition -min 0.1  [get_ports {prefix_in[31]}]
set_input_transition -max 0.1  [get_ports {prefix_in[30]}]
set_input_transition -min 0.1  [get_ports {prefix_in[30]}]
set_input_transition -max 0.1  [get_ports {prefix_in[29]}]
set_input_transition -min 0.1  [get_ports {prefix_in[29]}]
set_input_transition -max 0.1  [get_ports {prefix_in[28]}]
set_input_transition -min 0.1  [get_ports {prefix_in[28]}]
set_input_transition -max 0.1  [get_ports {prefix_in[27]}]
set_input_transition -min 0.1  [get_ports {prefix_in[27]}]
set_input_transition -max 0.1  [get_ports {prefix_in[26]}]
set_input_transition -min 0.1  [get_ports {prefix_in[26]}]
set_input_transition -max 0.1  [get_ports {prefix_in[25]}]
set_input_transition -min 0.1  [get_ports {prefix_in[25]}]
set_input_transition -max 0.1  [get_ports {prefix_in[24]}]
set_input_transition -min 0.1  [get_ports {prefix_in[24]}]
set_input_transition -max 0.1  [get_ports {prefix_in[23]}]
set_input_transition -min 0.1  [get_ports {prefix_in[23]}]
set_input_transition -max 0.1  [get_ports {prefix_in[22]}]
set_input_transition -min 0.1  [get_ports {prefix_in[22]}]
set_input_transition -max 0.1  [get_ports {prefix_in[21]}]
set_input_transition -min 0.1  [get_ports {prefix_in[21]}]
set_input_transition -max 0.1  [get_ports {prefix_in[20]}]
set_input_transition -min 0.1  [get_ports {prefix_in[20]}]
set_input_transition -max 0.1  [get_ports {prefix_in[19]}]
set_input_transition -min 0.1  [get_ports {prefix_in[19]}]
set_input_transition -max 0.1  [get_ports {prefix_in[18]}]
set_input_transition -min 0.1  [get_ports {prefix_in[18]}]
set_input_transition -max 0.1  [get_ports {prefix_in[17]}]
set_input_transition -min 0.1  [get_ports {prefix_in[17]}]
set_input_transition -max 0.1  [get_ports {prefix_in[16]}]
set_input_transition -min 0.1  [get_ports {prefix_in[16]}]
set_input_transition -max 0.1  [get_ports {prefix_in[15]}]
set_input_transition -min 0.1  [get_ports {prefix_in[15]}]
set_input_transition -max 0.1  [get_ports {prefix_in[14]}]
set_input_transition -min 0.1  [get_ports {prefix_in[14]}]
set_input_transition -max 0.1  [get_ports {prefix_in[13]}]
set_input_transition -min 0.1  [get_ports {prefix_in[13]}]
set_input_transition -max 0.1  [get_ports {prefix_in[12]}]
set_input_transition -min 0.1  [get_ports {prefix_in[12]}]
set_input_transition -max 0.1  [get_ports {prefix_in[11]}]
set_input_transition -min 0.1  [get_ports {prefix_in[11]}]
set_input_transition -max 0.1  [get_ports {prefix_in[10]}]
set_input_transition -min 0.1  [get_ports {prefix_in[10]}]
set_input_transition -max 0.1  [get_ports {prefix_in[9]}]
set_input_transition -min 0.1  [get_ports {prefix_in[9]}]
set_input_transition -max 0.1  [get_ports {prefix_in[8]}]
set_input_transition -min 0.1  [get_ports {prefix_in[8]}]
set_input_transition -max 0.1  [get_ports {prefix_in[7]}]
set_input_transition -min 0.1  [get_ports {prefix_in[7]}]
set_input_transition -max 0.1  [get_ports {prefix_in[6]}]
set_input_transition -min 0.1  [get_ports {prefix_in[6]}]
set_input_transition -max 0.1  [get_ports {prefix_in[5]}]
set_input_transition -min 0.1  [get_ports {prefix_in[5]}]
set_input_transition -max 0.1  [get_ports {prefix_in[4]}]
set_input_transition -min 0.1  [get_ports {prefix_in[4]}]
set_input_transition -max 0.1  [get_ports {prefix_in[3]}]
set_input_transition -min 0.1  [get_ports {prefix_in[3]}]
set_input_transition -max 0.1  [get_ports {prefix_in[2]}]
set_input_transition -min 0.1  [get_ports {prefix_in[2]}]
set_input_transition -max 0.1  [get_ports {prefix_in[1]}]
set_input_transition -min 0.1  [get_ports {prefix_in[1]}]
set_input_transition -max 0.1  [get_ports {prefix_in[0]}]
set_input_transition -min 0.1  [get_ports {prefix_in[0]}]
set_input_transition -max 0.1  [get_ports {tau_in[47]}]
set_input_transition -min 0.1  [get_ports {tau_in[47]}]
set_input_transition -max 0.1  [get_ports {tau_in[46]}]
set_input_transition -min 0.1  [get_ports {tau_in[46]}]
set_input_transition -max 0.1  [get_ports {tau_in[45]}]
set_input_transition -min 0.1  [get_ports {tau_in[45]}]
set_input_transition -max 0.1  [get_ports {tau_in[44]}]
set_input_transition -min 0.1  [get_ports {tau_in[44]}]
set_input_transition -max 0.1  [get_ports {tau_in[43]}]
set_input_transition -min 0.1  [get_ports {tau_in[43]}]
set_input_transition -max 0.1  [get_ports {tau_in[42]}]
set_input_transition -min 0.1  [get_ports {tau_in[42]}]
set_input_transition -max 0.1  [get_ports {tau_in[41]}]
set_input_transition -min 0.1  [get_ports {tau_in[41]}]
set_input_transition -max 0.1  [get_ports {tau_in[40]}]
set_input_transition -min 0.1  [get_ports {tau_in[40]}]
set_input_transition -max 0.1  [get_ports {tau_in[39]}]
set_input_transition -min 0.1  [get_ports {tau_in[39]}]
set_input_transition -max 0.1  [get_ports {tau_in[38]}]
set_input_transition -min 0.1  [get_ports {tau_in[38]}]
set_input_transition -max 0.1  [get_ports {tau_in[37]}]
set_input_transition -min 0.1  [get_ports {tau_in[37]}]
set_input_transition -max 0.1  [get_ports {tau_in[36]}]
set_input_transition -min 0.1  [get_ports {tau_in[36]}]
set_input_transition -max 0.1  [get_ports {tau_in[35]}]
set_input_transition -min 0.1  [get_ports {tau_in[35]}]
set_input_transition -max 0.1  [get_ports {tau_in[34]}]
set_input_transition -min 0.1  [get_ports {tau_in[34]}]
set_input_transition -max 0.1  [get_ports {tau_in[33]}]
set_input_transition -min 0.1  [get_ports {tau_in[33]}]
set_input_transition -max 0.1  [get_ports {tau_in[32]}]
set_input_transition -min 0.1  [get_ports {tau_in[32]}]
set_input_transition -max 0.1  [get_ports {tau_in[31]}]
set_input_transition -min 0.1  [get_ports {tau_in[31]}]
set_input_transition -max 0.1  [get_ports {tau_in[30]}]
set_input_transition -min 0.1  [get_ports {tau_in[30]}]
set_input_transition -max 0.1  [get_ports {tau_in[29]}]
set_input_transition -min 0.1  [get_ports {tau_in[29]}]
set_input_transition -max 0.1  [get_ports {tau_in[28]}]
set_input_transition -min 0.1  [get_ports {tau_in[28]}]
set_input_transition -max 0.1  [get_ports {tau_in[27]}]
set_input_transition -min 0.1  [get_ports {tau_in[27]}]
set_input_transition -max 0.1  [get_ports {tau_in[26]}]
set_input_transition -min 0.1  [get_ports {tau_in[26]}]
set_input_transition -max 0.1  [get_ports {tau_in[25]}]
set_input_transition -min 0.1  [get_ports {tau_in[25]}]
set_input_transition -max 0.1  [get_ports {tau_in[24]}]
set_input_transition -min 0.1  [get_ports {tau_in[24]}]
set_input_transition -max 0.1  [get_ports {tau_in[23]}]
set_input_transition -min 0.1  [get_ports {tau_in[23]}]
set_input_transition -max 0.1  [get_ports {tau_in[22]}]
set_input_transition -min 0.1  [get_ports {tau_in[22]}]
set_input_transition -max 0.1  [get_ports {tau_in[21]}]
set_input_transition -min 0.1  [get_ports {tau_in[21]}]
set_input_transition -max 0.1  [get_ports {tau_in[20]}]
set_input_transition -min 0.1  [get_ports {tau_in[20]}]
set_input_transition -max 0.1  [get_ports {tau_in[19]}]
set_input_transition -min 0.1  [get_ports {tau_in[19]}]
set_input_transition -max 0.1  [get_ports {tau_in[18]}]
set_input_transition -min 0.1  [get_ports {tau_in[18]}]
set_input_transition -max 0.1  [get_ports {tau_in[17]}]
set_input_transition -min 0.1  [get_ports {tau_in[17]}]
set_input_transition -max 0.1  [get_ports {tau_in[16]}]
set_input_transition -min 0.1  [get_ports {tau_in[16]}]
set_input_transition -max 0.1  [get_ports {tau_in[15]}]
set_input_transition -min 0.1  [get_ports {tau_in[15]}]
set_input_transition -max 0.1  [get_ports {tau_in[14]}]
set_input_transition -min 0.1  [get_ports {tau_in[14]}]
set_input_transition -max 0.1  [get_ports {tau_in[13]}]
set_input_transition -min 0.1  [get_ports {tau_in[13]}]
set_input_transition -max 0.1  [get_ports {tau_in[12]}]
set_input_transition -min 0.1  [get_ports {tau_in[12]}]
set_input_transition -max 0.1  [get_ports {tau_in[11]}]
set_input_transition -min 0.1  [get_ports {tau_in[11]}]
set_input_transition -max 0.1  [get_ports {tau_in[10]}]
set_input_transition -min 0.1  [get_ports {tau_in[10]}]
set_input_transition -max 0.1  [get_ports {tau_in[9]}]
set_input_transition -min 0.1  [get_ports {tau_in[9]}]
set_input_transition -max 0.1  [get_ports {tau_in[8]}]
set_input_transition -min 0.1  [get_ports {tau_in[8]}]
set_input_transition -max 0.1  [get_ports {tau_in[7]}]
set_input_transition -min 0.1  [get_ports {tau_in[7]}]
set_input_transition -max 0.1  [get_ports {tau_in[6]}]
set_input_transition -min 0.1  [get_ports {tau_in[6]}]
set_input_transition -max 0.1  [get_ports {tau_in[5]}]
set_input_transition -min 0.1  [get_ports {tau_in[5]}]
set_input_transition -max 0.1  [get_ports {tau_in[4]}]
set_input_transition -min 0.1  [get_ports {tau_in[4]}]
set_input_transition -max 0.1  [get_ports {tau_in[3]}]
set_input_transition -min 0.1  [get_ports {tau_in[3]}]
set_input_transition -max 0.1  [get_ports {tau_in[2]}]
set_input_transition -min 0.1  [get_ports {tau_in[2]}]
set_input_transition -max 0.1  [get_ports {tau_in[1]}]
set_input_transition -min 0.1  [get_ports {tau_in[1]}]
set_input_transition -max 0.1  [get_ports {tau_in[0]}]
set_input_transition -min 0.1  [get_ports {tau_in[0]}]
set_input_transition -max 0.1  [get_ports {p_in[47]}]
set_input_transition -min 0.1  [get_ports {p_in[47]}]
set_input_transition -max 0.1  [get_ports {p_in[46]}]
set_input_transition -min 0.1  [get_ports {p_in[46]}]
set_input_transition -max 0.1  [get_ports {p_in[45]}]
set_input_transition -min 0.1  [get_ports {p_in[45]}]
set_input_transition -max 0.1  [get_ports {p_in[44]}]
set_input_transition -min 0.1  [get_ports {p_in[44]}]
set_input_transition -max 0.1  [get_ports {p_in[43]}]
set_input_transition -min 0.1  [get_ports {p_in[43]}]
set_input_transition -max 0.1  [get_ports {p_in[42]}]
set_input_transition -min 0.1  [get_ports {p_in[42]}]
set_input_transition -max 0.1  [get_ports {p_in[41]}]
set_input_transition -min 0.1  [get_ports {p_in[41]}]
set_input_transition -max 0.1  [get_ports {p_in[40]}]
set_input_transition -min 0.1  [get_ports {p_in[40]}]
set_input_transition -max 0.1  [get_ports {p_in[39]}]
set_input_transition -min 0.1  [get_ports {p_in[39]}]
set_input_transition -max 0.1  [get_ports {p_in[38]}]
set_input_transition -min 0.1  [get_ports {p_in[38]}]
set_input_transition -max 0.1  [get_ports {p_in[37]}]
set_input_transition -min 0.1  [get_ports {p_in[37]}]
set_input_transition -max 0.1  [get_ports {p_in[36]}]
set_input_transition -min 0.1  [get_ports {p_in[36]}]
set_input_transition -max 0.1  [get_ports {p_in[35]}]
set_input_transition -min 0.1  [get_ports {p_in[35]}]
set_input_transition -max 0.1  [get_ports {p_in[34]}]
set_input_transition -min 0.1  [get_ports {p_in[34]}]
set_input_transition -max 0.1  [get_ports {p_in[33]}]
set_input_transition -min 0.1  [get_ports {p_in[33]}]
set_input_transition -max 0.1  [get_ports {p_in[32]}]
set_input_transition -min 0.1  [get_ports {p_in[32]}]
set_input_transition -max 0.1  [get_ports {p_in[31]}]
set_input_transition -min 0.1  [get_ports {p_in[31]}]
set_input_transition -max 0.1  [get_ports {p_in[30]}]
set_input_transition -min 0.1  [get_ports {p_in[30]}]
set_input_transition -max 0.1  [get_ports {p_in[29]}]
set_input_transition -min 0.1  [get_ports {p_in[29]}]
set_input_transition -max 0.1  [get_ports {p_in[28]}]
set_input_transition -min 0.1  [get_ports {p_in[28]}]
set_input_transition -max 0.1  [get_ports {p_in[27]}]
set_input_transition -min 0.1  [get_ports {p_in[27]}]
set_input_transition -max 0.1  [get_ports {p_in[26]}]
set_input_transition -min 0.1  [get_ports {p_in[26]}]
set_input_transition -max 0.1  [get_ports {p_in[25]}]
set_input_transition -min 0.1  [get_ports {p_in[25]}]
set_input_transition -max 0.1  [get_ports {p_in[24]}]
set_input_transition -min 0.1  [get_ports {p_in[24]}]
set_input_transition -max 0.1  [get_ports {p_in[23]}]
set_input_transition -min 0.1  [get_ports {p_in[23]}]
set_input_transition -max 0.1  [get_ports {p_in[22]}]
set_input_transition -min 0.1  [get_ports {p_in[22]}]
set_input_transition -max 0.1  [get_ports {p_in[21]}]
set_input_transition -min 0.1  [get_ports {p_in[21]}]
set_input_transition -max 0.1  [get_ports {p_in[20]}]
set_input_transition -min 0.1  [get_ports {p_in[20]}]
set_input_transition -max 0.1  [get_ports {p_in[19]}]
set_input_transition -min 0.1  [get_ports {p_in[19]}]
set_input_transition -max 0.1  [get_ports {p_in[18]}]
set_input_transition -min 0.1  [get_ports {p_in[18]}]
set_input_transition -max 0.1  [get_ports {p_in[17]}]
set_input_transition -min 0.1  [get_ports {p_in[17]}]
set_input_transition -max 0.1  [get_ports {p_in[16]}]
set_input_transition -min 0.1  [get_ports {p_in[16]}]
set_input_transition -max 0.1  [get_ports {p_in[15]}]
set_input_transition -min 0.1  [get_ports {p_in[15]}]
set_input_transition -max 0.1  [get_ports {p_in[14]}]
set_input_transition -min 0.1  [get_ports {p_in[14]}]
set_input_transition -max 0.1  [get_ports {p_in[13]}]
set_input_transition -min 0.1  [get_ports {p_in[13]}]
set_input_transition -max 0.1  [get_ports {p_in[12]}]
set_input_transition -min 0.1  [get_ports {p_in[12]}]
set_input_transition -max 0.1  [get_ports {p_in[11]}]
set_input_transition -min 0.1  [get_ports {p_in[11]}]
set_input_transition -max 0.1  [get_ports {p_in[10]}]
set_input_transition -min 0.1  [get_ports {p_in[10]}]
set_input_transition -max 0.1  [get_ports {p_in[9]}]
set_input_transition -min 0.1  [get_ports {p_in[9]}]
set_input_transition -max 0.1  [get_ports {p_in[8]}]
set_input_transition -min 0.1  [get_ports {p_in[8]}]
set_input_transition -max 0.1  [get_ports {p_in[7]}]
set_input_transition -min 0.1  [get_ports {p_in[7]}]
set_input_transition -max 0.1  [get_ports {p_in[6]}]
set_input_transition -min 0.1  [get_ports {p_in[6]}]
set_input_transition -max 0.1  [get_ports {p_in[5]}]
set_input_transition -min 0.1  [get_ports {p_in[5]}]
set_input_transition -max 0.1  [get_ports {p_in[4]}]
set_input_transition -min 0.1  [get_ports {p_in[4]}]
set_input_transition -max 0.1  [get_ports {p_in[3]}]
set_input_transition -min 0.1  [get_ports {p_in[3]}]
set_input_transition -max 0.1  [get_ports {p_in[2]}]
set_input_transition -min 0.1  [get_ports {p_in[2]}]
set_input_transition -max 0.1  [get_ports {p_in[1]}]
set_input_transition -min 0.1  [get_ports {p_in[1]}]
set_input_transition -max 0.1  [get_ports {p_in[0]}]
set_input_transition -min 0.1  [get_ports {p_in[0]}]
set_input_transition -max 0.1  [get_ports {n_in[47]}]
set_input_transition -min 0.1  [get_ports {n_in[47]}]
set_input_transition -max 0.1  [get_ports {n_in[46]}]
set_input_transition -min 0.1  [get_ports {n_in[46]}]
set_input_transition -max 0.1  [get_ports {n_in[45]}]
set_input_transition -min 0.1  [get_ports {n_in[45]}]
set_input_transition -max 0.1  [get_ports {n_in[44]}]
set_input_transition -min 0.1  [get_ports {n_in[44]}]
set_input_transition -max 0.1  [get_ports {n_in[43]}]
set_input_transition -min 0.1  [get_ports {n_in[43]}]
set_input_transition -max 0.1  [get_ports {n_in[42]}]
set_input_transition -min 0.1  [get_ports {n_in[42]}]
set_input_transition -max 0.1  [get_ports {n_in[41]}]
set_input_transition -min 0.1  [get_ports {n_in[41]}]
set_input_transition -max 0.1  [get_ports {n_in[40]}]
set_input_transition -min 0.1  [get_ports {n_in[40]}]
set_input_transition -max 0.1  [get_ports {n_in[39]}]
set_input_transition -min 0.1  [get_ports {n_in[39]}]
set_input_transition -max 0.1  [get_ports {n_in[38]}]
set_input_transition -min 0.1  [get_ports {n_in[38]}]
set_input_transition -max 0.1  [get_ports {n_in[37]}]
set_input_transition -min 0.1  [get_ports {n_in[37]}]
set_input_transition -max 0.1  [get_ports {n_in[36]}]
set_input_transition -min 0.1  [get_ports {n_in[36]}]
set_input_transition -max 0.1  [get_ports {n_in[35]}]
set_input_transition -min 0.1  [get_ports {n_in[35]}]
set_input_transition -max 0.1  [get_ports {n_in[34]}]
set_input_transition -min 0.1  [get_ports {n_in[34]}]
set_input_transition -max 0.1  [get_ports {n_in[33]}]
set_input_transition -min 0.1  [get_ports {n_in[33]}]
set_input_transition -max 0.1  [get_ports {n_in[32]}]
set_input_transition -min 0.1  [get_ports {n_in[32]}]
set_input_transition -max 0.1  [get_ports {n_in[31]}]
set_input_transition -min 0.1  [get_ports {n_in[31]}]
set_input_transition -max 0.1  [get_ports {n_in[30]}]
set_input_transition -min 0.1  [get_ports {n_in[30]}]
set_input_transition -max 0.1  [get_ports {n_in[29]}]
set_input_transition -min 0.1  [get_ports {n_in[29]}]
set_input_transition -max 0.1  [get_ports {n_in[28]}]
set_input_transition -min 0.1  [get_ports {n_in[28]}]
set_input_transition -max 0.1  [get_ports {n_in[27]}]
set_input_transition -min 0.1  [get_ports {n_in[27]}]
set_input_transition -max 0.1  [get_ports {n_in[26]}]
set_input_transition -min 0.1  [get_ports {n_in[26]}]
set_input_transition -max 0.1  [get_ports {n_in[25]}]
set_input_transition -min 0.1  [get_ports {n_in[25]}]
set_input_transition -max 0.1  [get_ports {n_in[24]}]
set_input_transition -min 0.1  [get_ports {n_in[24]}]
set_input_transition -max 0.1  [get_ports {n_in[23]}]
set_input_transition -min 0.1  [get_ports {n_in[23]}]
set_input_transition -max 0.1  [get_ports {n_in[22]}]
set_input_transition -min 0.1  [get_ports {n_in[22]}]
set_input_transition -max 0.1  [get_ports {n_in[21]}]
set_input_transition -min 0.1  [get_ports {n_in[21]}]
set_input_transition -max 0.1  [get_ports {n_in[20]}]
set_input_transition -min 0.1  [get_ports {n_in[20]}]
set_input_transition -max 0.1  [get_ports {n_in[19]}]
set_input_transition -min 0.1  [get_ports {n_in[19]}]
set_input_transition -max 0.1  [get_ports {n_in[18]}]
set_input_transition -min 0.1  [get_ports {n_in[18]}]
set_input_transition -max 0.1  [get_ports {n_in[17]}]
set_input_transition -min 0.1  [get_ports {n_in[17]}]
set_input_transition -max 0.1  [get_ports {n_in[16]}]
set_input_transition -min 0.1  [get_ports {n_in[16]}]
set_input_transition -max 0.1  [get_ports {n_in[15]}]
set_input_transition -min 0.1  [get_ports {n_in[15]}]
set_input_transition -max 0.1  [get_ports {n_in[14]}]
set_input_transition -min 0.1  [get_ports {n_in[14]}]
set_input_transition -max 0.1  [get_ports {n_in[13]}]
set_input_transition -min 0.1  [get_ports {n_in[13]}]
set_input_transition -max 0.1  [get_ports {n_in[12]}]
set_input_transition -min 0.1  [get_ports {n_in[12]}]
set_input_transition -max 0.1  [get_ports {n_in[11]}]
set_input_transition -min 0.1  [get_ports {n_in[11]}]
set_input_transition -max 0.1  [get_ports {n_in[10]}]
set_input_transition -min 0.1  [get_ports {n_in[10]}]
set_input_transition -max 0.1  [get_ports {n_in[9]}]
set_input_transition -min 0.1  [get_ports {n_in[9]}]
set_input_transition -max 0.1  [get_ports {n_in[8]}]
set_input_transition -min 0.1  [get_ports {n_in[8]}]
set_input_transition -max 0.1  [get_ports {n_in[7]}]
set_input_transition -min 0.1  [get_ports {n_in[7]}]
set_input_transition -max 0.1  [get_ports {n_in[6]}]
set_input_transition -min 0.1  [get_ports {n_in[6]}]
set_input_transition -max 0.1  [get_ports {n_in[5]}]
set_input_transition -min 0.1  [get_ports {n_in[5]}]
set_input_transition -max 0.1  [get_ports {n_in[4]}]
set_input_transition -min 0.1  [get_ports {n_in[4]}]
set_input_transition -max 0.1  [get_ports {n_in[3]}]
set_input_transition -min 0.1  [get_ports {n_in[3]}]
set_input_transition -max 0.1  [get_ports {n_in[2]}]
set_input_transition -min 0.1  [get_ports {n_in[2]}]
set_input_transition -max 0.1  [get_ports {n_in[1]}]
set_input_transition -min 0.1  [get_ports {n_in[1]}]
set_input_transition -max 0.1  [get_ports {n_in[0]}]
set_input_transition -min 0.1  [get_ports {n_in[0]}]
set_input_transition -max 0.1  [get_ports {lo_code_in[4]}]
set_input_transition -min 0.1  [get_ports {lo_code_in[4]}]
set_input_transition -max 0.1  [get_ports {lo_code_in[3]}]
set_input_transition -min 0.1  [get_ports {lo_code_in[3]}]
set_input_transition -max 0.1  [get_ports {lo_code_in[2]}]
set_input_transition -min 0.1  [get_ports {lo_code_in[2]}]
set_input_transition -max 0.1  [get_ports {lo_code_in[1]}]
set_input_transition -min 0.1  [get_ports {lo_code_in[1]}]
set_input_transition -max 0.1  [get_ports {lo_code_in[0]}]
set_input_transition -min 0.1  [get_ports {lo_code_in[0]}]
set_input_transition -max 0.1  [get_ports {hi_code_in[4]}]
set_input_transition -min 0.1  [get_ports {hi_code_in[4]}]
set_input_transition -max 0.1  [get_ports {hi_code_in[3]}]
set_input_transition -min 0.1  [get_ports {hi_code_in[3]}]
set_input_transition -max 0.1  [get_ports {hi_code_in[2]}]
set_input_transition -min 0.1  [get_ports {hi_code_in[2]}]
set_input_transition -max 0.1  [get_ports {hi_code_in[1]}]
set_input_transition -min 0.1  [get_ports {hi_code_in[1]}]
set_input_transition -max 0.1  [get_ports {hi_code_in[0]}]
set_input_transition -min 0.1  [get_ports {hi_code_in[0]}]
set_input_transition -max 0.1  [get_ports {m_in[4]}]
set_input_transition -min 0.1  [get_ports {m_in[4]}]
set_input_transition -max 0.1  [get_ports {m_in[3]}]
set_input_transition -min 0.1  [get_ports {m_in[3]}]
set_input_transition -max 0.1  [get_ports {m_in[2]}]
set_input_transition -min 0.1  [get_ports {m_in[2]}]
set_input_transition -max 0.1  [get_ports {m_in[1]}]
set_input_transition -min 0.1  [get_ports {m_in[1]}]
set_input_transition -max 0.1  [get_ports {m_in[0]}]
set_input_transition -min 0.1  [get_ports {m_in[0]}]
set_input_transition -max 0.1  [get_ports positive_in]
set_input_transition -min 0.1  [get_ports positive_in]
set_input_transition -max 0.1  [get_ports constant_in]
set_input_transition -min 0.1  [get_ports constant_in]
set_input_transition -max 0.1  [get_ports constant_gate_in]
set_input_transition -min 0.1  [get_ports constant_gate_in]
