#!/usr/bin/env python3
import json
import os
import sys
import tempfile
import unittest
from pathlib import Path


HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import m859_c2_r25_shared_whitelist_guard as guard  # noqa: E402


# This is deliberately the real runner-style producer shape, not a fixture
# generated by iterating guard.WHITELIST.  A mismatch therefore fails before
# staging and reproduces the class of M856 bug.
PHASE_FILES = (
    "attack/compile.log", "attack/compile.rc",
    "attack/sim.log", "attack/sim.rc",
    "attack/assert.report", "attack/assert.report.disablelog",
    "equalbw/compile.log", "equalbw/compile.rc",
    "equalbw/sim.log", "equalbw/sim.rc",
    "equalbw/assert.report", "equalbw/assert.report.disablelog",
)


def emit_runner_style_population(work):
    work.mkdir()
    (work / "launch_identity.txt").write_text(
        "runner_sha256=" + "1" * 64 + "\n", encoding="utf-8")
    for index, relative in enumerate(PHASE_FILES):
        path = work / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes((relative + "\n").encode("utf-8") + bytes([index]))
    guard.write_pending_receipt(work, "1" * 64, "2" * 64, "3" * 64,
                                "4" * 64, "5" * 64)
    (work / "RUN_COMPLETE.txt").write_text(
        guard.RUN_COMPLETE_STATUS + "\n", encoding="utf-8")
    tool = work / "attack" / "simv.daidir"
    tool.mkdir()
    (tool / "archive.so").write_bytes(b"private VCS tool output\n")
    os.symlink("../simv.daidir/archive.so",
               str(work / "attack" / "tool_archive.so"))


class RunnerPopulationTest(unittest.TestCase):
    def test_actual_r25_population_full_pipeline(self):
        with tempfile.TemporaryDirectory(prefix="m859_runner_population.") as raw:
            root = Path(raw)
            work = root / "work"
            emit_runner_style_population(work)
            actual_runner_evidence = {
                "RUN_COMPLETE.txt", "launch_identity.txt",
                guard.RECEIPT_FILENAME,
            } | set(PHASE_FILES)
            self.assertEqual(actual_runner_evidence, set(guard.WHITELIST))
            receipt = json.loads((work / guard.RECEIPT_FILENAME).read_text(
                encoding="utf-8"))
            self.assertEqual(receipt["schema"], guard.RECEIPT_SCHEMA)
            self.assertEqual(receipt["status"], guard.RECEIPT_STATUS)
            stage = root / "stage"
            staged = guard.stage_result_whitelist(work, stage)
            self.assertEqual(staged["member_count"], 15)
            guard.base.seal_directory(stage)
            before = guard.verify_recursive_sealed_directory(stage)
            destination = root / "canonical"
            after = guard.publish_recursive_noreplace(stage, destination)
            self.assertEqual(before, after)
            self.assertFalse(stage.exists())
            self.assertEqual(
                {p.relative_to(destination).as_posix()
                 for p in destination.rglob("*") if p.is_file()},
                set(guard.RESULT_MEMBERS))

    def test_obsolete_r24_receipt_name_does_not_substitute(self):
        with tempfile.TemporaryDirectory(prefix="m859_old_receipt.") as raw:
            root = Path(raw)
            work = root / "work"
            emit_runner_style_population(work)
            current = work / guard.RECEIPT_FILENAME
            current.rename(work /
                "m851_c2_r24_recursive_seal_vcs_receipt_r1.json")
            with self.assertRaises(guard.base.Failure):
                guard.stage_result_whitelist(work, root / "stage")

    def test_receipt_schema_and_status_are_bound(self):
        for key, wrong in (("schema", "wrong_schema"),
                           ("status", "wrong_status")):
            with self.subTest(key=key):
                with tempfile.TemporaryDirectory(
                        prefix="m859_receipt_identity.") as raw:
                    root = Path(raw)
                    work = root / "work"
                    emit_runner_style_population(work)
                    path = work / guard.RECEIPT_FILENAME
                    value = json.loads(path.read_text(encoding="utf-8"))
                    value[key] = wrong
                    path.write_text(json.dumps(value, indent=2,
                                                sort_keys=True) + "\n",
                                    encoding="utf-8")
                    with self.assertRaises(guard.base.Failure):
                        guard.stage_result_whitelist(work, root / "stage")

    def test_real_runner_uses_central_receipt_writer(self):
        runner = (HERE.parent /
            "dc_handoff/scripts/run_vcs_m859_c2_r25_shared_whitelist_exact_sha.sh")
        text = runner.read_text(encoding="utf-8")
        self.assertEqual(text.count("write-pending-receipt"), 1)
        self.assertNotIn(guard.RECEIPT_FILENAME, text)
        self.assertNotIn("m851_c2_r24_recursive_seal_vcs_receipt", text)
        self.assertEqual(text.count("stage-result-whitelist"), 1)
        self.assertEqual(text.count("verify-recursive-sealed-directory"), 2)
        self.assertEqual(text.count("publish-recursive-no-replace"), 1)


if __name__ == "__main__":
    unittest.main()
