+define+M979_AXIS_K8
+define+SVA_RUNTIME_ENABLED
/opt/tech/tsmc28/StandardCell/tcbn28hpcplusbwp35p140_190a/TSMCHOME/digital/Front_End/verilog/tcbn28hpcplusbwp35p140_110a/tcbn28hpcplusbwp35p140.v
/home/zhumd/work/sdformer_codex/SDformer/hw_autoresearch_nts07/dc_handoff/runs/m872_m803_c2_r16_channel_split_three_axis_logic_only_dc_3p000ns_r1_20260829/k8/netlist/m803_fc2_channel_split_registered_release_matched_8bank_raw4_acc24_mapped.v
/home/zhumd/work/sdformer_codex/SDformer/hw_autoresearch_nts07/dc_handoff/tb/m1332_c2_production_activity_reset_safe_memory_model.sv
/home/zhumd/work/sdformer_codex/SDformer/hw_autoresearch_nts07/dc_handoff/tb/tb_m979_c2_three_axis_mapped_gate_case_saif.sv
/home/zhumd/work/sdformer_codex/SDformer/hw_autoresearch_nts07/dc_handoff/tb/m1332_c2_production_activity_assertions.sv
/home/zhumd/work/sdformer_codex/SDformer/hw_autoresearch_nts07/dc_handoff/tb/tb_m1332_c2_headline_mapped_production_activity.sv
