create_clock -name core_clk -period 3.000 [get_ports core_clk]
set_clock_uncertainty 0.100 [get_clocks core_clk]
set_clock_transition 0.050 [get_clocks core_clk]
set_input_delay 0.200 -clock core_clk [remove_from_collection [all_inputs] [get_ports {core_clk reset_n}]]
set_output_delay 0.200 -clock core_clk [all_outputs]
set_false_path -from [get_ports reset_n]
set_load 0.010 [all_outputs]
set_max_transition 0.500 [current_design]
set_max_fanout 32 [current_design]
