// Research leaf: interval evidence is supplied, not generated by this module.
// No production H67 arithmetic, memory macro, or performance admission.
module atlif_threshold_packet_encoder #(
    parameter int B = 32,
    parameter int K = 4,
    parameter int W = 32,
    parameter int PACKET_W = B + 2*(W+1) + 2
                          + K*(2*(W+1)+$clog2(B)+1) + 82
) (
    input  logic clk,
    input  logic rst_n,
    input  logic start_valid_i,
    output logic start_ready_o,
    input  logic [31:0] context_i,
    input  logic [15:0] epoch_i,
    input  logic [31:0] theta_payload_i,
    input  logic reverse_i,
    input  logic signed [W-1:0] predicted_tau_i,
    input  logic in_valid_i,
    output logic in_ready_o,
    input  logic signed [W-1:0] u_lo_i,
    input  logic signed [W-1:0] u_hi_i,
    output logic packet_valid_o,
    input  logic packet_ready_i,
    output logic [PACKET_W-1:0] packet_o
);
    localparam int NW = W+1;
    localparam int IW = $clog2(B);
    localparam int KS = (K > 0) ? K : 1;
    localparam int CW = (KS > 1) ? $clog2(KS) : 1;
    localparam int ENTRY_W = 2*NW + IW + 1;
    localparam int A_OFF = B;
    localparam int B_OFF = A_OFF + NW;
    localparam int AV_OFF = B_OFF + NW;
    localparam int BV_OFF = AV_OFF + 1;
    localparam int KEEP_OFF = BV_OFF + 1;
    localparam int META_OFF = KEEP_OFF + K*ENTRY_W;

    typedef enum logic [1:0] {IDLE, COLLECT, EXPORT} state_t;
    state_t state_q;
    logic [IW:0] count_q;
    logic [31:0] context_q, theta_q;
    logic [15:0] epoch_q;
    logic reverse_q, error_q;
    logic signed [NW-1:0] prediction_q;
    logic [B-1:0] bits_q;
    logic signed [NW-1:0] a_q, b_q;
    logic a_valid_q, b_valid_q;
    logic [KS-1:0] kept_valid_q;
    logic signed [NW-1:0] kept_lo_q [KS];
    logic signed [NW-1:0] kept_hi_q [KS];
    logic [IW-1:0] kept_index_q [KS];
    logic [NW:0] kept_distance_q [KS];

    logic signed [NW-1:0] norm_lo, norm_hi;
    logic signed [NW:0] distance_wide;
    logic [NW:0] distance_now;
    logic bit_now, do_keep, do_discard, discard_bit;
    logic signed [NW-1:0] discard_lo, discard_hi;
    logic [CW-1:0] chosen, worst;
    integer vacant;

    initial begin
        if (B < 2 || K < 0 || K > B || W < 2)
            $fatal(1, "Unsupported B/K/W parameters");
        if (PACKET_W != META_OFF + 82)
            $fatal(1, "Packet width mismatch");
    end

    always_comb begin
        norm_lo = $signed({u_lo_i[W-1], u_lo_i});
        norm_hi = $signed({u_hi_i[W-1], u_hi_i});
        if (reverse_q) begin
            norm_lo = -$signed({u_hi_i[W-1], u_hi_i});
            norm_hi = -$signed({u_lo_i[W-1], u_lo_i});
        end
        bit_now = norm_lo >= prediction_q;
        distance_wide = '0;
        if (norm_lo > prediction_q)
            distance_wide = $signed({norm_lo[NW-1], norm_lo})
                          - $signed({prediction_q[NW-1], prediction_q});
        else if (norm_hi < prediction_q)
            distance_wide = $signed({prediction_q[NW-1], prediction_q})
                          - $signed({norm_hi[NW-1], norm_hi});
        distance_now = $unsigned(distance_wide);

        vacant = -1;
        worst = 0;
        for (int i = 0; i < K; i++) begin
            if (!kept_valid_q[i] && vacant < 0) vacant = i;
            if ((kept_distance_q[i] > kept_distance_q[worst]) ||
                ((kept_distance_q[i] == kept_distance_q[worst]) &&
                 (kept_index_q[i] > kept_index_q[worst]))) worst = CW'(i);
        end
        chosen = 0;
        do_keep = 1'b0;
        do_discard = 1'b1;
        discard_lo = norm_lo;
        discard_hi = norm_hi;
        discard_bit = bit_now;
        if (K > 0) begin
            if (vacant >= 0) begin
                chosen = CW'(vacant);
                do_keep = 1'b1;
                do_discard = 1'b0;
            end else if (distance_now < kept_distance_q[worst]) begin
                chosen = CW'(worst);
                do_keep = 1'b1;
                discard_lo = kept_lo_q[worst];
                discard_hi = kept_hi_q[worst];
                discard_bit = bits_q[kept_index_q[worst]];
            end
        end
    end

    assign start_ready_o = state_q == IDLE;
    assign in_ready_o = state_q == COLLECT;
    assign packet_valid_o = state_q == EXPORT;

    always_comb begin
        packet_o = '0;
        packet_o[0 +: B] = bits_q;
        packet_o[A_OFF +: NW] = a_q;
        packet_o[B_OFF +: NW] = b_q;
        packet_o[AV_OFF] = a_valid_q;
        packet_o[BV_OFF] = b_valid_q;
        for (int i = 0; i < K; i++) begin
            packet_o[KEEP_OFF+i*ENTRY_W +: NW] = kept_lo_q[i];
            packet_o[KEEP_OFF+i*ENTRY_W+NW +: NW] = kept_hi_q[i];
            packet_o[KEEP_OFF+i*ENTRY_W+2*NW +: IW] = kept_index_q[i];
            packet_o[KEEP_OFF+i*ENTRY_W+2*NW+IW] = kept_valid_q[i];
        end
        packet_o[META_OFF +: 32] = context_q;
        packet_o[META_OFF+32 +: 16] = epoch_q;
        packet_o[META_OFF+48 +: 32] = theta_q;
        packet_o[META_OFF+80] = reverse_q;
        packet_o[META_OFF+81] = error_q;
    end

    always_ff @(posedge clk) begin
        if (!rst_n) begin
            state_q <= IDLE;
            count_q <= '0;
            context_q <= '0;
            epoch_q <= '0;
            theta_q <= '0;
            reverse_q <= 1'b0;
            error_q <= 1'b0;
            prediction_q <= '0;
            bits_q <= '0;
            a_q <= '0;
            b_q <= '0;
            a_valid_q <= 1'b0;
            b_valid_q <= 1'b0;
            kept_valid_q <= '0;
            for (int i = 0; i < KS; i++) begin
                kept_lo_q[i] <= '0;
                kept_hi_q[i] <= '0;
                kept_index_q[i] <= '0;
                kept_distance_q[i] <= '0;
            end
        end else begin
            case (state_q)
                IDLE: if (start_valid_i) begin
                    state_q <= COLLECT;
                    count_q <= '0;
                    context_q <= context_i;
                    epoch_q <= epoch_i;
                    theta_q <= theta_payload_i;
                    reverse_q <= reverse_i;
                    prediction_q <= reverse_i
                        ? -$signed({predicted_tau_i[W-1], predicted_tau_i})
                        :  $signed({predicted_tau_i[W-1], predicted_tau_i});
                    error_q <= 1'b0;
                    bits_q <= '0;
                    a_q <= '0;
                    b_q <= '0;
                    a_valid_q <= 1'b0;
                    b_valid_q <= 1'b0;
                    kept_valid_q <= '0;
                    for (int i = 0; i < KS; i++) begin
                        kept_lo_q[i] <= '0;
                        kept_hi_q[i] <= '0;
                        kept_index_q[i] <= '0;
                        kept_distance_q[i] <= '0;
                    end
                end
                COLLECT: if (in_valid_i) begin
                    if (u_lo_i > u_hi_i) error_q <= 1'b1;
                    bits_q[count_q[IW-1:0]] <= bit_now;
                    if (do_keep) begin
                        kept_valid_q[chosen] <= 1'b1;
                        kept_lo_q[chosen] <= norm_lo;
                        kept_hi_q[chosen] <= norm_hi;
                        kept_index_q[chosen] <= count_q[IW-1:0];
                        kept_distance_q[chosen] <= distance_now;
                    end
                    if (do_discard) begin
                        if (!discard_bit) begin
                            if (!a_valid_q || discard_hi > a_q) a_q <= discard_hi;
                            a_valid_q <= 1'b1;
                        end else begin
                            if (!b_valid_q || discard_lo < b_q) b_q <= discard_lo;
                            b_valid_q <= 1'b1;
                        end
                    end
                    if (count_q == (IW+1)'(B-1)) state_q <= EXPORT;
                    else count_q <= count_q + 1'b1;
                end
                EXPORT: if (packet_ready_i) state_q <= IDLE;
                default: state_q <= IDLE;
            endcase
        end
    end
endmodule
