artifact_location: file:///root/private_data/work/sdformer_codex/SDformer/mlruns_local/214610415547705293
creation_time: 1783499152644
experiment_id: '214610415547705293'
last_update_time: 1783499152644
lifecycle_stage: active
name: date11_ttx_mdr_mvsec_ep20_calib_lr025_ep26
trace_location: null
workspace: default
