#!/usr/bin/env python3
"""Exact-SHA independent closure audit for the corrected M109-r2 frontier.

This checker consumes the four-window raw reconstruction and dual-timeline
results generated by the separate M109-r1 hammer, not any producer analyzer.
It then verifies every M109-r2 recurrence field exposed at W43/W64/W294/W384,
the storage arithmetic, M108-r3 W64 common-field identity, the revoked-r1
boundary, the 2.5x crossing, and all projection/admission labels.
"""

import hashlib
import json
import math
from pathlib import Path


REVIEW = Path(__file__).resolve().parent
HW = REVIEW.parents[1]
WINDOWS = (43, 64, 294, 384)

M109_R2_SCRIPT = HW / "system_simulator/scripts/analyze_m109_r2_window_storage_dual_timeline_frontier.py"
M109_R2_CONTRACT = HW / "contracts/m109_r2_window_storage_dual_timeline_frontier_contract_r1_20260824.json"
M109_R1_REVOCATION = HW / "contracts/m109_r1_cycle_schedule_revocation_r1_20260824.json"
M109_R2_DIR = HW / "results/m109_r2_window_storage_dual_timeline_frontier_r1_20260824"
M109_R2_RESULT = M109_R2_DIR / "m109_r2_window_storage_dual_timeline_frontier.json"
M109_R2_RUN = M109_R2_DIR / "RUN_COMPLETE.txt"
M109_R2_MANIFEST = M109_R2_DIR / "manifest.sha256"
M108_R3_RESULT = HW / "results/m108_r3_dual_timeline_fused_schedule_r1_20260824/m108_r3_dual_timeline_fused_schedule.json"
M108_R3_RUN = HW / "results/m108_r3_dual_timeline_fused_schedule_r1_20260824/RUN_COMPLETE.txt"
M106_RTL = HW / "rtl_m106/m106_bounded_bitmap_transpose_scheduler.sv"
R1_HAMMER_DIR = HW / "reviews/m109_window_storage_rtl_edge_frontier_independent_hammer_r1_20260824"
R1_HAMMER_SCRIPT = R1_HAMMER_DIR / "audit_m109_window_storage_rtl_edge_frontier.py"
R1_HAMMER_RESULT = R1_HAMMER_DIR / "m109_window_storage_rtl_edge_frontier_independent_audit.json"
DOC359 = HW / "docs/359_DATE终局冻结_20260813.md"

EXPECTED_SHA = {
    M109_R2_SCRIPT: "4eed1e1ef25cdbea0fdd40d1602d6b1eb7661b15b5ae47541c80e149fd060ada",
    M109_R2_CONTRACT: "d80efd387bb6b5b01371ca7ed5d07d8e2ec97f3efa93aa1d385cc80281f63b44",
    M109_R1_REVOCATION: "69f9962e8720b185a49a1a75cb7178932cbaf08bfd2cf0e3e93aaf4356cc186e",
    M109_R2_RESULT: "ee61b90ee894c6e6c778b815a52f1d8b6edc9c877227bc4987e4b135aa16c321",
    M109_R2_RUN: "c0eb8fd06d21da14b496c16f4709c85af55e0eb3bd9c44938c935bbf16c8a6c9",
    M109_R2_MANIFEST: "3da3f081f867edadf4767ddd78413cfec4a6187055ab6ec3d2fb5b365be3b1ba",
    M108_R3_RESULT: "d5a4d7c27a91a7735ed4481100d0db3640191357e4617e043378bb367a77dacc",
    M108_R3_RUN: "75bf2446fea8deed69014288ebdfe7bc9f2ad22a43249b68a56ee0283c12e32c",
    M106_RTL: "a6937765aea87269c3d38123b656c72b7ee400e36b0d634f21ab9c7dbdefc0b7",
    R1_HAMMER_SCRIPT: "1390b8fde50ba503aa588d024bcbcd1652f239ac68c45d4fb51506561dd13781",
    R1_HAMMER_RESULT: "bd357bf9d2962836449014757e938c9b6a4ffda61d341236c612c50ca040a489",
    DOC359: "dedde7ce44c3e595098f25ce6550dc0f6dfd66ce7227bcffd3dab0426a7bdfc4",
}


def require(condition, message):
    if not condition:
        raise ValueError(message)


def sha256(path):
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def strict_json(path):
    def reject(raw):
        raise ValueError("non-standard JSON constant: " + raw)

    def pairs_hook(pairs):
        result = {}
        for key, value in pairs:
            require(key not in result, "duplicate JSON key: " + key)
            result[key] = value
        return result

    return json.loads(Path(path).read_text(encoding="utf-8"),
                      object_pairs_hook=pairs_hook, parse_constant=reject)


def verify_manifest(path, base):
    checked = 0
    for raw in Path(path).read_text(encoding="utf-8").splitlines():
        if not raw.strip():
            continue
        expected, name = raw.split(None, 1)
        target = Path(base) / name.strip()
        require(target.is_file(), "manifest target missing: " + str(target))
        require(sha256(target) == expected, "manifest target mismatch: " + str(target))
        checked += 1
    return checked


def same_value(left, right):
    if isinstance(left, float) or isinstance(right, float):
        return math.isclose(float(left), float(right), rel_tol=0.0, abs_tol=1e-15)
    return left == right


def main():
    start_sha = sha256(Path(__file__).resolve())
    observed = {}
    for path, expected in EXPECTED_SHA.items():
        actual = sha256(path)
        require(actual == expected, "identity drift {} {}".format(path, actual))
        observed[str(path.relative_to(HW))] = actual
    require(verify_manifest(M109_R2_MANIFEST, M109_R2_DIR) == 5,
            "M109-r2 manifest extent drift")

    producer = strict_json(M109_R2_RESULT)
    contract = strict_json(M109_R2_CONTRACT)
    revocation = strict_json(M109_R1_REVOCATION)
    m108_r3 = strict_json(M108_R3_RESULT)
    independent = strict_json(R1_HAMMER_RESULT)
    producer_rows = {row["window_rows"]: row for row in producer["frontier"]}
    independent_rows = {row["window_rows"]: row
                        for row in independent["audited_windows"]}

    require(revocation["status"] == "REVOKED_M109_R1_SCHEDULED_FRONTIER_ADMISSION"
            and revocation["m109_r1_scheduled_ratio_admitted"] is False,
            "M109-r1 revocation missing")
    source_text = M109_R2_SCRIPT.read_text(encoding="utf-8")
    require("self.controller_free = 0" in source_text
            and "dispatch_ready = max(fill_end, self.controller_free) + 1" in source_text,
            "controller_free recurrence missing")
    rtl_text = M106_RTL.read_text(encoding="utf-8")
    require("if (!drain_active_q" in rtl_text
            and "if (WIN_ROWS != 64" in rtl_text,
            "M106 controller/projection boundary evidence missing")

    audited = []
    for window in WINDOWS:
        row = producer_rows[window]
        reference = independent_rows[window]
        corrected = reference["prior_drain_aware_dual_timeline"]
        require(row["exact_work"] == reference["work"],
                "raw work mismatch W{}".format(window))
        field_matches = {}
        for key, value in row["dual_timeline_recurrence"].items():
            require(key in corrected, "independent field absent W{} {}".format(window, key))
            require(same_value(value, corrected[key]),
                    "dual timeline mismatch W{} {}".format(window, key))
            field_matches[key] = True
        require(row["storage_lower_bound"] == reference["storage_reconstruction"],
                "storage mismatch W{}".format(window))
        require(row["windows_per_phase"] == int(math.ceil(3000.0 / window)),
                "window count mismatch W{}".format(window))
        audited.append({
            "window_rows": window,
            "independent_raw_work_match": True,
            "independent_dual_timeline_fields_matched": len(field_matches),
            "independent_dual_timeline_all_exposed_fields_match": True,
            "ordered_descriptor_sha256": corrected["ordered_descriptor_sha256"],
            "storage_all_fields_match": True,
            "candidate_cycles": row["dual_timeline_recurrence"]["candidate_cycles"],
            "same_clock_service_island_ratio":
                row["dual_timeline_recurrence"]["same_clock_service_island_ratio"],
            "combined_storage_bytes_lower_bound": row["storage_lower_bound"]
                ["combined_bytes_ceiling_before_control_ecc_macro_rounding"],
            "controller_geometry_vcs": row["admission"]["controller_geometry_vcs"],
        })

    w64 = producer_rows[64]["dual_timeline_recurrence"]
    frozen_w64 = m108_r3["dual_timeline_schedule"]
    common_keys = sorted(set(w64) & set(frozen_w64))
    require(len(common_keys) == 22 and all(same_value(w64[key], frozen_w64[key])
                                           for key in common_keys),
            "W64 common-field M108-r3 mismatch")
    missing_from_m109 = sorted(set(frozen_w64) - set(w64))
    require(missing_from_m109 == ["ordered_descriptor_sha256"],
            "unexpected W64 field-set difference")
    require(independent_rows[64]["prior_drain_aware_dual_timeline"]
            ["ordered_descriptor_sha256"] == frozen_w64["ordered_descriptor_sha256"],
            "independent W64 descriptor digest mismatch")

    require(producer_rows[294]["dual_timeline_recurrence"]
            ["same_clock_service_island_ratio"] < 2.5,
            "W294 threshold flipped")
    require(producer_rows[384]["dual_timeline_recurrence"]
            ["same_clock_service_island_ratio"] > 2.5,
            "W384 threshold flipped")
    require(all(producer_rows[w]["admission"]["controller_geometry_vcs"] is False
                for w in WINDOWS if w != 64),
            "non-W64 VCS projection boundary drift")
    require(producer["model_boundary"]["full_lane_numeric_accumulator_miter"]
            is False and producer["model_boundary"]["precompaction_schedule"] is False,
            "model boundary drift")

    payload = {
        "schema": "m109_r2_window_storage_dual_timeline_frontier_independent_audit_v1",
        "status": "PASS_R1_P0_CLOSED_IN_SOFTWARE_RECURRENCE_RAW_STORAGE_THRESHOLD_REPRODUCED_PORT_CUTS_REMAIN",
        "identity": observed,
        "manifest_entries_verified": 5,
        "r1_revocation_verified": True,
        "controller_free_repair": {
            "implemented_in_producer": True,
            "matches_prior_independent_dual_timeline_all_four_windows": True,
            "r1_prior_drain_serialization_p0_closed_in_software_recurrence": True,
            "actual_combined_controller_cycle_miter": False,
        },
        "audited_windows": audited,
        "w64_m108_r3_identity": {
            "common_schedule_fields": len(common_keys),
            "all_common_schedule_fields_match": True,
            "candidate_cycles": 521264186,
            "ratio": 2.1387700477853278,
            "m109_missing_field": "ordered_descriptor_sha256",
            "independent_digest_matches_m108_r3": True,
            "ordered_descriptor_sha256": frozen_w64["ordered_descriptor_sha256"],
        },
        "threshold_attack": {
            "w294_ratio": producer_rows[294]["dual_timeline_recurrence"]
                ["same_clock_service_island_ratio"],
            "w294_below_2p5": True,
            "w384_ratio": producer_rows[384]["dual_timeline_recurrence"]
                ["same_clock_service_island_ratio"],
            "w384_above_2p5": True,
        },
        "baseline_fairness": {
            "fixed8_tokens": 1114383288,
            "candidate_and_baseline_share_commit_and_flush": True,
            "controller_and_descriptor_ingress_edges_charged_to_baseline": False,
            "verdict": "conditional service-token denominator, not equal-controller end-to-end cycles",
        },
        "projection_boundary": {
            "w64_controller_geometry_vcs": True,
            "non_w64_controller_geometry_vcs": False,
            "non_w64_parameterized_projection": True,
            "full_lane_accumulator_vcs": False,
            "storage_is_lower_bound": True,
            "physical_speedup": False,
            "equal_area": False,
            "system_speedup": False,
            "headline": False,
        },
        "docs_359_sha256_unchanged": sha256(DOC359),
        "producer_analyzer_executed": False,
        "production_files_modified": False,
    }
    require(sha256(Path(__file__).resolve()) == start_sha,
            "independent auditor changed during run")
    output = REVIEW / "m109_r2_window_storage_dual_timeline_frontier_independent_audit.json"
    require(not output.exists(), "refusing independent output overwrite")
    output.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n",
                      encoding="utf-8")
    print("PASS M109R2 independent: W64=521264186/2.138770047785 "
          "W294<2.5 W384>2.5", flush=True)


if __name__ == "__main__":
    main()
